// DO NOT EDIT — generated by apps/server/cmd/wsgen.
//
// Regenerate with:
//   cd apps/server && go run ./cmd/wsgen
//
// Source of truth: apps/server/internal/ws/envelope_catalog_*.go
// Any hand edit will be overwritten by the next go generate run.
// Phase 19 PR-1 (2026-04-18).
//
// Catalog: 135 events (active=130, stub=3, deprec=2) · 10 //wsgen:payload structs.

/* eslint-disable */
/* prettier-ignore */

/** All WebSocket event wire types. Single source of truth: Go Catalog. */
export const WsEventType = {
  /** C2S · accusation */
  ACCUSATION_ACCUSE: "accusation:accuse",
  /** C2S · accusation */
  ACCUSATION_RESET: "accusation:reset",
  /** C2S · accusation */
  ACCUSATION_VOTE: "accusation:vote",
  /** S2C · audio */
  AUDIO_PLAY_MEDIA: "audio.play_media",
  /** S2C · audio */
  AUDIO_PLAY_SOUND: "audio.play_sound",
  /** S2C · audio */
  AUDIO_PLAY_VOICE: "audio.play_voice",
  /** S2C · audio */
  AUDIO_SET_BGM: "audio.set_bgm",
  /** S2C · audio */
  AUDIO_STOP: "audio.stop",
  /** C2S · audio */
  AUDIO_PAUSE: "audio:pause",
  /** C2S · audio */
  AUDIO_PLAY: "audio:play",
  /** C2S · audio */
  AUDIO_RESUME: "audio:resume",
  /** C2S · audio */
  AUDIO_STOP_LEGACY: "audio:stop",
  /**
   * S2C · auth
   * server asks for re-auth before a sensitive action; payload AuthChallengePayload
   */
  AUTH_CHALLENGE: "auth.challenge",
  /**
   * C2S · auth
   * client presents refreshed credentials post-upgrade; payload AuthIdentifyPayload
   */
  AUTH_IDENTIFY: "auth.identify",
  /**
   * S2C · auth
   * resume target stale; resumable bool guides retry policy (Discord INVALID_SESSION); payload AuthInvalidSessionPayload
   */
  AUTH_INVALID_SESSION: "auth.invalid_session",
  /**
   * C2S · auth
   * client requests a rotated token before expiry; payload AuthRefreshPayload
   */
  AUTH_REFRESH: "auth.refresh",
  /**
   * S2C · auth
   * server signals token approaching expiry; payload AuthRefreshRequiredPayload
   */
  AUTH_REFRESH_REQUIRED: "auth.refresh_required",
  /**
   * C2S · auth
   * client resumes session after reconnect (Discord gateway RESUME); payload AuthResumePayload
   */
  AUTH_RESUME: "auth.resume",
  /**
   * S2C · auth
   * server notifies client its session was invalidated (ban, logout-elsewhere); payload AuthRevokedPayload
   */
  AUTH_REVOKED: "auth.revoked",
  /**
   * S2C · auth
   * server's response to auth.refresh — new access token + expiry; payload AuthTokenIssuedPayload
   */
  AUTH_TOKEN_ISSUED: "auth.token_issued",
  /** S2C · chat */
  CHAT_MESSAGE: "chat:message",
  /** S2C · chat */
  CHAT_READ_RECEIPT: "chat:read_receipt",
  /** C2S · chat */
  CHAT_SEND: "chat:send",
  /** S2C · chat */
  CHAT_TYPING_INDICATOR: "chat:typing_indicator",
  /** S2C · chat */
  CHAT_WHISPER: "chat:whisper",
  /** S2C · clue */
  CLUE_ACQUIRED: "clue.acquired",
  /** S2C · clue */
  CLUE_ITEM_DECLARED: "clue.item_declared",
  /** S2C · clue */
  CLUE_ITEM_RESOLVED: "clue.item_resolved",
  /** S2C · clue */
  CLUE_PEEK_RESULT: "clue.peek_result",
  /** C2S · clue */
  CLUE_SHOW_ACCEPT: "clue:show_accept",
  /** C2S · clue */
  CLUE_SHOW_DECLINE: "clue:show_decline",
  /** C2S · clue */
  CLUE_SHOW_REQUEST: "clue:show_request",
  /** C2S · clue */
  CLUE_TRADE_ACCEPT: "clue:trade_accept",
  /** C2S · clue */
  CLUE_TRADE_DECLINE: "clue:trade_decline",
  /** C2S · clue */
  CLUE_TRADE_PROPOSE: "clue:trade_propose",
  /** C2S · clue */
  CLUE_USE: "clue:use",
  /** C2S · clue */
  CLUE_USE_CANCEL: "clue:use_cancel",
  /** C2S · clue */
  CLUE_USE_TARGET: "clue:use_target",
  /** C2S · conditional */
  CONDITIONAL_STATUS: "conditional:status",
  /**
   * S2C · system
   * first server frame on upgrade; payload is ConnectedPayload
   */
  CONNECTED: "connected",
  /** C2S · consensus */
  CONSENSUS_PROPOSE: "consensus:propose",
  /** C2S · consensus */
  CONSENSUS_VOTE: "consensus:vote",
  /** S2C · ending */
  ENDING_COMPLETED: "ending.completed",
  /** S2C · ending */
  ENDING_REVEAL_STEP: "ending.reveal_step",
  /** C2S · ending */
  ENDING_NEXT_REVEAL: "ending:next_reveal",
  /**
   * S2C · system
   * wire payload is ErrorPayload { code, message }
   */
  ERROR: "error",
  /** C2S · event */
  EVENT_TRIGGER: "event:trigger",
  /** C2S · explore */
  EXPLORE_EXAMINE: "explore:examine",
  /** C2S · explore */
  EXPLORE_MOVE: "explore:move",
  /** C2S · explore */
  EXPLORE_START: "explore:start",
  /** C2S · floor */
  FLOOR_CHANGE: "floor:change",
  /** C2S · floor */
  FLOOR_SELECT: "floor:select",
  /** S2C · friend */
  FRIEND_ACCEPTED: "friend:accepted",
  /** S2C · friend */
  FRIEND_REQUEST: "friend:request",
  /**
   * C2S · game
   * status=stub
   * FE send-only; server uses legacy per-action types. Phase 20 — unify or migrate
   */
  GAME_ACTION: "game.action",
  /**
   * S2C · game
   * status=stub
   * FE listen-only; server yet to emit ACK envelopes
   */
  GAME_ACTION_RESULT: "game.action_result",
  /**
   * S2C · game
   * status=stub
   * FE listen-only; server currently uses ending.completed instead
   */
  GAME_END: "game.end",
  /**
   * S2C · game
   * legacy alias observed in tests; verify vs game.started
   */
  GAME_START: "game.start",
  /** S2C · game */
  GAME_STARTED: "game.started",
  /** C2S · gm */
  GM_ADVANCE_PHASE: "gm:advance_phase",
  /** C2S · gm */
  GM_BROADCAST_MESSAGE: "gm:broadcast_message",
  /** C2S · gm */
  GM_PLAY_MEDIA: "gm:play_media",
  /** C2S · gm */
  GM_SHOW_ENDING: "gm:show_ending",
  /** C2S · gm */
  GM_START_PLAYING: "gm:start_playing",
  /** C2S · gm */
  GM_START_PROLOGUE: "gm:start_prologue",
  /** C2S · gm */
  GM_TOGGLE_VOTING: "gm:toggle_voting",
  /** C2S · group */
  GROUP_CREATE: "group:create",
  /** C2S · group */
  GROUP_INVITE: "group:invite",
  /** C2S · group */
  GROUP_LEAVE: "group:leave",
  /** C2S · group */
  GROUP_SEND: "group:send",
  /** C2S · groupchat */
  GROUPCHAT_JOIN: "groupchat:join",
  /** C2S · groupchat */
  GROUPCHAT_LEAVE: "groupchat:leave",
  /** C2S · groupchat */
  GROUPCHAT_SEND: "groupchat:send",
  /** C2S · hybrid */
  HYBRID_CONSENSUS_VOTE: "hybrid:consensus_vote",
  /** C2S · hybrid */
  HYBRID_TRIGGER_EVENT: "hybrid:trigger_event",
  /** C2S · location */
  LOCATION_SEARCH: "location:search",
  /** C2S · mission */
  MISSION_CHECK: "mission:check",
  /** C2S · mission */
  MISSION_REPORT: "mission:report",
  /** C2S · mission */
  MISSION_VERIFY: "mission:verify",
  /**
   * S2C · module
   * catch-all for module-specific domain events; payload.moduleId gates dispatch
   */
  MODULE_EVENT: "module.event",
  /** S2C · module */
  MODULE_STATE: "module.state",
  /** S2C · phase */
  PHASE_ADVANCED: "phase.advanced",
  /**
   * S2C · phase
   * status=deprec
   * colon form; prefer phase.advanced
   */
  PHASE_ENTERED: "phase:entered",
  /** BIDI · system */
  PING: "ping",
  /** S2C · player */
  PLAYER_JOINED: "player.joined",
  /** S2C · player */
  PLAYER_LEFT: "player.left",
  /** BIDI · system */
  PONG: "pong",
  /** S2C · presentation */
  PRESENTATION_SET_BACKGROUND: "presentation.set_background",
  /** S2C · presentation */
  PRESENTATION_SET_THEME_COLOR: "presentation.set_theme_color",
  /** S2C · reading */
  READING_COMPLETED: "reading.completed",
  /** S2C · reading */
  READING_LINE_CHANGED: "reading.line_changed",
  /** S2C · reading */
  READING_PAUSED: "reading.paused",
  /** S2C · reading */
  READING_RESUMED: "reading.resumed",
  /**
   * S2C · reading
   * engine-origin; overlaps with reading:started — dedupe in Phase 20
   */
  READING_STARTED: "reading.started",
  /** C2S · reading */
  READING_ADVANCE: "reading:advance",
  /** S2C · reading */
  READING_COMPLETED_LEGACY: "reading:completed",
  /** C2S · reading */
  READING_JUMP: "reading:jump",
  /** S2C · reading */
  READING_LINE_CHANGED_LEGACY: "reading:line_changed",
  /** S2C · reading */
  READING_PAUSED_LEGACY: "reading:paused",
  /** S2C · reading */
  READING_RESUMED_LEGACY: "reading:resumed",
  /** S2C · reading */
  READING_STARTED_LEGACY: "reading:started",
  /** S2C · reading */
  READING_STATE: "reading:state",
  /** C2S · reading */
  READING_VOICE_ENDED: "reading:voice_ended",
  /** S2C · ready */
  READY_ALL_READY: "ready.all_ready",
  /** S2C · ready */
  READY_STATUS_CHANGED: "ready.status_changed",
  /** C2S · ready */
  READY_TOGGLE: "ready:toggle",
  /**
   * S2C · system
   * server-initiated hint for clients to re-establish
   */
  RECONNECT: "reconnect",
  /** C2S · room */
  ROOM_DESELECT_CHARACTER: "room:deselect_character",
  /** C2S · room */
  ROOM_EXAMINE: "room:examine",
  /** C2S · room */
  ROOM_MOVE: "room:move",
  /** C2S · room */
  ROOM_SELECT_CHARACTER: "room:select_character",
  /** C2S · round_clue */
  ROUND_CLUE_STATUS: "round_clue:status",
  /** C2S · script */
  SCRIPT_SKIP: "script:skip",
  /**
   * S2C · session
   * snapshot; payload redacted per player by session actor
   */
  SESSION_STATE: "session:state",
  /** C2S · skip */
  SKIP_AGREE: "skip:agree",
  /** C2S · skip */
  SKIP_DISAGREE: "skip:disagree",
  /** C2S · skip */
  SKIP_REQUEST: "skip:request",
  /**
   * BIDI · sound
   * server-authored broadcast uses the same type from domain/sound/handler
   */
  SOUND_PLAY: "sound:play",
  /** C2S · sound */
  SOUND_STOP: "sound:stop",
  /** C2S · spatial */
  SPATIAL_MOVE: "spatial:move",
  /** C2S · starting */
  STARTING_STATUS: "starting:status",
  /** C2S · timed_clue */
  TIMED_CLUE_START: "timed_clue:start",
  /** C2S · timed_clue */
  TIMED_CLUE_STOP: "timed_clue:stop",
  /** C2S · timed_clue */
  TIMED_CLUE_TICK: "timed_clue:tick",
  /**
   * BIDI · voice
   * client intent; server also broadcasts via domain/bridge/voice_bridge
   */
  VOICE_JOIN: "voice:join",
  /** BIDI · voice */
  VOICE_LEAVE: "voice:leave",
  /** BIDI · voice */
  VOICE_MUTE: "voice:mute",
  /** S2C · voice */
  VOICE_STATE: "voice:state",
  /**
   * S2C · voice
   * LiveKit short-lived token issued after room.join
   */
  VOICE_TOKEN: "voice:token",
  /** BIDI · voice */
  VOICE_UNMUTE: "voice:unmute",
  /** S2C · vote */
  VOTE_CAST: "vote.cast",
  /** C2S · vote */
  VOTE_CAST_LEGACY: "vote:cast",
  /** C2S · vote */
  VOTE_CHANGE: "vote:change",
  /**
   * S2C · vote
   * status=deprec
   * colon form; prefer vote.tallied after Phase 20
   */
  VOTE_TALLIED: "vote:tallied",
  /** C2S · whisper */
  WHISPER_SEND: "whisper:send",
} as const;

export type WsEventType = (typeof WsEventType)[keyof typeof WsEventType];

/** Direction each event may travel. */
export const WsEventDirection: Readonly<Record<WsEventType, "c2s" | "s2c" | "bidi">> = {
  "accusation:accuse": "c2s",
  "accusation:reset": "c2s",
  "accusation:vote": "c2s",
  "audio.play_media": "s2c",
  "audio.play_sound": "s2c",
  "audio.play_voice": "s2c",
  "audio.set_bgm": "s2c",
  "audio.stop": "s2c",
  "audio:pause": "c2s",
  "audio:play": "c2s",
  "audio:resume": "c2s",
  "audio:stop": "c2s",
  "auth.challenge": "s2c",
  "auth.identify": "c2s",
  "auth.invalid_session": "s2c",
  "auth.refresh": "c2s",
  "auth.refresh_required": "s2c",
  "auth.resume": "c2s",
  "auth.revoked": "s2c",
  "auth.token_issued": "s2c",
  "chat:message": "s2c",
  "chat:read_receipt": "s2c",
  "chat:send": "c2s",
  "chat:typing_indicator": "s2c",
  "chat:whisper": "s2c",
  "clue.acquired": "s2c",
  "clue.item_declared": "s2c",
  "clue.item_resolved": "s2c",
  "clue.peek_result": "s2c",
  "clue:show_accept": "c2s",
  "clue:show_decline": "c2s",
  "clue:show_request": "c2s",
  "clue:trade_accept": "c2s",
  "clue:trade_decline": "c2s",
  "clue:trade_propose": "c2s",
  "clue:use": "c2s",
  "clue:use_cancel": "c2s",
  "clue:use_target": "c2s",
  "conditional:status": "c2s",
  "connected": "s2c",
  "consensus:propose": "c2s",
  "consensus:vote": "c2s",
  "ending.completed": "s2c",
  "ending.reveal_step": "s2c",
  "ending:next_reveal": "c2s",
  "error": "s2c",
  "event:trigger": "c2s",
  "explore:examine": "c2s",
  "explore:move": "c2s",
  "explore:start": "c2s",
  "floor:change": "c2s",
  "floor:select": "c2s",
  "friend:accepted": "s2c",
  "friend:request": "s2c",
  "game.action": "c2s",
  "game.action_result": "s2c",
  "game.end": "s2c",
  "game.start": "s2c",
  "game.started": "s2c",
  "gm:advance_phase": "c2s",
  "gm:broadcast_message": "c2s",
  "gm:play_media": "c2s",
  "gm:show_ending": "c2s",
  "gm:start_playing": "c2s",
  "gm:start_prologue": "c2s",
  "gm:toggle_voting": "c2s",
  "group:create": "c2s",
  "group:invite": "c2s",
  "group:leave": "c2s",
  "group:send": "c2s",
  "groupchat:join": "c2s",
  "groupchat:leave": "c2s",
  "groupchat:send": "c2s",
  "hybrid:consensus_vote": "c2s",
  "hybrid:trigger_event": "c2s",
  "location:search": "c2s",
  "mission:check": "c2s",
  "mission:report": "c2s",
  "mission:verify": "c2s",
  "module.event": "s2c",
  "module.state": "s2c",
  "phase.advanced": "s2c",
  "phase:entered": "s2c",
  "ping": "bidi",
  "player.joined": "s2c",
  "player.left": "s2c",
  "pong": "bidi",
  "presentation.set_background": "s2c",
  "presentation.set_theme_color": "s2c",
  "reading.completed": "s2c",
  "reading.line_changed": "s2c",
  "reading.paused": "s2c",
  "reading.resumed": "s2c",
  "reading.started": "s2c",
  "reading:advance": "c2s",
  "reading:completed": "s2c",
  "reading:jump": "c2s",
  "reading:line_changed": "s2c",
  "reading:paused": "s2c",
  "reading:resumed": "s2c",
  "reading:started": "s2c",
  "reading:state": "s2c",
  "reading:voice_ended": "c2s",
  "ready.all_ready": "s2c",
  "ready.status_changed": "s2c",
  "ready:toggle": "c2s",
  "reconnect": "s2c",
  "room:deselect_character": "c2s",
  "room:examine": "c2s",
  "room:move": "c2s",
  "room:select_character": "c2s",
  "round_clue:status": "c2s",
  "script:skip": "c2s",
  "session:state": "s2c",
  "skip:agree": "c2s",
  "skip:disagree": "c2s",
  "skip:request": "c2s",
  "sound:play": "bidi",
  "sound:stop": "c2s",
  "spatial:move": "c2s",
  "starting:status": "c2s",
  "timed_clue:start": "c2s",
  "timed_clue:stop": "c2s",
  "timed_clue:tick": "c2s",
  "voice:join": "bidi",
  "voice:leave": "bidi",
  "voice:mute": "bidi",
  "voice:state": "s2c",
  "voice:token": "s2c",
  "voice:unmute": "bidi",
  "vote.cast": "s2c",
  "vote:cast": "c2s",
  "vote:change": "c2s",
  "vote:tallied": "s2c",
  "whisper:send": "c2s",
} as const;

/** Coarse grouping for docs / UI rendering. */
export const WsEventCategory: Readonly<Record<WsEventType, string>> = {
  "accusation:accuse": "accusation",
  "accusation:reset": "accusation",
  "accusation:vote": "accusation",
  "audio.play_media": "audio",
  "audio.play_sound": "audio",
  "audio.play_voice": "audio",
  "audio.set_bgm": "audio",
  "audio.stop": "audio",
  "audio:pause": "audio",
  "audio:play": "audio",
  "audio:resume": "audio",
  "audio:stop": "audio",
  "auth.challenge": "auth",
  "auth.identify": "auth",
  "auth.invalid_session": "auth",
  "auth.refresh": "auth",
  "auth.refresh_required": "auth",
  "auth.resume": "auth",
  "auth.revoked": "auth",
  "auth.token_issued": "auth",
  "chat:message": "chat",
  "chat:read_receipt": "chat",
  "chat:send": "chat",
  "chat:typing_indicator": "chat",
  "chat:whisper": "chat",
  "clue.acquired": "clue",
  "clue.item_declared": "clue",
  "clue.item_resolved": "clue",
  "clue.peek_result": "clue",
  "clue:show_accept": "clue",
  "clue:show_decline": "clue",
  "clue:show_request": "clue",
  "clue:trade_accept": "clue",
  "clue:trade_decline": "clue",
  "clue:trade_propose": "clue",
  "clue:use": "clue",
  "clue:use_cancel": "clue",
  "clue:use_target": "clue",
  "conditional:status": "conditional",
  "connected": "system",
  "consensus:propose": "consensus",
  "consensus:vote": "consensus",
  "ending.completed": "ending",
  "ending.reveal_step": "ending",
  "ending:next_reveal": "ending",
  "error": "system",
  "event:trigger": "event",
  "explore:examine": "explore",
  "explore:move": "explore",
  "explore:start": "explore",
  "floor:change": "floor",
  "floor:select": "floor",
  "friend:accepted": "friend",
  "friend:request": "friend",
  "game.action": "game",
  "game.action_result": "game",
  "game.end": "game",
  "game.start": "game",
  "game.started": "game",
  "gm:advance_phase": "gm",
  "gm:broadcast_message": "gm",
  "gm:play_media": "gm",
  "gm:show_ending": "gm",
  "gm:start_playing": "gm",
  "gm:start_prologue": "gm",
  "gm:toggle_voting": "gm",
  "group:create": "group",
  "group:invite": "group",
  "group:leave": "group",
  "group:send": "group",
  "groupchat:join": "groupchat",
  "groupchat:leave": "groupchat",
  "groupchat:send": "groupchat",
  "hybrid:consensus_vote": "hybrid",
  "hybrid:trigger_event": "hybrid",
  "location:search": "location",
  "mission:check": "mission",
  "mission:report": "mission",
  "mission:verify": "mission",
  "module.event": "module",
  "module.state": "module",
  "phase.advanced": "phase",
  "phase:entered": "phase",
  "ping": "system",
  "player.joined": "player",
  "player.left": "player",
  "pong": "system",
  "presentation.set_background": "presentation",
  "presentation.set_theme_color": "presentation",
  "reading.completed": "reading",
  "reading.line_changed": "reading",
  "reading.paused": "reading",
  "reading.resumed": "reading",
  "reading.started": "reading",
  "reading:advance": "reading",
  "reading:completed": "reading",
  "reading:jump": "reading",
  "reading:line_changed": "reading",
  "reading:paused": "reading",
  "reading:resumed": "reading",
  "reading:started": "reading",
  "reading:state": "reading",
  "reading:voice_ended": "reading",
  "ready.all_ready": "ready",
  "ready.status_changed": "ready",
  "ready:toggle": "ready",
  "reconnect": "system",
  "room:deselect_character": "room",
  "room:examine": "room",
  "room:move": "room",
  "room:select_character": "room",
  "round_clue:status": "round_clue",
  "script:skip": "script",
  "session:state": "session",
  "skip:agree": "skip",
  "skip:disagree": "skip",
  "skip:request": "skip",
  "sound:play": "sound",
  "sound:stop": "sound",
  "spatial:move": "spatial",
  "starting:status": "starting",
  "timed_clue:start": "timed_clue",
  "timed_clue:stop": "timed_clue",
  "timed_clue:tick": "timed_clue",
  "voice:join": "voice",
  "voice:leave": "voice",
  "voice:mute": "voice",
  "voice:state": "voice",
  "voice:token": "voice",
  "voice:unmute": "voice",
  "vote.cast": "vote",
  "vote:cast": "vote",
  "vote:change": "vote",
  "vote:tallied": "vote",
  "whisper:send": "whisper",
} as const;

/** Lifecycle status. "stub" = reserved catalog entry, no server handler yet. */
export const WsEventStatus: Readonly<Record<WsEventType, "active" | "stub" | "deprec">> = {
  "accusation:accuse": "active",
  "accusation:reset": "active",
  "accusation:vote": "active",
  "audio.play_media": "active",
  "audio.play_sound": "active",
  "audio.play_voice": "active",
  "audio.set_bgm": "active",
  "audio.stop": "active",
  "audio:pause": "active",
  "audio:play": "active",
  "audio:resume": "active",
  "audio:stop": "active",
  "auth.challenge": "active",
  "auth.identify": "active",
  "auth.invalid_session": "active",
  "auth.refresh": "active",
  "auth.refresh_required": "active",
  "auth.resume": "active",
  "auth.revoked": "active",
  "auth.token_issued": "active",
  "chat:message": "active",
  "chat:read_receipt": "active",
  "chat:send": "active",
  "chat:typing_indicator": "active",
  "chat:whisper": "active",
  "clue.acquired": "active",
  "clue.item_declared": "active",
  "clue.item_resolved": "active",
  "clue.peek_result": "active",
  "clue:show_accept": "active",
  "clue:show_decline": "active",
  "clue:show_request": "active",
  "clue:trade_accept": "active",
  "clue:trade_decline": "active",
  "clue:trade_propose": "active",
  "clue:use": "active",
  "clue:use_cancel": "active",
  "clue:use_target": "active",
  "conditional:status": "active",
  "connected": "active",
  "consensus:propose": "active",
  "consensus:vote": "active",
  "ending.completed": "active",
  "ending.reveal_step": "active",
  "ending:next_reveal": "active",
  "error": "active",
  "event:trigger": "active",
  "explore:examine": "active",
  "explore:move": "active",
  "explore:start": "active",
  "floor:change": "active",
  "floor:select": "active",
  "friend:accepted": "active",
  "friend:request": "active",
  "game.action": "stub",
  "game.action_result": "stub",
  "game.end": "stub",
  "game.start": "active",
  "game.started": "active",
  "gm:advance_phase": "active",
  "gm:broadcast_message": "active",
  "gm:play_media": "active",
  "gm:show_ending": "active",
  "gm:start_playing": "active",
  "gm:start_prologue": "active",
  "gm:toggle_voting": "active",
  "group:create": "active",
  "group:invite": "active",
  "group:leave": "active",
  "group:send": "active",
  "groupchat:join": "active",
  "groupchat:leave": "active",
  "groupchat:send": "active",
  "hybrid:consensus_vote": "active",
  "hybrid:trigger_event": "active",
  "location:search": "active",
  "mission:check": "active",
  "mission:report": "active",
  "mission:verify": "active",
  "module.event": "active",
  "module.state": "active",
  "phase.advanced": "active",
  "phase:entered": "deprec",
  "ping": "active",
  "player.joined": "active",
  "player.left": "active",
  "pong": "active",
  "presentation.set_background": "active",
  "presentation.set_theme_color": "active",
  "reading.completed": "active",
  "reading.line_changed": "active",
  "reading.paused": "active",
  "reading.resumed": "active",
  "reading.started": "active",
  "reading:advance": "active",
  "reading:completed": "active",
  "reading:jump": "active",
  "reading:line_changed": "active",
  "reading:paused": "active",
  "reading:resumed": "active",
  "reading:started": "active",
  "reading:state": "active",
  "reading:voice_ended": "active",
  "ready.all_ready": "active",
  "ready.status_changed": "active",
  "ready:toggle": "active",
  "reconnect": "active",
  "room:deselect_character": "active",
  "room:examine": "active",
  "room:move": "active",
  "room:select_character": "active",
  "round_clue:status": "active",
  "script:skip": "active",
  "session:state": "active",
  "skip:agree": "active",
  "skip:disagree": "active",
  "skip:request": "active",
  "sound:play": "active",
  "sound:stop": "active",
  "spatial:move": "active",
  "starting:status": "active",
  "timed_clue:start": "active",
  "timed_clue:stop": "active",
  "timed_clue:tick": "active",
  "voice:join": "active",
  "voice:leave": "active",
  "voice:mute": "active",
  "voice:state": "active",
  "voice:token": "active",
  "voice:unmute": "active",
  "vote.cast": "active",
  "vote:cast": "active",
  "vote:change": "active",
  "vote:tallied": "deprec",
  "whisper:send": "active",
} as const;

// --- payload interfaces (generated from Go structs marked //wsgen:payload) ---

/**
 * AuthChallengePayload — S2C, server demands re-authentication before a
 * sensitive action proceeds.
 */
export interface AuthChallengePayload {
  reason: string;
  action?: string;
}

/**
 * AuthIdentifyPayload — C2S, sent post-upgrade with a refreshed credential.
 */
export interface AuthIdentifyPayload {
  token: string;
  sessionId?: string;
  clientLastSeq?: number;
}

/**
 * AuthInvalidSessionPayload — S2C, the resume target the client sent
 * (session_id + last_seq) cannot be honoured. The Resumable flag tells
 * the client whether reconnecting with a full auth.identify is allowed
 * (true; e.g. buffer expired but the user is still valid) or whether
 * the session is fully unauthorized (false; e.g. user was banned —
 * auth.revoked semantics overlap, but invalid_session signals
 * "your *resume target* is gone" rather than "your *user* is gone").
 * Discord INVALID_SESSION pattern.
 */
export interface AuthInvalidSessionPayload {
  resumable: boolean;
  reason: string;
}

/**
 * AuthRefreshPayload — C2S, request a rotated short-lived token.
 */
export interface AuthRefreshPayload {
  token: string;
}

/**
 * AuthRefreshRequiredPayload — S2C, the token is approaching expiry.
 * The client should reply with auth.refresh before ExpiresAt.
 */
export interface AuthRefreshRequiredPayload {
  expiresAt: number;
  reason?: string;
}

/**
 * AuthResumePayload — C2S, sent on reconnect to replay missed events.
 */
export interface AuthResumePayload {
  token: string;
  sessionId: string;
  lastSeq: number;
}

/**
 * AuthRevokedPayload — S2C, the session has been invalidated and the
 * connection is closing. Code is one of: "banned",
 * "logged_out_elsewhere", "password_changed", "admin_revoked".
 */
export interface AuthRevokedPayload {
  reason: string;
  code: string;
}

/**
 * AuthTokenIssuedPayload — S2C, server's response to a successful
 * auth.refresh. Carries the rotated short-lived access token plus its
 * expiry so the client can schedule the next refresh deterministically.
 * Sent as a dedicated frame (not piggybacked on another event) per
 * videosdk 2025 / websockets.readthedocs guidance.
 */
export interface AuthTokenIssuedPayload {
  token: string;
  expiresAt: number;
}

/**
 * ConnectedPayload is sent on successful connection/reconnection.
 */
export interface ConnectedPayload {
  playerId: string;
  sessionId?: string;
  seq: number;
}

/**
 * ErrorPayload is sent as the payload of "error" type messages.
 */
export interface ErrorPayload {
  code: number;
  message: string;
}

