// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	db "github.com/mmp-platform/server/internal/db"
	theme "github.com/mmp-platform/server/internal/domain/theme"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetCharacters mocks base method.
func (m *MockService) GetCharacters(ctx context.Context, themeID uuid.UUID) ([]theme.CharacterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacters", ctx, themeID)
	ret0, _ := ret[0].([]theme.CharacterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacters indicates an expected call of GetCharacters.
func (mr *MockServiceMockRecorder) GetCharacters(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacters", reflect.TypeOf((*MockService)(nil).GetCharacters), ctx, themeID)
}

// GetTheme mocks base method.
func (m *MockService) GetTheme(ctx context.Context, themeID uuid.UUID) (*theme.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", ctx, themeID)
	ret0, _ := ret[0].(*theme.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockServiceMockRecorder) GetTheme(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockService)(nil).GetTheme), ctx, themeID)
}

// GetThemeBySlug mocks base method.
func (m *MockService) GetThemeBySlug(ctx context.Context, slug string) (*theme.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeBySlug", ctx, slug)
	ret0, _ := ret[0].(*theme.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeBySlug indicates an expected call of GetThemeBySlug.
func (mr *MockServiceMockRecorder) GetThemeBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeBySlug", reflect.TypeOf((*MockService)(nil).GetThemeBySlug), ctx, slug)
}

// ListPublished mocks base method.
func (m *MockService) ListPublished(ctx context.Context, limit, offset int32) ([]theme.ThemeSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublished", ctx, limit, offset)
	ret0, _ := ret[0].([]theme.ThemeSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublished indicates an expected call of ListPublished.
func (mr *MockServiceMockRecorder) ListPublished(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublished", reflect.TypeOf((*MockService)(nil).ListPublished), ctx, limit, offset)
}

// MockthemeQueries is a mock of themeQueries interface.
type MockthemeQueries struct {
	ctrl     *gomock.Controller
	recorder *MockthemeQueriesMockRecorder
	isgomock struct{}
}

// MockthemeQueriesMockRecorder is the mock recorder for MockthemeQueries.
type MockthemeQueriesMockRecorder struct {
	mock *MockthemeQueries
}

// NewMockthemeQueries creates a new mock instance.
func NewMockthemeQueries(ctrl *gomock.Controller) *MockthemeQueries {
	mock := &MockthemeQueries{ctrl: ctrl}
	mock.recorder = &MockthemeQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockthemeQueries) EXPECT() *MockthemeQueriesMockRecorder {
	return m.recorder
}

// GetMedia mocks base method.
func (m *MockthemeQueries) GetMedia(ctx context.Context, id uuid.UUID) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedia", ctx, id)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedia indicates an expected call of GetMedia.
func (mr *MockthemeQueriesMockRecorder) GetMedia(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedia", reflect.TypeOf((*MockthemeQueries)(nil).GetMedia), ctx, id)
}

// GetTheme mocks base method.
func (m *MockthemeQueries) GetTheme(ctx context.Context, id uuid.UUID) (db.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", ctx, id)
	ret0, _ := ret[0].(db.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockthemeQueriesMockRecorder) GetTheme(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockthemeQueries)(nil).GetTheme), ctx, id)
}

// GetThemeBySlug mocks base method.
func (m *MockthemeQueries) GetThemeBySlug(ctx context.Context, slug string) (db.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeBySlug", ctx, slug)
	ret0, _ := ret[0].(db.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeBySlug indicates an expected call of GetThemeBySlug.
func (mr *MockthemeQueriesMockRecorder) GetThemeBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeBySlug", reflect.TypeOf((*MockthemeQueries)(nil).GetThemeBySlug), ctx, slug)
}

// GetThemeCharacters mocks base method.
func (m *MockthemeQueries) GetThemeCharacters(ctx context.Context, themeID uuid.UUID) ([]db.ThemeCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeCharacters", ctx, themeID)
	ret0, _ := ret[0].([]db.ThemeCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeCharacters indicates an expected call of GetThemeCharacters.
func (mr *MockthemeQueriesMockRecorder) GetThemeCharacters(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeCharacters", reflect.TypeOf((*MockthemeQueries)(nil).GetThemeCharacters), ctx, themeID)
}

// ListPublishedThemes mocks base method.
func (m *MockthemeQueries) ListPublishedThemes(ctx context.Context, arg db.ListPublishedThemesParams) ([]db.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublishedThemes", ctx, arg)
	ret0, _ := ret[0].([]db.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublishedThemes indicates an expected call of ListPublishedThemes.
func (mr *MockthemeQueriesMockRecorder) ListPublishedThemes(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublishedThemes", reflect.TypeOf((*MockthemeQueries)(nil).ListPublishedThemes), ctx, arg)
}
