// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	theme "github.com/mmp-platform/server/internal/domain/theme"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetCharacters mocks base method.
func (m *MockService) GetCharacters(ctx context.Context, themeID uuid.UUID) ([]theme.CharacterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacters", ctx, themeID)
	ret0, _ := ret[0].([]theme.CharacterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacters indicates an expected call of GetCharacters.
func (mr *MockServiceMockRecorder) GetCharacters(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacters", reflect.TypeOf((*MockService)(nil).GetCharacters), ctx, themeID)
}

// GetTheme mocks base method.
func (m *MockService) GetTheme(ctx context.Context, themeID uuid.UUID) (*theme.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", ctx, themeID)
	ret0, _ := ret[0].(*theme.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockServiceMockRecorder) GetTheme(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockService)(nil).GetTheme), ctx, themeID)
}

// GetThemeBySlug mocks base method.
func (m *MockService) GetThemeBySlug(ctx context.Context, slug string) (*theme.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeBySlug", ctx, slug)
	ret0, _ := ret[0].(*theme.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeBySlug indicates an expected call of GetThemeBySlug.
func (mr *MockServiceMockRecorder) GetThemeBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeBySlug", reflect.TypeOf((*MockService)(nil).GetThemeBySlug), ctx, slug)
}

// ListPublished mocks base method.
func (m *MockService) ListPublished(ctx context.Context, limit, offset int32) ([]theme.ThemeSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublished", ctx, limit, offset)
	ret0, _ := ret[0].([]theme.ThemeSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublished indicates an expected call of ListPublished.
func (mr *MockServiceMockRecorder) ListPublished(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublished", reflect.TypeOf((*MockService)(nil).ListPublished), ctx, limit, offset)
}
