// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mmp-platform/server/internal/engine (interfaces: SceneController,PhaseActionDispatcher)
//
// Generated by this command:
//
//	mockgen -destination=internal/module/progression/mocks/mock_engine_deps.go -package=mocks github.com/mmp-platform/server/internal/engine SceneController,PhaseActionDispatcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	engine "github.com/mmp-platform/server/internal/engine"
	gomock "go.uber.org/mock/gomock"
)

// MockSceneController is a mock of SceneController interface.
type MockSceneController struct {
	ctrl     *gomock.Controller
	recorder *MockSceneControllerMockRecorder
	isgomock struct{}
}

// MockSceneControllerMockRecorder is the mock recorder for MockSceneController.
type MockSceneControllerMockRecorder struct {
	mock *MockSceneController
}

// NewMockSceneController creates a new mock instance.
func NewMockSceneController(ctrl *gomock.Controller) *MockSceneController {
	mock := &MockSceneController{ctrl: ctrl}
	mock.recorder = &MockSceneControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSceneController) EXPECT() *MockSceneControllerMockRecorder {
	return m.recorder
}

// SkipToPhase mocks base method.
func (m *MockSceneController) SkipToPhase(ctx context.Context, phaseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkipToPhase", ctx, phaseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SkipToPhase indicates an expected call of SkipToPhase.
func (mr *MockSceneControllerMockRecorder) SkipToPhase(ctx, phaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkipToPhase", reflect.TypeOf((*MockSceneController)(nil).SkipToPhase), ctx, phaseID)
}

// MockPhaseActionDispatcher is a mock of PhaseActionDispatcher interface.
type MockPhaseActionDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockPhaseActionDispatcherMockRecorder
	isgomock struct{}
}

// MockPhaseActionDispatcherMockRecorder is the mock recorder for MockPhaseActionDispatcher.
type MockPhaseActionDispatcherMockRecorder struct {
	mock *MockPhaseActionDispatcher
}

// NewMockPhaseActionDispatcher creates a new mock instance.
func NewMockPhaseActionDispatcher(ctrl *gomock.Controller) *MockPhaseActionDispatcher {
	mock := &MockPhaseActionDispatcher{ctrl: ctrl}
	mock.recorder = &MockPhaseActionDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhaseActionDispatcher) EXPECT() *MockPhaseActionDispatcherMockRecorder {
	return m.recorder
}

// DispatchAction mocks base method.
func (m *MockPhaseActionDispatcher) DispatchAction(ctx context.Context, action engine.PhaseActionPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchAction", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchAction indicates an expected call of DispatchAction.
func (mr *MockPhaseActionDispatcherMockRecorder) DispatchAction(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchAction", reflect.TypeOf((*MockPhaseActionDispatcher)(nil).DispatchAction), ctx, action)
}
