# Development Dockerfile with air hot-reload
FROM golang:1.25-alpine
RUN go install github.com/air-verse/air@latest
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080 9090
CMD ["air", "-c", ".air.toml"]
