// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (session_id, seq, actor_id, action, module_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, seq, actor_id, action, module_id, payload, created_at
`

type AppendAuditEventParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	Seq       int64           `json:"seq"`
	ActorID   pgtype.UUID     `json:"actor_id"`
	Action    string          `json:"action"`
	ModuleID  pgtype.Text     `json:"module_id"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.SessionID,
		arg.Seq,
		arg.ActorID,
		arg.Action,
		arg.ModuleID,
		arg.Payload,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.ActorID,
		&i.Action,
		&i.ModuleID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const latestSeq = `-- name: LatestSeq :one
SELECT COALESCE(MAX(seq), 0)::bigint AS seq
FROM audit_events
WHERE session_id = $1
`

func (q *Queries) LatestSeq(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, latestSeq, sessionID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const listBySession = `-- name: ListBySession :many
SELECT id, session_id, seq, actor_id, action, module_id, payload, created_at FROM audit_events
WHERE session_id = $1
ORDER BY seq
`

func (q *Queries) ListBySession(ctx context.Context, sessionID uuid.UUID) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.ActorID,
			&i.Action,
			&i.ModuleID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
