// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clue_relation.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bulkInsertClueRelations = `-- name: BulkInsertClueRelations :many
INSERT INTO clue_relations (theme_id, source_id, target_id, mode)
SELECT $1::uuid, unnest($2::uuid[]), unnest($3::uuid[]), unnest($4::text[])
RETURNING id, theme_id, source_id, target_id, mode, created_at
`

type BulkInsertClueRelationsParams struct {
	Column1 uuid.UUID   `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
	Column3 []uuid.UUID `json:"column_3"`
	Column4 []string    `json:"column_4"`
}

func (q *Queries) BulkInsertClueRelations(ctx context.Context, arg BulkInsertClueRelationsParams) ([]ClueRelation, error) {
	rows, err := q.db.Query(ctx, bulkInsertClueRelations,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClueRelation{}
	for rows.Next() {
		var i ClueRelation
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.SourceID,
			&i.TargetID,
			&i.Mode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteClueRelationsByTheme = `-- name: DeleteClueRelationsByTheme :exec
DELETE FROM clue_relations WHERE theme_id = $1
`

func (q *Queries) DeleteClueRelationsByTheme(ctx context.Context, themeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClueRelationsByTheme, themeID)
	return err
}

const insertClueRelation = `-- name: InsertClueRelation :one
INSERT INTO clue_relations (theme_id, source_id, target_id, mode)
VALUES ($1, $2, $3, $4)
RETURNING id, theme_id, source_id, target_id, mode, created_at
`

type InsertClueRelationParams struct {
	ThemeID  uuid.UUID `json:"theme_id"`
	SourceID uuid.UUID `json:"source_id"`
	TargetID uuid.UUID `json:"target_id"`
	Mode     string    `json:"mode"`
}

func (q *Queries) InsertClueRelation(ctx context.Context, arg InsertClueRelationParams) (ClueRelation, error) {
	row := q.db.QueryRow(ctx, insertClueRelation,
		arg.ThemeID,
		arg.SourceID,
		arg.TargetID,
		arg.Mode,
	)
	var i ClueRelation
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.SourceID,
		&i.TargetID,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const listClueRelationsByTheme = `-- name: ListClueRelationsByTheme :many
SELECT id, theme_id, source_id, target_id, mode, created_at FROM clue_relations WHERE theme_id = $1 ORDER BY created_at
`

func (q *Queries) ListClueRelationsByTheme(ctx context.Context, themeID uuid.UUID) ([]ClueRelation, error) {
	rows, err := q.db.Query(ctx, listClueRelationsByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClueRelation{}
	for rows.Next() {
		var i ClueRelation
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.SourceID,
			&i.TargetID,
			&i.Mode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
