// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clue_edges.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bulkInsertClueEdgeMembers = `-- name: BulkInsertClueEdgeMembers :many
INSERT INTO clue_edge_members (group_id, source_id)
SELECT unnest($1::uuid[]), unnest($2::uuid[])
RETURNING group_id, source_id, created_at
`

type BulkInsertClueEdgeMembersParams struct {
	GroupIds  []uuid.UUID `json:"group_ids"`
	SourceIds []uuid.UUID `json:"source_ids"`
}

func (q *Queries) BulkInsertClueEdgeMembers(ctx context.Context, arg BulkInsertClueEdgeMembersParams) ([]ClueEdgeMember, error) {
	rows, err := q.db.Query(ctx, bulkInsertClueEdgeMembers, arg.GroupIds, arg.SourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClueEdgeMember{}
	for rows.Next() {
		var i ClueEdgeMember
		if err := rows.Scan(&i.GroupID, &i.SourceID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteClueEdgeGroupsByTheme = `-- name: DeleteClueEdgeGroupsByTheme :exec
DELETE FROM clue_edge_groups WHERE theme_id = $1
`

func (q *Queries) DeleteClueEdgeGroupsByTheme(ctx context.Context, themeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClueEdgeGroupsByTheme, themeID)
	return err
}

const insertClueEdgeGroup = `-- name: InsertClueEdgeGroup :one
INSERT INTO clue_edge_groups (theme_id, target_id, trigger, mode)
VALUES ($1, $2, $3, $4)
RETURNING id, theme_id, target_id, trigger, mode, created_at
`

type InsertClueEdgeGroupParams struct {
	ThemeID  uuid.UUID `json:"theme_id"`
	TargetID uuid.UUID `json:"target_id"`
	Trigger  string    `json:"trigger"`
	Mode     string    `json:"mode"`
}

func (q *Queries) InsertClueEdgeGroup(ctx context.Context, arg InsertClueEdgeGroupParams) (ClueEdgeGroup, error) {
	row := q.db.QueryRow(ctx, insertClueEdgeGroup,
		arg.ThemeID,
		arg.TargetID,
		arg.Trigger,
		arg.Mode,
	)
	var i ClueEdgeGroup
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.TargetID,
		&i.Trigger,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const listClueEdgeGroupsByTheme = `-- name: ListClueEdgeGroupsByTheme :many

SELECT id, theme_id, target_id, trigger, mode, created_at FROM clue_edge_groups WHERE theme_id = $1 ORDER BY created_at
`

// Phase 20 PR-4: unified clue edge schema queries.
// `clue_edge_groups` rows model a "one target + one group of sources +
// trigger + mode" tuple. `clue_edge_members` fans out the sources.
func (q *Queries) ListClueEdgeGroupsByTheme(ctx context.Context, themeID uuid.UUID) ([]ClueEdgeGroup, error) {
	rows, err := q.db.Query(ctx, listClueEdgeGroupsByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClueEdgeGroup{}
	for rows.Next() {
		var i ClueEdgeGroup
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.TargetID,
			&i.Trigger,
			&i.Mode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClueEdgeMembersByTheme = `-- name: ListClueEdgeMembersByTheme :many
SELECT m.group_id, m.source_id, m.created_at FROM clue_edge_members m
JOIN clue_edge_groups g ON m.group_id = g.id
WHERE g.theme_id = $1
ORDER BY m.created_at
`

func (q *Queries) ListClueEdgeMembersByTheme(ctx context.Context, themeID uuid.UUID) ([]ClueEdgeMember, error) {
	rows, err := q.db.Query(ctx, listClueEdgeMembersByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClueEdgeMember{}
	for rows.Next() {
		var i ClueEdgeMember
		if err := rows.Scan(&i.GroupID, &i.SourceID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
