// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCoinBalance = `-- name: AddCoinBalance :exec
UPDATE users
SET coin_balance_base = coin_balance_base + $2, coin_balance_bonus = coin_balance_bonus + $3
WHERE id = $1
`

type AddCoinBalanceParams struct {
	ID               uuid.UUID `json:"id"`
	CoinBalanceBase  int64     `json:"coin_balance_base"`
	CoinBalanceBonus int64     `json:"coin_balance_bonus"`
}

func (q *Queries) AddCoinBalance(ctx context.Context, arg AddCoinBalanceParams) error {
	_, err := q.db.Exec(ctx, addCoinBalance, arg.ID, arg.CoinBalanceBase, arg.CoinBalanceBonus)
	return err
}

const countCoinTransactions = `-- name: CountCoinTransactions :one
SELECT COUNT(*) FROM coin_transactions WHERE user_id = $1
`

func (q *Queries) CountCoinTransactions(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCoinTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCoinTransactionsByType = `-- name: CountCoinTransactionsByType :one
SELECT COUNT(*) FROM coin_transactions WHERE user_id = $1 AND type = $2
`

type CountCoinTransactionsByTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
}

func (q *Queries) CountCoinTransactionsByType(ctx context.Context, arg CountCoinTransactionsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCoinTransactionsByType, arg.UserID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchasedThemes = `-- name: CountPurchasedThemes :one
SELECT COUNT(*) FROM theme_purchases
WHERE user_id = $1 AND status = 'COMPLETED'
`

func (q *Queries) CountPurchasedThemes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchasedThemes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRefunds = `-- name: CountRecentRefunds :one
SELECT COUNT(*) FROM theme_purchases
WHERE user_id = $1 AND status = 'REFUNDED' AND refunded_at > NOW() - INTERVAL '30 days'
`

func (q *Queries) CountRecentRefunds(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRefunds, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoinTransaction = `-- name: CreateCoinTransaction :one

INSERT INTO coin_transactions (user_id, type, base_amount, bonus_amount, balance_after_base, balance_after_bonus, reference_type, reference_id, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, type, base_amount, bonus_amount, balance_after_base, balance_after_bonus, reference_type, reference_id, description, created_at
`

type CreateCoinTransactionParams struct {
	UserID            uuid.UUID   `json:"user_id"`
	Type              string      `json:"type"`
	BaseAmount        int32       `json:"base_amount"`
	BonusAmount       int32       `json:"bonus_amount"`
	BalanceAfterBase  int64       `json:"balance_after_base"`
	BalanceAfterBonus int64       `json:"balance_after_bonus"`
	ReferenceType     pgtype.Text `json:"reference_type"`
	ReferenceID       pgtype.Text `json:"reference_id"`
	Description       pgtype.Text `json:"description"`
}

// ═══════════════════════════════════════════════════════════════════
// Coin Transactions
// ═══════════════════════════════════════════════════════════════════
func (q *Queries) CreateCoinTransaction(ctx context.Context, arg CreateCoinTransactionParams) (CoinTransaction, error) {
	row := q.db.QueryRow(ctx, createCoinTransaction,
		arg.UserID,
		arg.Type,
		arg.BaseAmount,
		arg.BonusAmount,
		arg.BalanceAfterBase,
		arg.BalanceAfterBonus,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Description,
	)
	var i CoinTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.BaseAmount,
		&i.BonusAmount,
		&i.BalanceAfterBase,
		&i.BalanceAfterBonus,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createThemePurchase = `-- name: CreateThemePurchase :one

INSERT INTO theme_purchases (user_id, theme_id, coin_price, base_coins_used, bonus_coins_used, refundable_until)
VALUES ($1, $2, $3, $4, $5, NOW() + INTERVAL '7 days')
RETURNING id, user_id, theme_id, coin_price, base_coins_used, bonus_coins_used, status, has_played, refundable_until, refunded_at, created_at
`

type CreateThemePurchaseParams struct {
	UserID         uuid.UUID `json:"user_id"`
	ThemeID        uuid.UUID `json:"theme_id"`
	CoinPrice      int32     `json:"coin_price"`
	BaseCoinsUsed  int32     `json:"base_coins_used"`
	BonusCoinsUsed int32     `json:"bonus_coins_used"`
}

// ═══════════════════════════════════════════════════════════════════
// Theme Purchases
// ═══════════════════════════════════════════════════════════════════
func (q *Queries) CreateThemePurchase(ctx context.Context, arg CreateThemePurchaseParams) (ThemePurchase, error) {
	row := q.db.QueryRow(ctx, createThemePurchase,
		arg.UserID,
		arg.ThemeID,
		arg.CoinPrice,
		arg.BaseCoinsUsed,
		arg.BonusCoinsUsed,
	)
	var i ThemePurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ThemeID,
		&i.CoinPrice,
		&i.BaseCoinsUsed,
		&i.BonusCoinsUsed,
		&i.Status,
		&i.HasPlayed,
		&i.RefundableUntil,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCoinBalance = `-- name: GetCoinBalance :one
SELECT coin_balance_base, coin_balance_bonus FROM users WHERE id = $1
`

type GetCoinBalanceRow struct {
	CoinBalanceBase  int64 `json:"coin_balance_base"`
	CoinBalanceBonus int64 `json:"coin_balance_bonus"`
}

func (q *Queries) GetCoinBalance(ctx context.Context, id uuid.UUID) (GetCoinBalanceRow, error) {
	row := q.db.QueryRow(ctx, getCoinBalance, id)
	var i GetCoinBalanceRow
	err := row.Scan(&i.CoinBalanceBase, &i.CoinBalanceBonus)
	return i, err
}

const getThemePurchase = `-- name: GetThemePurchase :one
SELECT id, user_id, theme_id, coin_price, base_coins_used, bonus_coins_used, status, has_played, refundable_until, refunded_at, created_at FROM theme_purchases WHERE id = $1
`

func (q *Queries) GetThemePurchase(ctx context.Context, id uuid.UUID) (ThemePurchase, error) {
	row := q.db.QueryRow(ctx, getThemePurchase, id)
	var i ThemePurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ThemeID,
		&i.CoinPrice,
		&i.BaseCoinsUsed,
		&i.BonusCoinsUsed,
		&i.Status,
		&i.HasPlayed,
		&i.RefundableUntil,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getThemePurchaseByUserTheme = `-- name: GetThemePurchaseByUserTheme :one
SELECT id, user_id, theme_id, coin_price, base_coins_used, bonus_coins_used, status, has_played, refundable_until, refunded_at, created_at FROM theme_purchases WHERE user_id = $1 AND theme_id = $2
`

type GetThemePurchaseByUserThemeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ThemeID uuid.UUID `json:"theme_id"`
}

func (q *Queries) GetThemePurchaseByUserTheme(ctx context.Context, arg GetThemePurchaseByUserThemeParams) (ThemePurchase, error) {
	row := q.db.QueryRow(ctx, getThemePurchaseByUserTheme, arg.UserID, arg.ThemeID)
	var i ThemePurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ThemeID,
		&i.CoinPrice,
		&i.BaseCoinsUsed,
		&i.BonusCoinsUsed,
		&i.Status,
		&i.HasPlayed,
		&i.RefundableUntil,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getThemePurchaseForRefund = `-- name: GetThemePurchaseForRefund :one
SELECT id, user_id, theme_id, coin_price, base_coins_used, bonus_coins_used, status, has_played, refundable_until, refunded_at, created_at FROM theme_purchases WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type GetThemePurchaseForRefundParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetThemePurchaseForRefund(ctx context.Context, arg GetThemePurchaseForRefundParams) (ThemePurchase, error) {
	row := q.db.QueryRow(ctx, getThemePurchaseForRefund, arg.ID, arg.UserID)
	var i ThemePurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ThemeID,
		&i.CoinPrice,
		&i.BaseCoinsUsed,
		&i.BonusCoinsUsed,
		&i.Status,
		&i.HasPlayed,
		&i.RefundableUntil,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForCoinUpdate = `-- name: GetUserForCoinUpdate :one

SELECT id, coin_balance_base, coin_balance_bonus FROM users WHERE id = $1 FOR UPDATE
`

type GetUserForCoinUpdateRow struct {
	ID               uuid.UUID `json:"id"`
	CoinBalanceBase  int64     `json:"coin_balance_base"`
	CoinBalanceBonus int64     `json:"coin_balance_bonus"`
}

// ═══════════════════════════════════════════════════════════════════
// Coin Balance
// ═══════════════════════════════════════════════════════════════════
func (q *Queries) GetUserForCoinUpdate(ctx context.Context, id uuid.UUID) (GetUserForCoinUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserForCoinUpdate, id)
	var i GetUserForCoinUpdateRow
	err := row.Scan(&i.ID, &i.CoinBalanceBase, &i.CoinBalanceBonus)
	return i, err
}

const listCoinTransactions = `-- name: ListCoinTransactions :many
SELECT id, user_id, type, base_amount, bonus_amount, balance_after_base, balance_after_bonus, reference_type, reference_id, description, created_at FROM coin_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCoinTransactionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListCoinTransactions(ctx context.Context, arg ListCoinTransactionsParams) ([]CoinTransaction, error) {
	rows, err := q.db.Query(ctx, listCoinTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoinTransaction{}
	for rows.Next() {
		var i CoinTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.BaseAmount,
			&i.BonusAmount,
			&i.BalanceAfterBase,
			&i.BalanceAfterBonus,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoinTransactionsByType = `-- name: ListCoinTransactionsByType :many
SELECT id, user_id, type, base_amount, bonus_amount, balance_after_base, balance_after_bonus, reference_type, reference_id, description, created_at FROM coin_transactions
WHERE user_id = $1 AND type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListCoinTransactionsByTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListCoinTransactionsByType(ctx context.Context, arg ListCoinTransactionsByTypeParams) ([]CoinTransaction, error) {
	rows, err := q.db.Query(ctx, listCoinTransactionsByType,
		arg.UserID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoinTransaction{}
	for rows.Next() {
		var i CoinTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.BaseAmount,
			&i.BonusAmount,
			&i.BalanceAfterBase,
			&i.BalanceAfterBonus,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasedThemes = `-- name: ListPurchasedThemes :many
SELECT tp.id, tp.user_id, tp.theme_id, tp.coin_price, tp.base_coins_used, tp.bonus_coins_used, tp.status, tp.has_played, tp.refundable_until, tp.refunded_at, tp.created_at, t.title AS theme_title, t.slug AS theme_slug, t.cover_image AS theme_cover_image
FROM theme_purchases tp
JOIN themes t ON tp.theme_id = t.id
WHERE tp.user_id = $1 AND tp.status = 'COMPLETED'
ORDER BY tp.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPurchasedThemesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListPurchasedThemesRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	ThemeID         uuid.UUID          `json:"theme_id"`
	CoinPrice       int32              `json:"coin_price"`
	BaseCoinsUsed   int32              `json:"base_coins_used"`
	BonusCoinsUsed  int32              `json:"bonus_coins_used"`
	Status          string             `json:"status"`
	HasPlayed       bool               `json:"has_played"`
	RefundableUntil pgtype.Timestamptz `json:"refundable_until"`
	RefundedAt      pgtype.Timestamptz `json:"refunded_at"`
	CreatedAt       time.Time          `json:"created_at"`
	ThemeTitle      string             `json:"theme_title"`
	ThemeSlug       string             `json:"theme_slug"`
	ThemeCoverImage pgtype.Text        `json:"theme_cover_image"`
}

func (q *Queries) ListPurchasedThemes(ctx context.Context, arg ListPurchasedThemesParams) ([]ListPurchasedThemesRow, error) {
	rows, err := q.db.Query(ctx, listPurchasedThemes, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchasedThemesRow{}
	for rows.Next() {
		var i ListPurchasedThemesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ThemeID,
			&i.CoinPrice,
			&i.BaseCoinsUsed,
			&i.BonusCoinsUsed,
			&i.Status,
			&i.HasPlayed,
			&i.RefundableUntil,
			&i.RefundedAt,
			&i.CreatedAt,
			&i.ThemeTitle,
			&i.ThemeSlug,
			&i.ThemeCoverImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThemePlayed = `-- name: MarkThemePlayed :exec
UPDATE theme_purchases SET has_played = true
WHERE user_id = $1 AND theme_id = $2 AND status = 'COMPLETED'
`

type MarkThemePlayedParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ThemeID uuid.UUID `json:"theme_id"`
}

func (q *Queries) MarkThemePlayed(ctx context.Context, arg MarkThemePlayedParams) error {
	_, err := q.db.Exec(ctx, markThemePlayed, arg.UserID, arg.ThemeID)
	return err
}

const refundThemePurchase = `-- name: RefundThemePurchase :one
UPDATE theme_purchases
SET status = 'REFUNDED', refunded_at = NOW()
WHERE id = $1 AND status = 'COMPLETED'
RETURNING id, user_id, theme_id, coin_price, base_coins_used, bonus_coins_used, status, has_played, refundable_until, refunded_at, created_at
`

func (q *Queries) RefundThemePurchase(ctx context.Context, id uuid.UUID) (ThemePurchase, error) {
	row := q.db.QueryRow(ctx, refundThemePurchase, id)
	var i ThemePurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ThemeID,
		&i.CoinPrice,
		&i.BaseCoinsUsed,
		&i.BonusCoinsUsed,
		&i.Status,
		&i.HasPlayed,
		&i.RefundableUntil,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}
