// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editor.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCluesByTheme = `-- name: CountCluesByTheme :one
SELECT count(*) FROM theme_clues WHERE theme_id = $1
`

func (q *Queries) CountCluesByTheme(ctx context.Context, themeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCluesByTheme, themeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLocationsByMap = `-- name: CountLocationsByMap :one
SELECT count(*) FROM theme_locations WHERE map_id = $1
`

func (q *Queries) CountLocationsByMap(ctx context.Context, mapID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLocationsByMap, mapID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMapsByTheme = `-- name: CountMapsByTheme :one
SELECT count(*) FROM theme_maps WHERE theme_id = $1
`

func (q *Queries) CountMapsByTheme(ctx context.Context, themeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMapsByTheme, themeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClue = `-- name: CreateClue :one
INSERT INTO theme_clues (theme_id, location_id, name, description, image_url, is_common, level, sort_order, is_usable, use_effect, use_target, use_consumed, reveal_round, hide_round)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, theme_id, location_id, name, description, image_url, is_common, level, sort_order, created_at, is_usable, use_effect, use_target, use_consumed, reveal_round, hide_round
`

type CreateClueParams struct {
	ThemeID     uuid.UUID   `json:"theme_id"`
	LocationID  pgtype.UUID `json:"location_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrl    pgtype.Text `json:"image_url"`
	IsCommon    bool        `json:"is_common"`
	Level       int32       `json:"level"`
	SortOrder   int32       `json:"sort_order"`
	IsUsable    bool        `json:"is_usable"`
	UseEffect   pgtype.Text `json:"use_effect"`
	UseTarget   pgtype.Text `json:"use_target"`
	UseConsumed bool        `json:"use_consumed"`
	RevealRound pgtype.Int4 `json:"reveal_round"`
	HideRound   pgtype.Int4 `json:"hide_round"`
}

func (q *Queries) CreateClue(ctx context.Context, arg CreateClueParams) (ThemeClue, error) {
	row := q.db.QueryRow(ctx, createClue,
		arg.ThemeID,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.IsCommon,
		arg.Level,
		arg.SortOrder,
		arg.IsUsable,
		arg.UseEffect,
		arg.UseTarget,
		arg.UseConsumed,
		arg.RevealRound,
		arg.HideRound,
	)
	var i ThemeClue
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsCommon,
		&i.Level,
		&i.SortOrder,
		&i.CreatedAt,
		&i.IsUsable,
		&i.UseEffect,
		&i.UseTarget,
		&i.UseConsumed,
		&i.RevealRound,
		&i.HideRound,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO theme_locations (theme_id, map_id, name, restricted_characters, sort_order, from_round, until_round, image_url, image_media_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, theme_id, map_id, name, restricted_characters, sort_order, created_at, from_round, until_round, image_url, image_media_id
`

type CreateLocationParams struct {
	ThemeID              uuid.UUID   `json:"theme_id"`
	MapID                uuid.UUID   `json:"map_id"`
	Name                 string      `json:"name"`
	RestrictedCharacters pgtype.Text `json:"restricted_characters"`
	SortOrder            int32       `json:"sort_order"`
	FromRound            pgtype.Int4 `json:"from_round"`
	UntilRound           pgtype.Int4 `json:"until_round"`
	ImageUrl             pgtype.Text `json:"image_url"`
	ImageMediaID         pgtype.UUID `json:"image_media_id"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (ThemeLocation, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.ThemeID,
		arg.MapID,
		arg.Name,
		arg.RestrictedCharacters,
		arg.SortOrder,
		arg.FromRound,
		arg.UntilRound,
		arg.ImageUrl,
		arg.ImageMediaID,
	)
	var i ThemeLocation
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.MapID,
		&i.Name,
		&i.RestrictedCharacters,
		&i.SortOrder,
		&i.CreatedAt,
		&i.FromRound,
		&i.UntilRound,
		&i.ImageUrl,
		&i.ImageMediaID,
	)
	return i, err
}

const createMap = `-- name: CreateMap :one
INSERT INTO theme_maps (theme_id, name, image_url, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, theme_id, name, image_url, sort_order, created_at
`

type CreateMapParams struct {
	ThemeID   uuid.UUID   `json:"theme_id"`
	Name      string      `json:"name"`
	ImageUrl  pgtype.Text `json:"image_url"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateMap(ctx context.Context, arg CreateMapParams) (ThemeMap, error) {
	row := q.db.QueryRow(ctx, createMap,
		arg.ThemeID,
		arg.Name,
		arg.ImageUrl,
		arg.SortOrder,
	)
	var i ThemeMap
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClue = `-- name: DeleteClue :exec
DELETE FROM theme_clues WHERE id = $1
`

func (q *Queries) DeleteClue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClue, id)
	return err
}

const deleteClueWithOwner = `-- name: DeleteClueWithOwner :execrows
DELETE FROM theme_clues c USING themes t
WHERE c.id = $1 AND c.theme_id = t.id AND t.creator_id = $2
`

type DeleteClueWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteClueWithOwner(ctx context.Context, arg DeleteClueWithOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClueWithOwner, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM theme_contents WHERE theme_id = $1 AND key = $2
`

type DeleteContentParams struct {
	ThemeID uuid.UUID `json:"theme_id"`
	Key     string    `json:"key"`
}

func (q *Queries) DeleteContent(ctx context.Context, arg DeleteContentParams) error {
	_, err := q.db.Exec(ctx, deleteContent, arg.ThemeID, arg.Key)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM theme_locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deleteLocationWithOwner = `-- name: DeleteLocationWithOwner :execrows
DELETE FROM theme_locations l USING themes t
WHERE l.id = $1 AND l.theme_id = t.id AND t.creator_id = $2
`

type DeleteLocationWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteLocationWithOwner(ctx context.Context, arg DeleteLocationWithOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocationWithOwner, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMap = `-- name: DeleteMap :exec
DELETE FROM theme_maps WHERE id = $1
`

func (q *Queries) DeleteMap(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMap, id)
	return err
}

const deleteMapWithOwner = `-- name: DeleteMapWithOwner :execrows
DELETE FROM theme_maps m USING themes t
WHERE m.id = $1 AND m.theme_id = t.id AND t.creator_id = $2
`

type DeleteMapWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteMapWithOwner(ctx context.Context, arg DeleteMapWithOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMapWithOwner, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClue = `-- name: GetClue :one
SELECT id, theme_id, location_id, name, description, image_url, is_common, level, sort_order, created_at, is_usable, use_effect, use_target, use_consumed, reveal_round, hide_round FROM theme_clues WHERE id = $1
`

func (q *Queries) GetClue(ctx context.Context, id uuid.UUID) (ThemeClue, error) {
	row := q.db.QueryRow(ctx, getClue, id)
	var i ThemeClue
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsCommon,
		&i.Level,
		&i.SortOrder,
		&i.CreatedAt,
		&i.IsUsable,
		&i.UseEffect,
		&i.UseTarget,
		&i.UseConsumed,
		&i.RevealRound,
		&i.HideRound,
	)
	return i, err
}

const getClueWithOwner = `-- name: GetClueWithOwner :one
SELECT c.id, c.theme_id, c.location_id, c.name, c.description, c.image_url, c.is_common, c.level, c.sort_order, c.created_at, c.is_usable, c.use_effect, c.use_target, c.use_consumed, c.reveal_round, c.hide_round FROM theme_clues c
JOIN themes t ON c.theme_id = t.id
WHERE c.id = $1 AND t.creator_id = $2
`

type GetClueWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) GetClueWithOwner(ctx context.Context, arg GetClueWithOwnerParams) (ThemeClue, error) {
	row := q.db.QueryRow(ctx, getClueWithOwner, arg.ID, arg.CreatorID)
	var i ThemeClue
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsCommon,
		&i.Level,
		&i.SortOrder,
		&i.CreatedAt,
		&i.IsUsable,
		&i.UseEffect,
		&i.UseTarget,
		&i.UseConsumed,
		&i.RevealRound,
		&i.HideRound,
	)
	return i, err
}

const getContent = `-- name: GetContent :one

SELECT id, theme_id, key, body, updated_at FROM theme_contents WHERE theme_id = $1 AND key = $2
`

type GetContentParams struct {
	ThemeID uuid.UUID `json:"theme_id"`
	Key     string    `json:"key"`
}

// ============================================================
// Contents
// ============================================================
func (q *Queries) GetContent(ctx context.Context, arg GetContentParams) (ThemeContent, error) {
	row := q.db.QueryRow(ctx, getContent, arg.ThemeID, arg.Key)
	var i ThemeContent
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Key,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, theme_id, map_id, name, restricted_characters, sort_order, created_at, from_round, until_round, image_url, image_media_id FROM theme_locations WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (ThemeLocation, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i ThemeLocation
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.MapID,
		&i.Name,
		&i.RestrictedCharacters,
		&i.SortOrder,
		&i.CreatedAt,
		&i.FromRound,
		&i.UntilRound,
		&i.ImageUrl,
		&i.ImageMediaID,
	)
	return i, err
}

const getLocationWithOwner = `-- name: GetLocationWithOwner :one
SELECT l.id, l.theme_id, l.map_id, l.name, l.restricted_characters, l.sort_order, l.created_at, l.from_round, l.until_round, l.image_url, l.image_media_id FROM theme_locations l
JOIN themes t ON l.theme_id = t.id
WHERE l.id = $1 AND t.creator_id = $2
`

type GetLocationWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) GetLocationWithOwner(ctx context.Context, arg GetLocationWithOwnerParams) (ThemeLocation, error) {
	row := q.db.QueryRow(ctx, getLocationWithOwner, arg.ID, arg.CreatorID)
	var i ThemeLocation
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.MapID,
		&i.Name,
		&i.RestrictedCharacters,
		&i.SortOrder,
		&i.CreatedAt,
		&i.FromRound,
		&i.UntilRound,
		&i.ImageUrl,
		&i.ImageMediaID,
	)
	return i, err
}

const getMap = `-- name: GetMap :one
SELECT id, theme_id, name, image_url, sort_order, created_at FROM theme_maps WHERE id = $1
`

func (q *Queries) GetMap(ctx context.Context, id uuid.UUID) (ThemeMap, error) {
	row := q.db.QueryRow(ctx, getMap, id)
	var i ThemeMap
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getMapWithOwner = `-- name: GetMapWithOwner :one

SELECT m.id, m.theme_id, m.name, m.image_url, m.sort_order, m.created_at FROM theme_maps m
JOIN themes t ON m.theme_id = t.id
WHERE m.id = $1 AND t.creator_id = $2
`

type GetMapWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

// ============================================================
// Ownership verification (JOIN-based, single query)
// ============================================================
func (q *Queries) GetMapWithOwner(ctx context.Context, arg GetMapWithOwnerParams) (ThemeMap, error) {
	row := q.db.QueryRow(ctx, getMapWithOwner, arg.ID, arg.CreatorID)
	var i ThemeMap
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listCluesByLocation = `-- name: ListCluesByLocation :many
SELECT id, theme_id, location_id, name, description, image_url, is_common, level, sort_order, created_at, is_usable, use_effect, use_target, use_consumed, reveal_round, hide_round FROM theme_clues WHERE location_id = $1 ORDER BY sort_order
`

func (q *Queries) ListCluesByLocation(ctx context.Context, locationID pgtype.UUID) ([]ThemeClue, error) {
	rows, err := q.db.Query(ctx, listCluesByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeClue{}
	for rows.Next() {
		var i ThemeClue
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.IsCommon,
			&i.Level,
			&i.SortOrder,
			&i.CreatedAt,
			&i.IsUsable,
			&i.UseEffect,
			&i.UseTarget,
			&i.UseConsumed,
			&i.RevealRound,
			&i.HideRound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCluesByTheme = `-- name: ListCluesByTheme :many

SELECT id, theme_id, location_id, name, description, image_url, is_common, level, sort_order, created_at, is_usable, use_effect, use_target, use_consumed, reveal_round, hide_round FROM theme_clues WHERE theme_id = $1 ORDER BY sort_order
`

// ============================================================
// Clues
// ============================================================
func (q *Queries) ListCluesByTheme(ctx context.Context, themeID uuid.UUID) ([]ThemeClue, error) {
	rows, err := q.db.Query(ctx, listCluesByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeClue{}
	for rows.Next() {
		var i ThemeClue
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.IsCommon,
			&i.Level,
			&i.SortOrder,
			&i.CreatedAt,
			&i.IsUsable,
			&i.UseEffect,
			&i.UseTarget,
			&i.UseConsumed,
			&i.RevealRound,
			&i.HideRound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsByTheme = `-- name: ListContentsByTheme :many
SELECT id, theme_id, key, body, updated_at FROM theme_contents WHERE theme_id = $1 ORDER BY key
`

func (q *Queries) ListContentsByTheme(ctx context.Context, themeID uuid.UUID) ([]ThemeContent, error) {
	rows, err := q.db.Query(ctx, listContentsByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeContent{}
	for rows.Next() {
		var i ThemeContent
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Key,
			&i.Body,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByMap = `-- name: ListLocationsByMap :many

SELECT id, theme_id, map_id, name, restricted_characters, sort_order, created_at, from_round, until_round, image_url, image_media_id FROM theme_locations WHERE map_id = $1 ORDER BY sort_order
`

// ============================================================
// Locations
// ============================================================
func (q *Queries) ListLocationsByMap(ctx context.Context, mapID uuid.UUID) ([]ThemeLocation, error) {
	rows, err := q.db.Query(ctx, listLocationsByMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeLocation{}
	for rows.Next() {
		var i ThemeLocation
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.MapID,
			&i.Name,
			&i.RestrictedCharacters,
			&i.SortOrder,
			&i.CreatedAt,
			&i.FromRound,
			&i.UntilRound,
			&i.ImageUrl,
			&i.ImageMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByTheme = `-- name: ListLocationsByTheme :many
SELECT id, theme_id, map_id, name, restricted_characters, sort_order, created_at, from_round, until_round, image_url, image_media_id FROM theme_locations WHERE theme_id = $1 ORDER BY sort_order
`

func (q *Queries) ListLocationsByTheme(ctx context.Context, themeID uuid.UUID) ([]ThemeLocation, error) {
	rows, err := q.db.Query(ctx, listLocationsByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeLocation{}
	for rows.Next() {
		var i ThemeLocation
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.MapID,
			&i.Name,
			&i.RestrictedCharacters,
			&i.SortOrder,
			&i.CreatedAt,
			&i.FromRound,
			&i.UntilRound,
			&i.ImageUrl,
			&i.ImageMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapsByTheme = `-- name: ListMapsByTheme :many

SELECT id, theme_id, name, image_url, sort_order, created_at FROM theme_maps WHERE theme_id = $1 ORDER BY sort_order
`

// ============================================================
// Maps
// ============================================================
func (q *Queries) ListMapsByTheme(ctx context.Context, themeID uuid.UUID) ([]ThemeMap, error) {
	rows, err := q.db.Query(ctx, listMapsByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeMap{}
	for rows.Next() {
		var i ThemeMap
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Name,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClue = `-- name: UpdateClue :one
UPDATE theme_clues
SET location_id = $2, name = $3, description = $4, image_url = $5, is_common = $6, level = $7, sort_order = $8, is_usable = $9, use_effect = $10, use_target = $11, use_consumed = $12, reveal_round = $13, hide_round = $14
WHERE id = $1
RETURNING id, theme_id, location_id, name, description, image_url, is_common, level, sort_order, created_at, is_usable, use_effect, use_target, use_consumed, reveal_round, hide_round
`

type UpdateClueParams struct {
	ID          uuid.UUID   `json:"id"`
	LocationID  pgtype.UUID `json:"location_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrl    pgtype.Text `json:"image_url"`
	IsCommon    bool        `json:"is_common"`
	Level       int32       `json:"level"`
	SortOrder   int32       `json:"sort_order"`
	IsUsable    bool        `json:"is_usable"`
	UseEffect   pgtype.Text `json:"use_effect"`
	UseTarget   pgtype.Text `json:"use_target"`
	UseConsumed bool        `json:"use_consumed"`
	RevealRound pgtype.Int4 `json:"reveal_round"`
	HideRound   pgtype.Int4 `json:"hide_round"`
}

func (q *Queries) UpdateClue(ctx context.Context, arg UpdateClueParams) (ThemeClue, error) {
	row := q.db.QueryRow(ctx, updateClue,
		arg.ID,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.IsCommon,
		arg.Level,
		arg.SortOrder,
		arg.IsUsable,
		arg.UseEffect,
		arg.UseTarget,
		arg.UseConsumed,
		arg.RevealRound,
		arg.HideRound,
	)
	var i ThemeClue
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsCommon,
		&i.Level,
		&i.SortOrder,
		&i.CreatedAt,
		&i.IsUsable,
		&i.UseEffect,
		&i.UseTarget,
		&i.UseConsumed,
		&i.RevealRound,
		&i.HideRound,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE theme_locations
SET name = $2, restricted_characters = $3, sort_order = $4, from_round = $5, until_round = $6, image_url = $7, image_media_id = $8
WHERE id = $1
RETURNING id, theme_id, map_id, name, restricted_characters, sort_order, created_at, from_round, until_round, image_url, image_media_id
`

type UpdateLocationParams struct {
	ID                   uuid.UUID   `json:"id"`
	Name                 string      `json:"name"`
	RestrictedCharacters pgtype.Text `json:"restricted_characters"`
	SortOrder            int32       `json:"sort_order"`
	FromRound            pgtype.Int4 `json:"from_round"`
	UntilRound           pgtype.Int4 `json:"until_round"`
	ImageUrl             pgtype.Text `json:"image_url"`
	ImageMediaID         pgtype.UUID `json:"image_media_id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (ThemeLocation, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.RestrictedCharacters,
		arg.SortOrder,
		arg.FromRound,
		arg.UntilRound,
		arg.ImageUrl,
		arg.ImageMediaID,
	)
	var i ThemeLocation
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.MapID,
		&i.Name,
		&i.RestrictedCharacters,
		&i.SortOrder,
		&i.CreatedAt,
		&i.FromRound,
		&i.UntilRound,
		&i.ImageUrl,
		&i.ImageMediaID,
	)
	return i, err
}

const updateMap = `-- name: UpdateMap :one
UPDATE theme_maps SET name = $2, image_url = $3, sort_order = $4
WHERE id = $1
RETURNING id, theme_id, name, image_url, sort_order, created_at
`

type UpdateMapParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	ImageUrl  pgtype.Text `json:"image_url"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateMap(ctx context.Context, arg UpdateMapParams) (ThemeMap, error) {
	row := q.db.QueryRow(ctx, updateMap,
		arg.ID,
		arg.Name,
		arg.ImageUrl,
		arg.SortOrder,
	)
	var i ThemeMap
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const upsertContent = `-- name: UpsertContent :one
INSERT INTO theme_contents (theme_id, key, body, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (theme_id, key) DO UPDATE SET body = EXCLUDED.body, updated_at = NOW()
RETURNING id, theme_id, key, body, updated_at
`

type UpsertContentParams struct {
	ThemeID uuid.UUID `json:"theme_id"`
	Key     string    `json:"key"`
	Body    string    `json:"body"`
}

func (q *Queries) UpsertContent(ctx context.Context, arg UpsertContentParams) (ThemeContent, error) {
	row := q.db.QueryRow(ctx, upsertContent, arg.ThemeID, arg.Key, arg.Body)
	var i ThemeContent
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Key,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}
