// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flow.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFlowEdge = `-- name: CreateFlowEdge :one
INSERT INTO flow_edges (theme_id, source_id, target_id, condition, label, sort_order)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, theme_id, source_id, target_id, condition, label, sort_order, created_at
`

type CreateFlowEdgeParams struct {
	ThemeID   uuid.UUID   `json:"theme_id"`
	SourceID  uuid.UUID   `json:"source_id"`
	TargetID  uuid.UUID   `json:"target_id"`
	Condition []byte      `json:"condition"`
	Label     pgtype.Text `json:"label"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateFlowEdge(ctx context.Context, arg CreateFlowEdgeParams) (FlowEdge, error) {
	row := q.db.QueryRow(ctx, createFlowEdge,
		arg.ThemeID,
		arg.SourceID,
		arg.TargetID,
		arg.Condition,
		arg.Label,
		arg.SortOrder,
	)
	var i FlowEdge
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.SourceID,
		&i.TargetID,
		&i.Condition,
		&i.Label,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createFlowNode = `-- name: CreateFlowNode :one
INSERT INTO flow_nodes (theme_id, type, data, position_x, position_y)
VALUES ($1, $2, $3, $4, $5) RETURNING id, theme_id, type, data, position_x, position_y, created_at, updated_at
`

type CreateFlowNodeParams struct {
	ThemeID   uuid.UUID       `json:"theme_id"`
	Type      string          `json:"type"`
	Data      json.RawMessage `json:"data"`
	PositionX float64         `json:"position_x"`
	PositionY float64         `json:"position_y"`
}

func (q *Queries) CreateFlowNode(ctx context.Context, arg CreateFlowNodeParams) (FlowNode, error) {
	row := q.db.QueryRow(ctx, createFlowNode,
		arg.ThemeID,
		arg.Type,
		arg.Data,
		arg.PositionX,
		arg.PositionY,
	)
	var i FlowNode
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Type,
		&i.Data,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowEdge = `-- name: DeleteFlowEdge :exec
DELETE FROM flow_edges WHERE id = $1
`

func (q *Queries) DeleteFlowEdge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowEdge, id)
	return err
}

const deleteFlowEdgesByTheme = `-- name: DeleteFlowEdgesByTheme :exec
DELETE FROM flow_edges WHERE theme_id = $1
`

func (q *Queries) DeleteFlowEdgesByTheme(ctx context.Context, themeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowEdgesByTheme, themeID)
	return err
}

const deleteFlowNode = `-- name: DeleteFlowNode :exec
DELETE FROM flow_nodes WHERE id = $1
`

func (q *Queries) DeleteFlowNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowNode, id)
	return err
}

const deleteFlowNodesByTheme = `-- name: DeleteFlowNodesByTheme :exec
DELETE FROM flow_nodes WHERE theme_id = $1
`

func (q *Queries) DeleteFlowNodesByTheme(ctx context.Context, themeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowNodesByTheme, themeID)
	return err
}

const getFlowEdge = `-- name: GetFlowEdge :one
SELECT id, theme_id, source_id, target_id, condition, label, sort_order, created_at FROM flow_edges WHERE id = $1
`

func (q *Queries) GetFlowEdge(ctx context.Context, id uuid.UUID) (FlowEdge, error) {
	row := q.db.QueryRow(ctx, getFlowEdge, id)
	var i FlowEdge
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.SourceID,
		&i.TargetID,
		&i.Condition,
		&i.Label,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getFlowNode = `-- name: GetFlowNode :one
SELECT id, theme_id, type, data, position_x, position_y, created_at, updated_at FROM flow_nodes WHERE id = $1
`

func (q *Queries) GetFlowNode(ctx context.Context, id uuid.UUID) (FlowNode, error) {
	row := q.db.QueryRow(ctx, getFlowNode, id)
	var i FlowNode
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Type,
		&i.Data,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlowEdgesByTheme = `-- name: ListFlowEdgesByTheme :many
SELECT id, theme_id, source_id, target_id, condition, label, sort_order, created_at FROM flow_edges WHERE theme_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListFlowEdgesByTheme(ctx context.Context, themeID uuid.UUID) ([]FlowEdge, error) {
	rows, err := q.db.Query(ctx, listFlowEdgesByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowEdge{}
	for rows.Next() {
		var i FlowEdge
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.SourceID,
			&i.TargetID,
			&i.Condition,
			&i.Label,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowNodesByTheme = `-- name: ListFlowNodesByTheme :many
SELECT id, theme_id, type, data, position_x, position_y, created_at, updated_at FROM flow_nodes WHERE theme_id = $1 ORDER BY created_at
`

func (q *Queries) ListFlowNodesByTheme(ctx context.Context, themeID uuid.UUID) ([]FlowNode, error) {
	rows, err := q.db.Query(ctx, listFlowNodesByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowNode{}
	for rows.Next() {
		var i FlowNode
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Type,
			&i.Data,
			&i.PositionX,
			&i.PositionY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowEdge = `-- name: UpdateFlowEdge :one
UPDATE flow_edges SET source_id = $2, target_id = $3, condition = $4, label = $5, sort_order = $6
WHERE id = $1 RETURNING id, theme_id, source_id, target_id, condition, label, sort_order, created_at
`

type UpdateFlowEdgeParams struct {
	ID        uuid.UUID   `json:"id"`
	SourceID  uuid.UUID   `json:"source_id"`
	TargetID  uuid.UUID   `json:"target_id"`
	Condition []byte      `json:"condition"`
	Label     pgtype.Text `json:"label"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateFlowEdge(ctx context.Context, arg UpdateFlowEdgeParams) (FlowEdge, error) {
	row := q.db.QueryRow(ctx, updateFlowEdge,
		arg.ID,
		arg.SourceID,
		arg.TargetID,
		arg.Condition,
		arg.Label,
		arg.SortOrder,
	)
	var i FlowEdge
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.SourceID,
		&i.TargetID,
		&i.Condition,
		&i.Label,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateFlowNode = `-- name: UpdateFlowNode :one
UPDATE flow_nodes SET type = $2, data = $3, position_x = $4, position_y = $5, updated_at = now()
WHERE id = $1 RETURNING id, theme_id, type, data, position_x, position_y, created_at, updated_at
`

type UpdateFlowNodeParams struct {
	ID        uuid.UUID       `json:"id"`
	Type      string          `json:"type"`
	Data      json.RawMessage `json:"data"`
	PositionX float64         `json:"position_x"`
	PositionY float64         `json:"position_y"`
}

func (q *Queries) UpdateFlowNode(ctx context.Context, arg UpdateFlowNodeParams) (FlowNode, error) {
	row := q.db.QueryRow(ctx, updateFlowNode,
		arg.ID,
		arg.Type,
		arg.Data,
		arg.PositionX,
		arg.PositionY,
	)
	var i FlowNode
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Type,
		&i.Data,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
