// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaByTheme = `-- name: CountMediaByTheme :one
SELECT count(*) FROM theme_media WHERE theme_id = $1
`

func (q *Queries) CountMediaByTheme(ctx context.Context, themeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaByTheme, themeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO theme_media (theme_id, name, type, source_type, url, storage_key, duration, file_size, mime_type, tags, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, theme_id, name, type, source_type, url, storage_key, duration, file_size, mime_type, tags, sort_order, created_at, updated_at
`

type CreateMediaParams struct {
	ThemeID    uuid.UUID   `json:"theme_id"`
	Name       string      `json:"name"`
	Type       string      `json:"type"`
	SourceType string      `json:"source_type"`
	Url        pgtype.Text `json:"url"`
	StorageKey pgtype.Text `json:"storage_key"`
	Duration   pgtype.Int4 `json:"duration"`
	FileSize   pgtype.Int8 `json:"file_size"`
	MimeType   pgtype.Text `json:"mime_type"`
	Tags       []string    `json:"tags"`
	SortOrder  int32       `json:"sort_order"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (ThemeMedium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.ThemeID,
		arg.Name,
		arg.Type,
		arg.SourceType,
		arg.Url,
		arg.StorageKey,
		arg.Duration,
		arg.FileSize,
		arg.MimeType,
		arg.Tags,
		arg.SortOrder,
	)
	var i ThemeMedium
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Type,
		&i.SourceType,
		&i.Url,
		&i.StorageKey,
		&i.Duration,
		&i.FileSize,
		&i.MimeType,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM theme_media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const deleteMediaWithOwner = `-- name: DeleteMediaWithOwner :execrows
DELETE FROM theme_media m USING themes t
WHERE m.id = $1 AND m.theme_id = t.id AND t.creator_id = $2
`

type DeleteMediaWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteMediaWithOwner(ctx context.Context, arg DeleteMediaWithOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMediaWithOwner, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMedia = `-- name: GetMedia :one
SELECT id, theme_id, name, type, source_type, url, storage_key, duration, file_size, mime_type, tags, sort_order, created_at, updated_at FROM theme_media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (ThemeMedium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i ThemeMedium
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Type,
		&i.SourceType,
		&i.Url,
		&i.StorageKey,
		&i.Duration,
		&i.FileSize,
		&i.MimeType,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaWithOwner = `-- name: GetMediaWithOwner :one

SELECT m.id, m.theme_id, m.name, m.type, m.source_type, m.url, m.storage_key, m.duration, m.file_size, m.mime_type, m.tags, m.sort_order, m.created_at, m.updated_at FROM theme_media m
JOIN themes t ON m.theme_id = t.id
WHERE m.id = $1 AND t.creator_id = $2
`

type GetMediaWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

// ============================================================
// Media (Owner-verified)
// ============================================================
func (q *Queries) GetMediaWithOwner(ctx context.Context, arg GetMediaWithOwnerParams) (ThemeMedium, error) {
	row := q.db.QueryRow(ctx, getMediaWithOwner, arg.ID, arg.CreatorID)
	var i ThemeMedium
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Type,
		&i.SourceType,
		&i.Url,
		&i.StorageKey,
		&i.Duration,
		&i.FileSize,
		&i.MimeType,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaByIDs = `-- name: ListMediaByIDs :many

SELECT id, theme_id, name, type, source_type, url, storage_key, duration, file_size, mime_type, tags, sort_order, created_at, updated_at FROM theme_media WHERE id = ANY($1::uuid[])
`

// ============================================================
// Media (Batch)
// ============================================================
func (q *Queries) ListMediaByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ThemeMedium, error) {
	rows, err := q.db.Query(ctx, listMediaByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeMedium{}
	for rows.Next() {
		var i ThemeMedium
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Name,
			&i.Type,
			&i.SourceType,
			&i.Url,
			&i.StorageKey,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Tags,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByTheme = `-- name: ListMediaByTheme :many

SELECT id, theme_id, name, type, source_type, url, storage_key, duration, file_size, mime_type, tags, sort_order, created_at, updated_at FROM theme_media WHERE theme_id = $1 ORDER BY sort_order, created_at
`

// ============================================================
// Media
// ============================================================
func (q *Queries) ListMediaByTheme(ctx context.Context, themeID uuid.UUID) ([]ThemeMedium, error) {
	rows, err := q.db.Query(ctx, listMediaByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeMedium{}
	for rows.Next() {
		var i ThemeMedium
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Name,
			&i.Type,
			&i.SourceType,
			&i.Url,
			&i.StorageKey,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Tags,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByThemeAndType = `-- name: ListMediaByThemeAndType :many
SELECT id, theme_id, name, type, source_type, url, storage_key, duration, file_size, mime_type, tags, sort_order, created_at, updated_at FROM theme_media WHERE theme_id = $1 AND type = $2 ORDER BY sort_order, created_at
`

type ListMediaByThemeAndTypeParams struct {
	ThemeID uuid.UUID `json:"theme_id"`
	Type    string    `json:"type"`
}

func (q *Queries) ListMediaByThemeAndType(ctx context.Context, arg ListMediaByThemeAndTypeParams) ([]ThemeMedium, error) {
	rows, err := q.db.Query(ctx, listMediaByThemeAndType, arg.ThemeID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeMedium{}
	for rows.Next() {
		var i ThemeMedium
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Name,
			&i.Type,
			&i.SourceType,
			&i.Url,
			&i.StorageKey,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Tags,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMediaSizeByCreator = `-- name: SumMediaSizeByCreator :one
SELECT COALESCE(sum(m.file_size), 0)::BIGINT FROM theme_media m
JOIN themes t ON m.theme_id = t.id
WHERE t.creator_id = $1
`

func (q *Queries) SumMediaSizeByCreator(ctx context.Context, creatorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumMediaSizeByCreator, creatorID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumMediaSizeByTheme = `-- name: SumMediaSizeByTheme :one
SELECT COALESCE(sum(file_size), 0)::BIGINT FROM theme_media WHERE theme_id = $1
`

func (q *Queries) SumMediaSizeByTheme(ctx context.Context, themeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumMediaSizeByTheme, themeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE theme_media SET name = $2, type = $3, duration = $4, tags = $5, sort_order = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, theme_id, name, type, source_type, url, storage_key, duration, file_size, mime_type, tags, sort_order, created_at, updated_at
`

type UpdateMediaParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Duration  pgtype.Int4 `json:"duration"`
	Tags      []string    `json:"tags"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (ThemeMedium, error) {
	row := q.db.QueryRow(ctx, updateMedia,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Duration,
		arg.Tags,
		arg.SortOrder,
	)
	var i ThemeMedium
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Type,
		&i.SourceType,
		&i.Url,
		&i.StorageKey,
		&i.Duration,
		&i.FileSize,
		&i.MimeType,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
