// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GameSession struct {
	ID           uuid.UUID          `json:"id"`
	RoomID       uuid.UUID          `json:"room_id"`
	ThemeID      uuid.UUID          `json:"theme_id"`
	CurrentPhase string             `json:"current_phase"`
	PhaseIndex   int32              `json:"phase_index"`
	StateJson    json.RawMessage    `json:"state_json"`
	StartedAt    time.Time          `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
}

type Room struct {
	ID         uuid.UUID `json:"id"`
	ThemeID    uuid.UUID `json:"theme_id"`
	HostID     uuid.UUID `json:"host_id"`
	Code       string    `json:"code"`
	Status     string    `json:"status"`
	MaxPlayers int32     `json:"max_players"`
	IsPrivate  bool      `json:"is_private"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RoomPlayer struct {
	RoomID      uuid.UUID   `json:"room_id"`
	UserID      uuid.UUID   `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	IsReady     bool        `json:"is_ready"`
	JoinedAt    time.Time   `json:"joined_at"`
}

type SessionEvent struct {
	ID        int64           `json:"id"`
	SessionID uuid.UUID       `json:"session_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type SessionPlayer struct {
	SessionID   uuid.UUID `json:"session_id"`
	UserID      uuid.UUID `json:"user_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Score       int32     `json:"score"`
	IsAlive     bool      `json:"is_alive"`
}

type Theme struct {
	ID          uuid.UUID          `json:"id"`
	CreatorID   uuid.UUID          `json:"creator_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CoverImage  pgtype.Text        `json:"cover_image"`
	MinPlayers  int32              `json:"min_players"`
	MaxPlayers  int32              `json:"max_players"`
	DurationMin int32              `json:"duration_min"`
	Price       int32              `json:"price"`
	Status      string             `json:"status"`
	ConfigJson  json.RawMessage    `json:"config_json"`
	Version     int32              `json:"version"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type ThemeCharacter struct {
	ID          uuid.UUID   `json:"id"`
	ThemeID     uuid.UUID   `json:"theme_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrl    pgtype.Text `json:"image_url"`
	IsCulprit   bool        `json:"is_culprit"`
	SortOrder   int32       `json:"sort_order"`
}

type User struct {
	ID          uuid.UUID   `json:"id"`
	Nickname    string      `json:"nickname"`
	Email       pgtype.Text `json:"email"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Role        string      `json:"role"`
	Provider    string      `json:"provider"`
	ProviderID  string      `json:"provider_id"`
	CoinBalance int64       `json:"coin_balance"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
