// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_preferences.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationPrefs = `-- name: GetNotificationPrefs :one
SELECT user_id, game_invite, room_status, marketing, updated_at FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPrefs(ctx context.Context, userID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.GameInvite,
		&i.RoomStatus,
		&i.Marketing,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPrefs = `-- name: UpsertNotificationPrefs :one
INSERT INTO notification_preferences (user_id, game_invite, room_status, marketing, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    game_invite = EXCLUDED.game_invite,
    room_status = EXCLUDED.room_status,
    marketing = EXCLUDED.marketing,
    updated_at = NOW()
RETURNING user_id, game_invite, room_status, marketing, updated_at
`

type UpsertNotificationPrefsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	GameInvite bool      `json:"game_invite"`
	RoomStatus bool      `json:"room_status"`
	Marketing  bool      `json:"marketing"`
}

func (q *Queries) UpsertNotificationPrefs(ctx context.Context, arg UpsertNotificationPrefsParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPrefs,
		arg.UserID,
		arg.GameInvite,
		arg.RoomStatus,
		arg.Marketing,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.GameInvite,
		&i.RoomStatus,
		&i.Marketing,
		&i.UpdatedAt,
	)
	return i, err
}
