// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPayment = `-- name: ConfirmPayment :one
UPDATE payments
SET status = 'CONFIRMED', payment_key = $2, confirmed_at = NOW()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, user_id, package_id, payment_key, idempotency_key, provider, status, amount_krw, base_coins, bonus_coins, refunded_at, confirmed_at, created_at, updated_at
`

type ConfirmPaymentParams struct {
	ID         uuid.UUID   `json:"id"`
	PaymentKey pgtype.Text `json:"payment_key"`
}

func (q *Queries) ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, confirmPayment, arg.ID, arg.PaymentKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.PaymentKey,
		&i.IdempotencyKey,
		&i.Provider,
		&i.Status,
		&i.AmountKrw,
		&i.BaseCoins,
		&i.BonusCoins,
		&i.RefundedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPaymentsByUser = `-- name: CountPaymentsByUser :one
SELECT COUNT(*) FROM payments WHERE user_id = $1
`

func (q *Queries) CountPaymentsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO coin_packages (platform, name, price_krw, base_coins, bonus_coins, sort_order, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, platform, name, price_krw, base_coins, bonus_coins, sort_order, is_active, created_at, updated_at
`

type CreatePackageParams struct {
	Platform   string `json:"platform"`
	Name       string `json:"name"`
	PriceKrw   int32  `json:"price_krw"`
	BaseCoins  int32  `json:"base_coins"`
	BonusCoins int32  `json:"bonus_coins"`
	SortOrder  int32  `json:"sort_order"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (CoinPackage, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.Platform,
		arg.Name,
		arg.PriceKrw,
		arg.BaseCoins,
		arg.BonusCoins,
		arg.SortOrder,
		arg.IsActive,
	)
	var i CoinPackage
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Name,
		&i.PriceKrw,
		&i.BaseCoins,
		&i.BonusCoins,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (user_id, package_id, idempotency_key, provider, amount_krw, base_coins, bonus_coins)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, package_id, payment_key, idempotency_key, provider, status, amount_krw, base_coins, bonus_coins, refunded_at, confirmed_at, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID         uuid.UUID `json:"user_id"`
	PackageID      uuid.UUID `json:"package_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
	Provider       string    `json:"provider"`
	AmountKrw      int32     `json:"amount_krw"`
	BaseCoins      int32     `json:"base_coins"`
	BonusCoins     int32     `json:"bonus_coins"`
}

// ═══════════════════════════════════════════════════════════════════
// Payments
// ═══════════════════════════════════════════════════════════════════
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.PackageID,
		arg.IdempotencyKey,
		arg.Provider,
		arg.AmountKrw,
		arg.BaseCoins,
		arg.BonusCoins,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.PaymentKey,
		&i.IdempotencyKey,
		&i.Provider,
		&i.Status,
		&i.AmountKrw,
		&i.BaseCoins,
		&i.BonusCoins,
		&i.RefundedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failPayment = `-- name: FailPayment :exec
UPDATE payments SET status = 'FAILED'
WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) FailPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failPayment, id)
	return err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, platform, name, price_krw, base_coins, bonus_coins, sort_order, is_active, created_at, updated_at FROM coin_packages WHERE id = $1
`

func (q *Queries) GetPackageByID(ctx context.Context, id uuid.UUID) (CoinPackage, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i CoinPackage
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Name,
		&i.PriceKrw,
		&i.BaseCoins,
		&i.BonusCoins,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, package_id, payment_key, idempotency_key, provider, status, amount_krw, base_coins, bonus_coins, refunded_at, confirmed_at, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.PaymentKey,
		&i.IdempotencyKey,
		&i.Provider,
		&i.Status,
		&i.AmountKrw,
		&i.BaseCoins,
		&i.BonusCoins,
		&i.RefundedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, user_id, package_id, payment_key, idempotency_key, provider, status, amount_krw, base_coins, bonus_coins, refunded_at, confirmed_at, created_at, updated_at FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.PaymentKey,
		&i.IdempotencyKey,
		&i.Provider,
		&i.Status,
		&i.AmountKrw,
		&i.BaseCoins,
		&i.BonusCoins,
		&i.RefundedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePackages = `-- name: ListActivePackages :many

SELECT id, platform, name, price_krw, base_coins, bonus_coins, sort_order, is_active, created_at, updated_at FROM coin_packages
WHERE is_active = true AND platform = $1
ORDER BY sort_order
`

// ═══════════════════════════════════════════════════════════════════
// Coin Packages
// ═══════════════════════════════════════════════════════════════════
func (q *Queries) ListActivePackages(ctx context.Context, platform string) ([]CoinPackage, error) {
	rows, err := q.db.Query(ctx, listActivePackages, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoinPackage{}
	for rows.Next() {
		var i CoinPackage
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Name,
			&i.PriceKrw,
			&i.BaseCoins,
			&i.BonusCoins,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT id, user_id, package_id, payment_key, idempotency_key, provider, status, amount_krw, base_coins, bonus_coins, refunded_at, confirmed_at, created_at, updated_at FROM payments
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PackageID,
			&i.PaymentKey,
			&i.IdempotencyKey,
			&i.Provider,
			&i.Status,
			&i.AmountKrw,
			&i.BaseCoins,
			&i.BonusCoins,
			&i.RefundedAt,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE coin_packages
SET name = $2, price_krw = $3, base_coins = $4, bonus_coins = $5, sort_order = $6, is_active = $7
WHERE id = $1
RETURNING id, platform, name, price_krw, base_coins, bonus_coins, sort_order, is_active, created_at, updated_at
`

type UpdatePackageParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	PriceKrw   int32     `json:"price_krw"`
	BaseCoins  int32     `json:"base_coins"`
	BonusCoins int32     `json:"bonus_coins"`
	SortOrder  int32     `json:"sort_order"`
	IsActive   bool      `json:"is_active"`
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (CoinPackage, error) {
	row := q.db.QueryRow(ctx, updatePackage,
		arg.ID,
		arg.Name,
		arg.PriceKrw,
		arg.BaseCoins,
		arg.BonusCoins,
		arg.SortOrder,
		arg.IsActive,
	)
	var i CoinPackage
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Name,
		&i.PriceKrw,
		&i.BaseCoins,
		&i.BonusCoins,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
