// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_sections.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReadingSection = `-- name: CreateReadingSection :one
INSERT INTO reading_sections (theme_id, name, bgm_media_id, lines, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, theme_id, name, bgm_media_id, lines, sort_order, version, created_at, updated_at
`

type CreateReadingSectionParams struct {
	ThemeID    uuid.UUID       `json:"theme_id"`
	Name       string          `json:"name"`
	BgmMediaID pgtype.UUID     `json:"bgm_media_id"`
	Lines      json.RawMessage `json:"lines"`
	SortOrder  int32           `json:"sort_order"`
}

func (q *Queries) CreateReadingSection(ctx context.Context, arg CreateReadingSectionParams) (ReadingSection, error) {
	row := q.db.QueryRow(ctx, createReadingSection,
		arg.ThemeID,
		arg.Name,
		arg.BgmMediaID,
		arg.Lines,
		arg.SortOrder,
	)
	var i ReadingSection
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.BgmMediaID,
		&i.Lines,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReadingSectionWithOwner = `-- name: DeleteReadingSectionWithOwner :execrows
DELETE FROM reading_sections rs USING themes t
WHERE rs.id = $1 AND rs.theme_id = t.id AND t.creator_id = $2
`

type DeleteReadingSectionWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteReadingSectionWithOwner(ctx context.Context, arg DeleteReadingSectionWithOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReadingSectionWithOwner, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findMediaReferencesInReadingSections = `-- name: FindMediaReferencesInReadingSections :many
SELECT DISTINCT rs.id, rs.name FROM reading_sections rs
WHERE rs.theme_id = $1
  AND (
    rs.bgm_media_id = $2::uuid
    OR EXISTS (
      SELECT 1 FROM jsonb_array_elements(rs.lines) AS line
      WHERE line->>'VoiceMediaID' = $2::text
         OR line->>'ImageMediaID' = $2::text
    )
  )
`

type FindMediaReferencesInReadingSectionsParams struct {
	ThemeID uuid.UUID `json:"theme_id"`
	MediaID uuid.UUID `json:"media_id"`
}

type FindMediaReferencesInReadingSectionsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Returns reading sections that reference the given media as bgm_media_id
// OR inside any line's VoiceMediaID/ImageMediaID (PascalCase keys — match engine struct serialization).
func (q *Queries) FindMediaReferencesInReadingSections(ctx context.Context, arg FindMediaReferencesInReadingSectionsParams) ([]FindMediaReferencesInReadingSectionsRow, error) {
	rows, err := q.db.Query(ctx, findMediaReferencesInReadingSections, arg.ThemeID, arg.MediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindMediaReferencesInReadingSectionsRow{}
	for rows.Next() {
		var i FindMediaReferencesInReadingSectionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingSection = `-- name: GetReadingSection :one
SELECT id, theme_id, name, bgm_media_id, lines, sort_order, version, created_at, updated_at FROM reading_sections WHERE id = $1
`

func (q *Queries) GetReadingSection(ctx context.Context, id uuid.UUID) (ReadingSection, error) {
	row := q.db.QueryRow(ctx, getReadingSection, id)
	var i ReadingSection
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.BgmMediaID,
		&i.Lines,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingSectionWithOwner = `-- name: GetReadingSectionWithOwner :one
SELECT rs.id, rs.theme_id, rs.name, rs.bgm_media_id, rs.lines, rs.sort_order, rs.version, rs.created_at, rs.updated_at FROM reading_sections rs
JOIN themes t ON rs.theme_id = t.id
WHERE rs.id = $1 AND t.creator_id = $2
`

type GetReadingSectionWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) GetReadingSectionWithOwner(ctx context.Context, arg GetReadingSectionWithOwnerParams) (ReadingSection, error) {
	row := q.db.QueryRow(ctx, getReadingSectionWithOwner, arg.ID, arg.CreatorID)
	var i ReadingSection
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.BgmMediaID,
		&i.Lines,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReadingSectionsByTheme = `-- name: ListReadingSectionsByTheme :many

SELECT id, theme_id, name, bgm_media_id, lines, sort_order, version, created_at, updated_at FROM reading_sections WHERE theme_id = $1 ORDER BY sort_order, created_at
`

// ============================================================
// Reading Sections
// ============================================================
func (q *Queries) ListReadingSectionsByTheme(ctx context.Context, themeID uuid.UUID) ([]ReadingSection, error) {
	rows, err := q.db.Query(ctx, listReadingSectionsByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingSection{}
	for rows.Next() {
		var i ReadingSection
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Name,
			&i.BgmMediaID,
			&i.Lines,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReadingSection = `-- name: UpdateReadingSection :one
UPDATE reading_sections
SET name = $2,
    bgm_media_id = $3,
    lines = $4,
    sort_order = $5,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND version = $6
RETURNING id, theme_id, name, bgm_media_id, lines, sort_order, version, created_at, updated_at
`

type UpdateReadingSectionParams struct {
	ID         uuid.UUID       `json:"id"`
	Name       string          `json:"name"`
	BgmMediaID pgtype.UUID     `json:"bgm_media_id"`
	Lines      json.RawMessage `json:"lines"`
	SortOrder  int32           `json:"sort_order"`
	Version    int32           `json:"version"`
}

func (q *Queries) UpdateReadingSection(ctx context.Context, arg UpdateReadingSectionParams) (ReadingSection, error) {
	row := q.db.QueryRow(ctx, updateReadingSection,
		arg.ID,
		arg.Name,
		arg.BgmMediaID,
		arg.Lines,
		arg.SortOrder,
		arg.Version,
	)
	var i ReadingSection
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.BgmMediaID,
		&i.Lines,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
