// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveTheme = `-- name: ApproveTheme :one
UPDATE themes
SET status       = 'PUBLISHED',
    published_at = NOW(),
    reviewed_at  = NOW(),
    reviewed_by  = $2,
    review_note  = $3,
    updated_at   = NOW()
WHERE id = $1
  AND status = 'PENDING_REVIEW'
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by
`

type ApproveThemeParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
	ReviewNote pgtype.Text `json:"review_note"`
}

func (q *Queries) ApproveTheme(ctx context.Context, arg ApproveThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, approveTheme, arg.ID, arg.ReviewedBy, arg.ReviewNote)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const getUserTrustedCreator = `-- name: GetUserTrustedCreator :one
SELECT trusted_creator FROM users WHERE id = $1
`

func (q *Queries) GetUserTrustedCreator(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getUserTrustedCreator, id)
	var trusted_creator bool
	err := row.Scan(&trusted_creator)
	return trusted_creator, err
}

const listPendingReviewThemes = `-- name: ListPendingReviewThemes :many
SELECT t.id, t.creator_id, t.title, t.slug, t.description, t.cover_image, t.min_players, t.max_players, t.duration_min, t.price, t.status, t.config_json, t.version, t.published_at, t.created_at, t.updated_at, t.coin_price, t.review_note, t.reviewed_at, t.reviewed_by, u.nickname AS creator_name
FROM themes t
JOIN users u ON t.creator_id = u.id
WHERE t.status = 'PENDING_REVIEW'
ORDER BY t.updated_at ASC
`

type ListPendingReviewThemesRow struct {
	ID          uuid.UUID          `json:"id"`
	CreatorID   uuid.UUID          `json:"creator_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CoverImage  pgtype.Text        `json:"cover_image"`
	MinPlayers  int32              `json:"min_players"`
	MaxPlayers  int32              `json:"max_players"`
	DurationMin int32              `json:"duration_min"`
	Price       int32              `json:"price"`
	Status      string             `json:"status"`
	ConfigJson  json.RawMessage    `json:"config_json"`
	Version     int32              `json:"version"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	CoinPrice   int32              `json:"coin_price"`
	ReviewNote  pgtype.Text        `json:"review_note"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy  pgtype.UUID        `json:"reviewed_by"`
	CreatorName string             `json:"creator_name"`
}

func (q *Queries) ListPendingReviewThemes(ctx context.Context) ([]ListPendingReviewThemesRow, error) {
	rows, err := q.db.Query(ctx, listPendingReviewThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingReviewThemesRow{}
	for rows.Next() {
		var i ListPendingReviewThemesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.DurationMin,
			&i.Price,
			&i.Status,
			&i.ConfigJson,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoinPrice,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectTheme = `-- name: RejectTheme :one
UPDATE themes
SET status      = 'REJECTED',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_note = $3,
    updated_at  = NOW()
WHERE id = $1
  AND status = 'PENDING_REVIEW'
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by
`

type RejectThemeParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
	ReviewNote pgtype.Text `json:"review_note"`
}

func (q *Queries) RejectTheme(ctx context.Context, arg RejectThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, rejectTheme, arg.ID, arg.ReviewedBy, arg.ReviewNote)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const setUserTrustedCreator = `-- name: SetUserTrustedCreator :exec
UPDATE users SET trusted_creator = $2 WHERE id = $1
`

type SetUserTrustedCreatorParams struct {
	ID             uuid.UUID `json:"id"`
	TrustedCreator bool      `json:"trusted_creator"`
}

func (q *Queries) SetUserTrustedCreator(ctx context.Context, arg SetUserTrustedCreatorParams) error {
	_, err := q.db.Exec(ctx, setUserTrustedCreator, arg.ID, arg.TrustedCreator)
	return err
}

const submitThemeForReview = `-- name: SubmitThemeForReview :one
UPDATE themes
SET status      = 'PENDING_REVIEW',
    review_note = NULL,
    reviewed_at = NULL,
    reviewed_by = NULL,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by
`

func (q *Queries) SubmitThemeForReview(ctx context.Context, id uuid.UUID) (Theme, error) {
	row := q.db.QueryRow(ctx, submitThemeForReview, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const suspendTheme = `-- name: SuspendTheme :one
UPDATE themes
SET status      = 'SUSPENDED',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_note = $3,
    updated_at  = NOW()
WHERE id = $1
  AND status IN ('PUBLISHED', 'PENDING_REVIEW')
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by
`

type SuspendThemeParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
	ReviewNote pgtype.Text `json:"review_note"`
}

func (q *Queries) SuspendTheme(ctx context.Context, arg SuspendThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, suspendTheme, arg.ID, arg.ReviewedBy, arg.ReviewNote)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const unpublishTheme = `-- name: UnpublishTheme :one
UPDATE themes
SET status     = 'UNPUBLISHED',
    updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by
`

func (q *Queries) UnpublishTheme(ctx context.Context, id uuid.UUID) (Theme, error) {
	row := q.db.QueryRow(ctx, unpublishTheme, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}
