// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revoke_log.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertRevoke = `-- name: InsertRevoke :one
INSERT INTO revoke_log (user_id, session_id, token_jti, reason, code, revoked_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, session_id, token_jti, revoked_at, reason, code, revoked_by
`

type InsertRevokeParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	TokenJti  pgtype.Text `json:"token_jti"`
	Reason    string      `json:"reason"`
	Code      string      `json:"code"`
	RevokedBy pgtype.UUID `json:"revoked_by"`
}

// Append a revoke entry. user_id is required; session_id / token_jti /
// revoked_by are optional and select the granularity:
//   - (user_id only)              — bans, password changes; whole user.
//   - (user_id, session_id)       — kick a specific WS session.
//   - (user_id, token_jti)        — logout-elsewhere; that token only.
func (q *Queries) InsertRevoke(ctx context.Context, arg InsertRevokeParams) (RevokeLog, error) {
	row := q.db.QueryRow(ctx, insertRevoke,
		arg.UserID,
		arg.SessionID,
		arg.TokenJti,
		arg.Reason,
		arg.Code,
		arg.RevokedBy,
	)
	var i RevokeLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.TokenJti,
		&i.RevokedAt,
		&i.Reason,
		&i.Code,
		&i.RevokedBy,
	)
	return i, err
}

const isSessionRevoked = `-- name: IsSessionRevoked :one
SELECT EXISTS (
    SELECT 1 FROM revoke_log
    WHERE session_id = $1
) AS revoked
`

// Session-precision lookup. Used when a single WS session is kicked
// without invalidating the user's other devices.
func (q *Queries) IsSessionRevoked(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionRevoked, sessionID)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS (
    SELECT 1 FROM revoke_log
    WHERE token_jti = $1
) AS revoked
`

// Token-precision lookup used by auth.identify / auth.resume on
// reconnect. Returns true if the supplied token_jti has any revoke row.
func (q *Queries) IsTokenRevoked(ctx context.Context, tokenJti pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, tokenJti)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const isUserRevokedSince = `-- name: IsUserRevokedSince :one
SELECT EXISTS (
    SELECT 1 FROM revoke_log
    WHERE user_id = $1 AND revoked_at > $2
) AS revoked
`

type IsUserRevokedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	RevokedAt time.Time `json:"revoked_at"`
}

// True if any revoke for user_id is newer than `since`. The WS hub
// middleware passes the connection's auth timestamp as `since` so a
// pre-existing revoke from before login does not nuke the new session.
func (q *Queries) IsUserRevokedSince(ctx context.Context, arg IsUserRevokedSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserRevokedSince, arg.UserID, arg.RevokedAt)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const listRecentRevokesForUser = `-- name: ListRecentRevokesForUser :many
SELECT id, user_id, session_id, token_jti, revoked_at, reason, code, revoked_by FROM revoke_log
WHERE user_id = $1
ORDER BY revoked_at DESC
LIMIT $2
`

type ListRecentRevokesForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

// Newest-first audit lookup for admin dashboards.
func (q *Queries) ListRecentRevokesForUser(ctx context.Context, arg ListRecentRevokesForUserParams) ([]RevokeLog, error) {
	rows, err := q.db.Query(ctx, listRecentRevokesForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeLog{}
	for rows.Next() {
		var i RevokeLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.TokenJti,
			&i.RevokedAt,
			&i.Reason,
			&i.Code,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
