// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRoomPlayer = `-- name: AddRoomPlayer :exec
INSERT INTO room_players (room_id, user_id) VALUES ($1, $2)
`

type AddRoomPlayerParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddRoomPlayer(ctx context.Context, arg AddRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, addRoomPlayer, arg.RoomID, arg.UserID)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (theme_id, host_id, code, max_players, is_private)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, theme_id, host_id, code, status, max_players, is_private, created_at, updated_at
`

type CreateRoomParams struct {
	ThemeID    uuid.UUID `json:"theme_id"`
	HostID     uuid.UUID `json:"host_id"`
	Code       string    `json:"code"`
	MaxPlayers int32     `json:"max_players"`
	IsPrivate  bool      `json:"is_private"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ThemeID,
		arg.HostID,
		arg.Code,
		arg.MaxPlayers,
		arg.IsPrivate,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.HostID,
		&i.Code,
		&i.Status,
		&i.MaxPlayers,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, theme_id, host_id, code, status, max_players, is_private, created_at, updated_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.HostID,
		&i.Code,
		&i.Status,
		&i.MaxPlayers,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, theme_id, host_id, code, status, max_players, is_private, created_at, updated_at FROM rooms WHERE code = $1
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.HostID,
		&i.Code,
		&i.Status,
		&i.MaxPlayers,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomForUpdate = `-- name: GetRoomForUpdate :one
SELECT id, theme_id, host_id, code, status, max_players, is_private, created_at, updated_at FROM rooms WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRoomForUpdate(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomForUpdate, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.HostID,
		&i.Code,
		&i.Status,
		&i.MaxPlayers,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomPlayerCount = `-- name: GetRoomPlayerCount :one
SELECT count(*) FROM room_players WHERE room_id = $1
`

func (q *Queries) GetRoomPlayerCount(ctx context.Context, roomID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRoomPlayerCount, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRoomPlayers = `-- name: GetRoomPlayers :many
SELECT room_id, user_id, character_id, is_ready, joined_at FROM room_players WHERE room_id = $1
`

func (q *Queries) GetRoomPlayers(ctx context.Context, roomID uuid.UUID) ([]RoomPlayer, error) {
	rows, err := q.db.Query(ctx, getRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPlayer{}
	for rows.Next() {
		var i RoomPlayer
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.CharacterID,
			&i.IsReady,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingRooms = `-- name: ListWaitingRooms :many
SELECT id, theme_id, host_id, code, status, max_players, is_private, created_at, updated_at FROM rooms WHERE status = 'WAITING' AND is_private = FALSE ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListWaitingRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWaitingRooms(ctx context.Context, arg ListWaitingRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listWaitingRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.HostID,
			&i.Code,
			&i.Status,
			&i.MaxPlayers,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingRoomsWithCount = `-- name: ListWaitingRoomsWithCount :many
SELECT r.id, r.theme_id, r.host_id, r.code, r.status, r.max_players, r.is_private, r.created_at, r.updated_at, (SELECT count(*) FROM room_players rp WHERE rp.room_id = r.id)::int AS player_count
FROM rooms r
WHERE r.status = 'WAITING' AND r.is_private = FALSE
ORDER BY r.created_at DESC LIMIT $1 OFFSET $2
`

type ListWaitingRoomsWithCountParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWaitingRoomsWithCountRow struct {
	ID          uuid.UUID `json:"id"`
	ThemeID     uuid.UUID `json:"theme_id"`
	HostID      uuid.UUID `json:"host_id"`
	Code        string    `json:"code"`
	Status      string    `json:"status"`
	MaxPlayers  int32     `json:"max_players"`
	IsPrivate   bool      `json:"is_private"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	PlayerCount int32     `json:"player_count"`
}

func (q *Queries) ListWaitingRoomsWithCount(ctx context.Context, arg ListWaitingRoomsWithCountParams) ([]ListWaitingRoomsWithCountRow, error) {
	rows, err := q.db.Query(ctx, listWaitingRoomsWithCount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaitingRoomsWithCountRow{}
	for rows.Next() {
		var i ListWaitingRoomsWithCountRow
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.HostID,
			&i.Code,
			&i.Status,
			&i.MaxPlayers,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomPlayer = `-- name: RemoveRoomPlayer :exec
DELETE FROM room_players WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomPlayerParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoomPlayer(ctx context.Context, arg RemoveRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, removeRoomPlayer, arg.RoomID, arg.UserID)
	return err
}

const setPlayerReady = `-- name: SetPlayerReady :exec
UPDATE room_players SET is_ready = $3 WHERE room_id = $1 AND user_id = $2
`

type SetPlayerReadyParams struct {
	RoomID  uuid.UUID `json:"room_id"`
	UserID  uuid.UUID `json:"user_id"`
	IsReady bool      `json:"is_ready"`
}

func (q *Queries) SetPlayerReady(ctx context.Context, arg SetPlayerReadyParams) error {
	_, err := q.db.Exec(ctx, setPlayerReady, arg.RoomID, arg.UserID, arg.IsReady)
	return err
}

const updateRoomStatus = `-- name: UpdateRoomStatus :exec
UPDATE rooms SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateRoomStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) error {
	_, err := q.db.Exec(ctx, updateRoomStatus, arg.ID, arg.Status)
	return err
}
