// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addSessionEvent = `-- name: AddSessionEvent :one
INSERT INTO session_events (session_id, type, payload) VALUES ($1, $2, $3) RETURNING id, session_id, type, payload, created_at
`

type AddSessionEventParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) AddSessionEvent(ctx context.Context, arg AddSessionEventParams) (SessionEvent, error) {
	row := q.db.QueryRow(ctx, addSessionEvent, arg.SessionID, arg.Type, arg.Payload)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const addSessionPlayer = `-- name: AddSessionPlayer :exec
INSERT INTO session_players (session_id, user_id, character_id) VALUES ($1, $2, $3)
`

type AddSessionPlayerParams struct {
	SessionID   uuid.UUID `json:"session_id"`
	UserID      uuid.UUID `json:"user_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) AddSessionPlayer(ctx context.Context, arg AddSessionPlayerParams) error {
	_, err := q.db.Exec(ctx, addSessionPlayer, arg.SessionID, arg.UserID, arg.CharacterID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO game_sessions (room_id, theme_id) VALUES ($1, $2) RETURNING id, room_id, theme_id, current_phase, phase_index, state_json, started_at, ended_at
`

type CreateSessionParams struct {
	RoomID  uuid.UUID `json:"room_id"`
	ThemeID uuid.UUID `json:"theme_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.RoomID, arg.ThemeID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ThemeID,
		&i.CurrentPhase,
		&i.PhaseIndex,
		&i.StateJson,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endSession = `-- name: EndSession :exec
UPDATE game_sessions SET ended_at = NOW() WHERE id = $1
`

func (q *Queries) EndSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, endSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, room_id, theme_id, current_phase, phase_index, state_json, started_at, ended_at FROM game_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GameSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ThemeID,
		&i.CurrentPhase,
		&i.PhaseIndex,
		&i.StateJson,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getSessionEvents = `-- name: GetSessionEvents :many
SELECT id, session_id, type, payload, created_at FROM session_events WHERE session_id = $1 ORDER BY id
`

func (q *Queries) GetSessionEvents(ctx context.Context, sessionID uuid.UUID) ([]SessionEvent, error) {
	rows, err := q.db.Query(ctx, getSessionEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionPlayers = `-- name: GetSessionPlayers :many
SELECT session_id, user_id, character_id, score, is_alive FROM session_players WHERE session_id = $1
`

func (q *Queries) GetSessionPlayers(ctx context.Context, sessionID uuid.UUID) ([]SessionPlayer, error) {
	rows, err := q.db.Query(ctx, getSessionPlayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPlayer{}
	for rows.Next() {
		var i SessionPlayer
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.CharacterID,
			&i.Score,
			&i.IsAlive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayerAlive = `-- name: SetPlayerAlive :exec
UPDATE session_players SET is_alive = $3 WHERE session_id = $1 AND user_id = $2
`

type SetPlayerAliveParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	IsAlive   bool      `json:"is_alive"`
}

func (q *Queries) SetPlayerAlive(ctx context.Context, arg SetPlayerAliveParams) error {
	_, err := q.db.Exec(ctx, setPlayerAlive, arg.SessionID, arg.UserID, arg.IsAlive)
	return err
}

const updatePlayerScore = `-- name: UpdatePlayerScore :exec
UPDATE session_players SET score = score + $3 WHERE session_id = $1 AND user_id = $2
`

type UpdatePlayerScoreParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	Score     int32     `json:"score"`
}

func (q *Queries) UpdatePlayerScore(ctx context.Context, arg UpdatePlayerScoreParams) error {
	_, err := q.db.Exec(ctx, updatePlayerScore, arg.SessionID, arg.UserID, arg.Score)
	return err
}

const updateSessionPhase = `-- name: UpdateSessionPhase :exec
UPDATE game_sessions SET current_phase = $2, phase_index = $3 WHERE id = $1
`

type UpdateSessionPhaseParams struct {
	ID           uuid.UUID `json:"id"`
	CurrentPhase string    `json:"current_phase"`
	PhaseIndex   int32     `json:"phase_index"`
}

func (q *Queries) UpdateSessionPhase(ctx context.Context, arg UpdateSessionPhaseParams) error {
	_, err := q.db.Exec(ctx, updateSessionPhase, arg.ID, arg.CurrentPhase, arg.PhaseIndex)
	return err
}

const updateSessionState = `-- name: UpdateSessionState :exec
UPDATE game_sessions SET state_json = $2 WHERE id = $1
`

type UpdateSessionStateParams struct {
	ID        uuid.UUID       `json:"id"`
	StateJson json.RawMessage `json:"state_json"`
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error {
	_, err := q.db.Exec(ctx, updateSessionState, arg.ID, arg.StateJson)
	return err
}
