// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: story_infos.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStoryInfo = `-- name: CreateStoryInfo :one
INSERT INTO story_infos (
  theme_id,
  title,
  body,
  content_format,
  image_media_id,
  related_character_ids,
  related_clue_ids,
  related_location_ids,
  sort_order
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9
FROM themes t
WHERE t.id = $1 AND t.creator_id = $10
RETURNING id, theme_id, title, body, image_media_id, related_character_ids, related_clue_ids, related_location_ids, sort_order, version, created_at, updated_at, content_format
`

type CreateStoryInfoParams struct {
	ThemeID             uuid.UUID       `json:"theme_id"`
	Title               string          `json:"title"`
	Body                string          `json:"body"`
	ContentFormat       string          `json:"content_format"`
	ImageMediaID        pgtype.UUID     `json:"image_media_id"`
	RelatedCharacterIds json.RawMessage `json:"related_character_ids"`
	RelatedClueIds      json.RawMessage `json:"related_clue_ids"`
	RelatedLocationIds  json.RawMessage `json:"related_location_ids"`
	SortOrder           int32           `json:"sort_order"`
	CreatorID           uuid.UUID       `json:"creator_id"`
}

func (q *Queries) CreateStoryInfo(ctx context.Context, arg CreateStoryInfoParams) (StoryInfo, error) {
	row := q.db.QueryRow(ctx, createStoryInfo,
		arg.ThemeID,
		arg.Title,
		arg.Body,
		arg.ContentFormat,
		arg.ImageMediaID,
		arg.RelatedCharacterIds,
		arg.RelatedClueIds,
		arg.RelatedLocationIds,
		arg.SortOrder,
		arg.CreatorID,
	)
	var i StoryInfo
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Title,
		&i.Body,
		&i.ImageMediaID,
		&i.RelatedCharacterIds,
		&i.RelatedClueIds,
		&i.RelatedLocationIds,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentFormat,
	)
	return i, err
}

const createStoryInfoMediaRef = `-- name: CreateStoryInfoMediaRef :exec
INSERT INTO story_info_media_refs (
  story_info_id,
  media_id,
  usage,
  sort_order
)
VALUES ($1, $2, $3, $4)
`

type CreateStoryInfoMediaRefParams struct {
	StoryInfoID uuid.UUID `json:"story_info_id"`
	MediaID     uuid.UUID `json:"media_id"`
	Usage       string    `json:"usage"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) CreateStoryInfoMediaRef(ctx context.Context, arg CreateStoryInfoMediaRefParams) error {
	_, err := q.db.Exec(ctx, createStoryInfoMediaRef,
		arg.StoryInfoID,
		arg.MediaID,
		arg.Usage,
		arg.SortOrder,
	)
	return err
}

const deleteStoryInfoMediaRefs = `-- name: DeleteStoryInfoMediaRefs :exec
DELETE FROM story_info_media_refs
WHERE story_info_id = $1
`

func (q *Queries) DeleteStoryInfoMediaRefs(ctx context.Context, storyInfoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStoryInfoMediaRefs, storyInfoID)
	return err
}

const deleteStoryInfoWithOwner = `-- name: DeleteStoryInfoWithOwner :one
DELETE FROM story_infos si USING themes t
WHERE si.id = $1 AND si.theme_id = t.id AND t.creator_id = $2
RETURNING si.theme_id
`

type DeleteStoryInfoWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteStoryInfoWithOwner(ctx context.Context, arg DeleteStoryInfoWithOwnerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteStoryInfoWithOwner, arg.ID, arg.CreatorID)
	var theme_id uuid.UUID
	err := row.Scan(&theme_id)
	return theme_id, err
}

const getStoryInfoWithOwner = `-- name: GetStoryInfoWithOwner :one
SELECT si.id, si.theme_id, si.title, si.body, si.image_media_id, si.related_character_ids, si.related_clue_ids, si.related_location_ids, si.sort_order, si.version, si.created_at, si.updated_at, si.content_format FROM story_infos si
JOIN themes t ON si.theme_id = t.id
WHERE si.id = $1 AND t.creator_id = $2
`

type GetStoryInfoWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) GetStoryInfoWithOwner(ctx context.Context, arg GetStoryInfoWithOwnerParams) (StoryInfo, error) {
	row := q.db.QueryRow(ctx, getStoryInfoWithOwner, arg.ID, arg.CreatorID)
	var i StoryInfo
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Title,
		&i.Body,
		&i.ImageMediaID,
		&i.RelatedCharacterIds,
		&i.RelatedClueIds,
		&i.RelatedLocationIds,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentFormat,
	)
	return i, err
}

const listStoryInfosByTheme = `-- name: ListStoryInfosByTheme :many

SELECT si.id, si.theme_id, si.title, si.body, si.image_media_id, si.related_character_ids, si.related_clue_ids, si.related_location_ids, si.sort_order, si.version, si.created_at, si.updated_at, si.content_format FROM story_infos si
JOIN themes t ON si.theme_id = t.id
WHERE si.theme_id = $1 AND t.creator_id = $2
ORDER BY si.sort_order, si.created_at
`

type ListStoryInfosByThemeParams struct {
	ThemeID   uuid.UUID `json:"theme_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

// ============================================================
// Story Infos
// ============================================================
func (q *Queries) ListStoryInfosByTheme(ctx context.Context, arg ListStoryInfosByThemeParams) ([]StoryInfo, error) {
	rows, err := q.db.Query(ctx, listStoryInfosByTheme, arg.ThemeID, arg.CreatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryInfo{}
	for rows.Next() {
		var i StoryInfo
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Title,
			&i.Body,
			&i.ImageMediaID,
			&i.RelatedCharacterIds,
			&i.RelatedClueIds,
			&i.RelatedLocationIds,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoryInfo = `-- name: UpdateStoryInfo :one
UPDATE story_infos
SET title = $2,
    body = $3,
    content_format = $4,
    image_media_id = $5,
    related_character_ids = $6,
    related_clue_ids = $7,
    related_location_ids = $8,
    sort_order = $9,
    version = version + 1,
    updated_at = NOW()
FROM themes t
WHERE story_infos.id = $1
  AND story_infos.theme_id = t.id
  AND t.creator_id = $11
  AND story_infos.version = $10
RETURNING story_infos.id, story_infos.theme_id, story_infos.title, story_infos.body, story_infos.image_media_id, story_infos.related_character_ids, story_infos.related_clue_ids, story_infos.related_location_ids, story_infos.sort_order, story_infos.version, story_infos.created_at, story_infos.updated_at, story_infos.content_format
`

type UpdateStoryInfoParams struct {
	ID                  uuid.UUID       `json:"id"`
	Title               string          `json:"title"`
	Body                string          `json:"body"`
	ContentFormat       string          `json:"content_format"`
	ImageMediaID        pgtype.UUID     `json:"image_media_id"`
	RelatedCharacterIds json.RawMessage `json:"related_character_ids"`
	RelatedClueIds      json.RawMessage `json:"related_clue_ids"`
	RelatedLocationIds  json.RawMessage `json:"related_location_ids"`
	SortOrder           int32           `json:"sort_order"`
	Version             int32           `json:"version"`
	CreatorID           uuid.UUID       `json:"creator_id"`
}

func (q *Queries) UpdateStoryInfo(ctx context.Context, arg UpdateStoryInfoParams) (StoryInfo, error) {
	row := q.db.QueryRow(ctx, updateStoryInfo,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.ContentFormat,
		arg.ImageMediaID,
		arg.RelatedCharacterIds,
		arg.RelatedClueIds,
		arg.RelatedLocationIds,
		arg.SortOrder,
		arg.Version,
		arg.CreatorID,
	)
	var i StoryInfo
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Title,
		&i.Body,
		&i.ImageMediaID,
		&i.RelatedCharacterIds,
		&i.RelatedClueIds,
		&i.RelatedLocationIds,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentFormat,
	)
	return i, err
}
