// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: story_infos.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStoryInfo = `-- name: CreateStoryInfo :one
INSERT INTO story_infos (
  theme_id,
  title,
  body,
  image_media_id,
  related_character_ids,
  related_clue_ids,
  related_location_ids,
  sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, theme_id, title, body, image_media_id, related_character_ids, related_clue_ids, related_location_ids, sort_order, version, created_at, updated_at
`

type CreateStoryInfoParams struct {
	ThemeID             uuid.UUID       `json:"theme_id"`
	Title               string          `json:"title"`
	Body                string          `json:"body"`
	ImageMediaID        pgtype.UUID     `json:"image_media_id"`
	RelatedCharacterIds json.RawMessage `json:"related_character_ids"`
	RelatedClueIds      json.RawMessage `json:"related_clue_ids"`
	RelatedLocationIds  json.RawMessage `json:"related_location_ids"`
	SortOrder           int32           `json:"sort_order"`
}

func (q *Queries) CreateStoryInfo(ctx context.Context, arg CreateStoryInfoParams) (StoryInfo, error) {
	row := q.db.QueryRow(ctx, createStoryInfo,
		arg.ThemeID,
		arg.Title,
		arg.Body,
		arg.ImageMediaID,
		arg.RelatedCharacterIds,
		arg.RelatedClueIds,
		arg.RelatedLocationIds,
		arg.SortOrder,
	)
	var i StoryInfo
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Title,
		&i.Body,
		&i.ImageMediaID,
		&i.RelatedCharacterIds,
		&i.RelatedClueIds,
		&i.RelatedLocationIds,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStoryInfoWithOwner = `-- name: DeleteStoryInfoWithOwner :execrows
DELETE FROM story_infos si USING themes t
WHERE si.id = $1 AND si.theme_id = t.id AND t.creator_id = $2
`

type DeleteStoryInfoWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteStoryInfoWithOwner(ctx context.Context, arg DeleteStoryInfoWithOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStoryInfoWithOwner, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStoryInfoWithOwner = `-- name: GetStoryInfoWithOwner :one
SELECT si.id, si.theme_id, si.title, si.body, si.image_media_id, si.related_character_ids, si.related_clue_ids, si.related_location_ids, si.sort_order, si.version, si.created_at, si.updated_at FROM story_infos si
JOIN themes t ON si.theme_id = t.id
WHERE si.id = $1 AND t.creator_id = $2
`

type GetStoryInfoWithOwnerParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) GetStoryInfoWithOwner(ctx context.Context, arg GetStoryInfoWithOwnerParams) (StoryInfo, error) {
	row := q.db.QueryRow(ctx, getStoryInfoWithOwner, arg.ID, arg.CreatorID)
	var i StoryInfo
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Title,
		&i.Body,
		&i.ImageMediaID,
		&i.RelatedCharacterIds,
		&i.RelatedClueIds,
		&i.RelatedLocationIds,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoryInfosByTheme = `-- name: ListStoryInfosByTheme :many

SELECT id, theme_id, title, body, image_media_id, related_character_ids, related_clue_ids, related_location_ids, sort_order, version, created_at, updated_at FROM story_infos WHERE theme_id = $1 ORDER BY sort_order, created_at
`

// ============================================================
// Story Infos
// ============================================================
func (q *Queries) ListStoryInfosByTheme(ctx context.Context, themeID uuid.UUID) ([]StoryInfo, error) {
	rows, err := q.db.Query(ctx, listStoryInfosByTheme, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryInfo{}
	for rows.Next() {
		var i StoryInfo
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Title,
			&i.Body,
			&i.ImageMediaID,
			&i.RelatedCharacterIds,
			&i.RelatedClueIds,
			&i.RelatedLocationIds,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoryInfo = `-- name: UpdateStoryInfo :one
UPDATE story_infos
SET title = $2,
    body = $3,
    image_media_id = $4,
    related_character_ids = $5,
    related_clue_ids = $6,
    related_location_ids = $7,
    sort_order = $8,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND version = $9
RETURNING id, theme_id, title, body, image_media_id, related_character_ids, related_clue_ids, related_location_ids, sort_order, version, created_at, updated_at
`

type UpdateStoryInfoParams struct {
	ID                  uuid.UUID       `json:"id"`
	Title               string          `json:"title"`
	Body                string          `json:"body"`
	ImageMediaID        pgtype.UUID     `json:"image_media_id"`
	RelatedCharacterIds json.RawMessage `json:"related_character_ids"`
	RelatedClueIds      json.RawMessage `json:"related_clue_ids"`
	RelatedLocationIds  json.RawMessage `json:"related_location_ids"`
	SortOrder           int32           `json:"sort_order"`
	Version             int32           `json:"version"`
}

func (q *Queries) UpdateStoryInfo(ctx context.Context, arg UpdateStoryInfoParams) (StoryInfo, error) {
	row := q.db.QueryRow(ctx, updateStoryInfo,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.ImageMediaID,
		arg.RelatedCharacterIds,
		arg.RelatedClueIds,
		arg.RelatedLocationIds,
		arg.SortOrder,
		arg.Version,
	)
	var i StoryInfo
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Title,
		&i.Body,
		&i.ImageMediaID,
		&i.RelatedCharacterIds,
		&i.RelatedClueIds,
		&i.RelatedLocationIds,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
