// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: themes.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countThemeCharacters = `-- name: CountThemeCharacters :one
SELECT count(*) FROM theme_characters WHERE theme_id = $1
`

func (q *Queries) CountThemeCharacters(ctx context.Context, themeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countThemeCharacters, themeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, coin_price, config_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id
`

type CreateThemeParams struct {
	CreatorID   uuid.UUID       `json:"creator_id"`
	Title       string          `json:"title"`
	Slug        string          `json:"slug"`
	Description pgtype.Text     `json:"description"`
	CoverImage  pgtype.Text     `json:"cover_image"`
	MinPlayers  int32           `json:"min_players"`
	MaxPlayers  int32           `json:"max_players"`
	DurationMin int32           `json:"duration_min"`
	Price       int32           `json:"price"`
	CoinPrice   int32           `json:"coin_price"`
	ConfigJson  json.RawMessage `json:"config_json"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme,
		arg.CreatorID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.CoverImage,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.DurationMin,
		arg.Price,
		arg.CoinPrice,
		arg.ConfigJson,
	)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CoverImageMediaID,
	)
	return i, err
}

const createThemeCharacter = `-- name: CreateThemeCharacter :one
INSERT INTO theme_characters (
  theme_id, name, description, image_url, is_culprit, mystery_role, sort_order,
  is_playable, show_in_intro, can_speak_in_reading, is_voting_candidate,
  endcard_title, endcard_body, endcard_image_url, image_media_id, endcard_image_media_id, alias_rules
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, theme_id, name, description, image_url, is_culprit, sort_order, mystery_role, is_playable, show_in_intro, can_speak_in_reading, is_voting_candidate, endcard_title, endcard_body, endcard_image_url, alias_rules, image_media_id, endcard_image_media_id
`

type CreateThemeCharacterParams struct {
	ThemeID             uuid.UUID       `json:"theme_id"`
	Name                string          `json:"name"`
	Description         pgtype.Text     `json:"description"`
	ImageUrl            pgtype.Text     `json:"image_url"`
	IsCulprit           bool            `json:"is_culprit"`
	MysteryRole         string          `json:"mystery_role"`
	SortOrder           int32           `json:"sort_order"`
	IsPlayable          bool            `json:"is_playable"`
	ShowInIntro         bool            `json:"show_in_intro"`
	CanSpeakInReading   bool            `json:"can_speak_in_reading"`
	IsVotingCandidate   bool            `json:"is_voting_candidate"`
	EndcardTitle        pgtype.Text     `json:"endcard_title"`
	EndcardBody         pgtype.Text     `json:"endcard_body"`
	EndcardImageUrl     pgtype.Text     `json:"endcard_image_url"`
	ImageMediaID        pgtype.UUID     `json:"image_media_id"`
	EndcardImageMediaID pgtype.UUID     `json:"endcard_image_media_id"`
	AliasRules          json.RawMessage `json:"alias_rules"`
}

func (q *Queries) CreateThemeCharacter(ctx context.Context, arg CreateThemeCharacterParams) (ThemeCharacter, error) {
	row := q.db.QueryRow(ctx, createThemeCharacter,
		arg.ThemeID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.IsCulprit,
		arg.MysteryRole,
		arg.SortOrder,
		arg.IsPlayable,
		arg.ShowInIntro,
		arg.CanSpeakInReading,
		arg.IsVotingCandidate,
		arg.EndcardTitle,
		arg.EndcardBody,
		arg.EndcardImageUrl,
		arg.ImageMediaID,
		arg.EndcardImageMediaID,
		arg.AliasRules,
	)
	var i ThemeCharacter
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsCulprit,
		&i.SortOrder,
		&i.MysteryRole,
		&i.IsPlayable,
		&i.ShowInIntro,
		&i.CanSpeakInReading,
		&i.IsVotingCandidate,
		&i.EndcardTitle,
		&i.EndcardBody,
		&i.EndcardImageUrl,
		&i.AliasRules,
		&i.ImageMediaID,
		&i.EndcardImageMediaID,
	)
	return i, err
}

const deleteTheme = `-- name: DeleteTheme :exec
DELETE FROM themes WHERE id = $1
`

func (q *Queries) DeleteTheme(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTheme, id)
	return err
}

const deleteThemeCharacter = `-- name: DeleteThemeCharacter :exec
DELETE FROM theme_characters WHERE id = $1
`

func (q *Queries) DeleteThemeCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteThemeCharacter, id)
	return err
}

const getTheme = `-- name: GetTheme :one
SELECT id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id FROM themes WHERE id = $1
`

func (q *Queries) GetTheme(ctx context.Context, id uuid.UUID) (Theme, error) {
	row := q.db.QueryRow(ctx, getTheme, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CoverImageMediaID,
	)
	return i, err
}

const getThemeBySlug = `-- name: GetThemeBySlug :one
SELECT id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id FROM themes WHERE slug = $1
`

func (q *Queries) GetThemeBySlug(ctx context.Context, slug string) (Theme, error) {
	row := q.db.QueryRow(ctx, getThemeBySlug, slug)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CoverImageMediaID,
	)
	return i, err
}

const getThemeCharacter = `-- name: GetThemeCharacter :one
SELECT id, theme_id, name, description, image_url, is_culprit, sort_order, mystery_role, is_playable, show_in_intro, can_speak_in_reading, is_voting_candidate, endcard_title, endcard_body, endcard_image_url, alias_rules, image_media_id, endcard_image_media_id FROM theme_characters WHERE id = $1
`

func (q *Queries) GetThemeCharacter(ctx context.Context, id uuid.UUID) (ThemeCharacter, error) {
	row := q.db.QueryRow(ctx, getThemeCharacter, id)
	var i ThemeCharacter
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsCulprit,
		&i.SortOrder,
		&i.MysteryRole,
		&i.IsPlayable,
		&i.ShowInIntro,
		&i.CanSpeakInReading,
		&i.IsVotingCandidate,
		&i.EndcardTitle,
		&i.EndcardBody,
		&i.EndcardImageUrl,
		&i.AliasRules,
		&i.ImageMediaID,
		&i.EndcardImageMediaID,
	)
	return i, err
}

const getThemeCharacters = `-- name: GetThemeCharacters :many
SELECT id, theme_id, name, description, image_url, is_culprit, sort_order, mystery_role, is_playable, show_in_intro, can_speak_in_reading, is_voting_candidate, endcard_title, endcard_body, endcard_image_url, alias_rules, image_media_id, endcard_image_media_id FROM theme_characters WHERE theme_id = $1 ORDER BY sort_order
`

func (q *Queries) GetThemeCharacters(ctx context.Context, themeID uuid.UUID) ([]ThemeCharacter, error) {
	rows, err := q.db.Query(ctx, getThemeCharacters, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemeCharacter{}
	for rows.Next() {
		var i ThemeCharacter
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.IsCulprit,
			&i.SortOrder,
			&i.MysteryRole,
			&i.IsPlayable,
			&i.ShowInIntro,
			&i.CanSpeakInReading,
			&i.IsVotingCandidate,
			&i.EndcardTitle,
			&i.EndcardBody,
			&i.EndcardImageUrl,
			&i.AliasRules,
			&i.ImageMediaID,
			&i.EndcardImageMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRooms = `-- name: ListAllRooms :many
SELECT id, theme_id, host_id, code, status, max_players, is_private, created_at, updated_at FROM rooms ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllRooms(ctx context.Context, arg ListAllRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listAllRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.HostID,
			&i.Code,
			&i.Status,
			&i.MaxPlayers,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllThemes = `-- name: ListAllThemes :many
SELECT id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id FROM themes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllThemesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllThemes(ctx context.Context, arg ListAllThemesParams) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listAllThemes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theme{}
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.DurationMin,
			&i.Price,
			&i.Status,
			&i.ConfigJson,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoinPrice,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.CoverImageMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedThemes = `-- name: ListPublishedThemes :many
SELECT id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id FROM themes WHERE status = 'PUBLISHED' ORDER BY published_at DESC LIMIT $1 OFFSET $2
`

type ListPublishedThemesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublishedThemes(ctx context.Context, arg ListPublishedThemesParams) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listPublishedThemes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theme{}
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverImage,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.DurationMin,
			&i.Price,
			&i.Status,
			&i.ConfigJson,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoinPrice,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.CoverImageMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemesByCreator = `-- name: ListThemesByCreator :many
SELECT id, title, status, min_players, max_players, coin_price, version, created_at
FROM themes WHERE creator_id = $1 ORDER BY created_at DESC
`

type ListThemesByCreatorRow struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	Status     string    `json:"status"`
	MinPlayers int32     `json:"min_players"`
	MaxPlayers int32     `json:"max_players"`
	CoinPrice  int32     `json:"coin_price"`
	Version    int32     `json:"version"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListThemesByCreator(ctx context.Context, creatorID uuid.UUID) ([]ListThemesByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listThemesByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThemesByCreatorRow{}
	for rows.Next() {
		var i ListThemesByCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.CoinPrice,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTheme = `-- name: UpdateTheme :one
UPDATE themes SET title = $2, slug = $3, description = $4, cover_image = $5, cover_image_media_id = $6,
  min_players = $7, max_players = $8, duration_min = $9, price = $10, coin_price = $11,
  version = version + 1, updated_at = NOW()
WHERE id = $1 AND version = $12
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id
`

type UpdateThemeParams struct {
	ID                uuid.UUID   `json:"id"`
	Title             string      `json:"title"`
	Slug              string      `json:"slug"`
	Description       pgtype.Text `json:"description"`
	CoverImage        pgtype.Text `json:"cover_image"`
	CoverImageMediaID pgtype.UUID `json:"cover_image_media_id"`
	MinPlayers        int32       `json:"min_players"`
	MaxPlayers        int32       `json:"max_players"`
	DurationMin       int32       `json:"duration_min"`
	Price             int32       `json:"price"`
	CoinPrice         int32       `json:"coin_price"`
	Version           int32       `json:"version"`
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateTheme,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.CoverImage,
		arg.CoverImageMediaID,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.DurationMin,
		arg.Price,
		arg.CoinPrice,
		arg.Version,
	)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CoverImageMediaID,
	)
	return i, err
}

const updateThemeCharacter = `-- name: UpdateThemeCharacter :one
UPDATE theme_characters SET
  name = $2,
  description = $3,
  image_url = $4,
  is_culprit = $5,
  mystery_role = $6,
  sort_order = $7,
  is_playable = $8,
  show_in_intro = $9,
  can_speak_in_reading = $10,
  is_voting_candidate = $11,
  endcard_title = $12,
  endcard_body = $13,
  endcard_image_url = $14,
  image_media_id = $15,
  endcard_image_media_id = $16,
  alias_rules = $17
WHERE id = $1
RETURNING id, theme_id, name, description, image_url, is_culprit, sort_order, mystery_role, is_playable, show_in_intro, can_speak_in_reading, is_voting_candidate, endcard_title, endcard_body, endcard_image_url, alias_rules, image_media_id, endcard_image_media_id
`

type UpdateThemeCharacterParams struct {
	ID                  uuid.UUID       `json:"id"`
	Name                string          `json:"name"`
	Description         pgtype.Text     `json:"description"`
	ImageUrl            pgtype.Text     `json:"image_url"`
	IsCulprit           bool            `json:"is_culprit"`
	MysteryRole         string          `json:"mystery_role"`
	SortOrder           int32           `json:"sort_order"`
	IsPlayable          bool            `json:"is_playable"`
	ShowInIntro         bool            `json:"show_in_intro"`
	CanSpeakInReading   bool            `json:"can_speak_in_reading"`
	IsVotingCandidate   bool            `json:"is_voting_candidate"`
	EndcardTitle        pgtype.Text     `json:"endcard_title"`
	EndcardBody         pgtype.Text     `json:"endcard_body"`
	EndcardImageUrl     pgtype.Text     `json:"endcard_image_url"`
	ImageMediaID        pgtype.UUID     `json:"image_media_id"`
	EndcardImageMediaID pgtype.UUID     `json:"endcard_image_media_id"`
	AliasRules          json.RawMessage `json:"alias_rules"`
}

func (q *Queries) UpdateThemeCharacter(ctx context.Context, arg UpdateThemeCharacterParams) (ThemeCharacter, error) {
	row := q.db.QueryRow(ctx, updateThemeCharacter,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.IsCulprit,
		arg.MysteryRole,
		arg.SortOrder,
		arg.IsPlayable,
		arg.ShowInIntro,
		arg.CanSpeakInReading,
		arg.IsVotingCandidate,
		arg.EndcardTitle,
		arg.EndcardBody,
		arg.EndcardImageUrl,
		arg.ImageMediaID,
		arg.EndcardImageMediaID,
		arg.AliasRules,
	)
	var i ThemeCharacter
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsCulprit,
		&i.SortOrder,
		&i.MysteryRole,
		&i.IsPlayable,
		&i.ShowInIntro,
		&i.CanSpeakInReading,
		&i.IsVotingCandidate,
		&i.EndcardTitle,
		&i.EndcardBody,
		&i.EndcardImageUrl,
		&i.AliasRules,
		&i.ImageMediaID,
		&i.EndcardImageMediaID,
	)
	return i, err
}

const updateThemeConfigJson = `-- name: UpdateThemeConfigJson :one
UPDATE themes SET config_json = $2, version = version + 1, updated_at = NOW()
WHERE id = $1 AND version = $3
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id
`

type UpdateThemeConfigJsonParams struct {
	ID         uuid.UUID       `json:"id"`
	ConfigJson json.RawMessage `json:"config_json"`
	Version    int32           `json:"version"`
}

func (q *Queries) UpdateThemeConfigJson(ctx context.Context, arg UpdateThemeConfigJsonParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateThemeConfigJson, arg.ID, arg.ConfigJson, arg.Version)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CoverImageMediaID,
	)
	return i, err
}

const updateThemeConfigJsonWithOwner = `-- name: UpdateThemeConfigJsonWithOwner :one
UPDATE themes SET config_json = $3, version = version + 1, updated_at = NOW()
WHERE id = $1 AND creator_id = $2
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id
`

type UpdateThemeConfigJsonWithOwnerParams struct {
	ID         uuid.UUID       `json:"id"`
	CreatorID  uuid.UUID       `json:"creator_id"`
	ConfigJson json.RawMessage `json:"config_json"`
}

func (q *Queries) UpdateThemeConfigJsonWithOwner(ctx context.Context, arg UpdateThemeConfigJsonWithOwnerParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateThemeConfigJsonWithOwner, arg.ID, arg.CreatorID, arg.ConfigJson)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CoverImageMediaID,
	)
	return i, err
}

const updateThemeCoverImage = `-- name: UpdateThemeCoverImage :exec
UPDATE themes SET cover_image = $2, cover_image_media_id = NULL, updated_at = NOW() WHERE id = $1
`

type UpdateThemeCoverImageParams struct {
	ID         uuid.UUID   `json:"id"`
	CoverImage pgtype.Text `json:"cover_image"`
}

func (q *Queries) UpdateThemeCoverImage(ctx context.Context, arg UpdateThemeCoverImageParams) error {
	_, err := q.db.Exec(ctx, updateThemeCoverImage, arg.ID, arg.CoverImage)
	return err
}

const updateThemeStatus = `-- name: UpdateThemeStatus :one
UPDATE themes SET status = $2, published_at = CASE WHEN $2 = 'PUBLISHED' THEN NOW() ELSE published_at END, updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, title, slug, description, cover_image, min_players, max_players, duration_min, price, status, config_json, version, published_at, created_at, updated_at, coin_price, review_note, reviewed_at, reviewed_by, cover_image_media_id
`

type UpdateThemeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateThemeStatus(ctx context.Context, arg UpdateThemeStatusParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateThemeStatus, arg.ID, arg.Status)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverImage,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.DurationMin,
		&i.Price,
		&i.Status,
		&i.ConfigJson,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoinPrice,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CoverImageMediaID,
	)
	return i, err
}
