// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (nickname, email, avatar_url, provider, provider_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nickname, email, avatar_url, role, provider, provider_id, coin_balance, coin_balance_base, coin_balance_bonus, created_at, updated_at
`

type CreateUserParams struct {
	Nickname   string      `json:"nickname"`
	Email      pgtype.Text `json:"email"`
	AvatarUrl  pgtype.Text `json:"avatar_url"`
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Nickname,
		arg.Email,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CoinBalance,
		&i.CoinBalanceBase,
		&i.CoinBalanceBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, nickname, email, avatar_url, role, provider, provider_id, coin_balance, coin_balance_base, coin_balance_bonus, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CoinBalance,
		&i.CoinBalanceBase,
		&i.CoinBalanceBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, nickname, email, avatar_url, role, provider, provider_id, coin_balance, coin_balance_base, coin_balance_bonus, created_at, updated_at FROM users WHERE provider = $1 AND provider_id = $2
`

type GetUserByProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProvider, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CoinBalance,
		&i.CoinBalanceBase,
		&i.CoinBalanceBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, nickname, email, avatar_url, role, provider, provider_id, coin_balance, coin_balance_base, coin_balance_bonus, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Email,
			&i.AvatarUrl,
			&i.Role,
			&i.Provider,
			&i.ProviderID,
			&i.CoinBalance,
			&i.CoinBalanceBase,
			&i.CoinBalanceBonus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoinBalance = `-- name: UpdateCoinBalance :one
UPDATE users SET coin_balance = coin_balance + $2, updated_at = NOW()
WHERE id = $1 AND coin_balance + $2 >= 0
RETURNING id, nickname, email, avatar_url, role, provider, provider_id, coin_balance, coin_balance_base, coin_balance_bonus, created_at, updated_at
`

type UpdateCoinBalanceParams struct {
	ID          uuid.UUID `json:"id"`
	CoinBalance int64     `json:"coin_balance"`
}

func (q *Queries) UpdateCoinBalance(ctx context.Context, arg UpdateCoinBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, updateCoinBalance, arg.ID, arg.CoinBalance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CoinBalance,
		&i.CoinBalanceBase,
		&i.CoinBalanceBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET nickname = $2, avatar_url = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, nickname, email, avatar_url, role, provider, provider_id, coin_balance, coin_balance_base, coin_balance_bonus, created_at, updated_at
`

type UpdateUserParams struct {
	ID        uuid.UUID   `json:"id"`
	Nickname  string      `json:"nickname"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Nickname, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CoinBalance,
		&i.CoinBalanceBase,
		&i.CoinBalanceBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, nickname, email, avatar_url, role, provider, provider_id, coin_balance, coin_balance_base, coin_balance_bonus, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CoinBalance,
		&i.CoinBalanceBase,
		&i.CoinBalanceBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
