// Code generated by MockGen. DO NOT EDIT.
// Source: story_info_service.go
//
// Generated by this command:
//
//	mockgen -destination=mock_story_info_service_test.go -package=editor -source=story_info_service.go StoryInfoService
//

// Package editor is a generated GoMock package.
package editor

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	db "github.com/mmp-platform/server/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockstoryInfoQueries is a mock of storyInfoQueries interface.
type MockstoryInfoQueries struct {
	ctrl     *gomock.Controller
	recorder *MockstoryInfoQueriesMockRecorder
	isgomock struct{}
}

// MockstoryInfoQueriesMockRecorder is the mock recorder for MockstoryInfoQueries.
type MockstoryInfoQueriesMockRecorder struct {
	mock *MockstoryInfoQueries
}

// NewMockstoryInfoQueries creates a new mock instance.
func NewMockstoryInfoQueries(ctrl *gomock.Controller) *MockstoryInfoQueries {
	mock := &MockstoryInfoQueries{ctrl: ctrl}
	mock.recorder = &MockstoryInfoQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstoryInfoQueries) EXPECT() *MockstoryInfoQueriesMockRecorder {
	return m.recorder
}

// CreateStoryInfo mocks base method.
func (m *MockstoryInfoQueries) CreateStoryInfo(ctx context.Context, arg db.CreateStoryInfoParams) (db.StoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoryInfo", ctx, arg)
	ret0, _ := ret[0].(db.StoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoryInfo indicates an expected call of CreateStoryInfo.
func (mr *MockstoryInfoQueriesMockRecorder) CreateStoryInfo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoryInfo", reflect.TypeOf((*MockstoryInfoQueries)(nil).CreateStoryInfo), ctx, arg)
}

// DeleteStoryInfoWithOwner mocks base method.
func (m *MockstoryInfoQueries) DeleteStoryInfoWithOwner(ctx context.Context, arg db.DeleteStoryInfoWithOwnerParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoryInfoWithOwner", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStoryInfoWithOwner indicates an expected call of DeleteStoryInfoWithOwner.
func (mr *MockstoryInfoQueriesMockRecorder) DeleteStoryInfoWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoryInfoWithOwner", reflect.TypeOf((*MockstoryInfoQueries)(nil).DeleteStoryInfoWithOwner), ctx, arg)
}

// GetClue mocks base method.
func (m *MockstoryInfoQueries) GetClue(ctx context.Context, id uuid.UUID) (db.ThemeClue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClue", ctx, id)
	ret0, _ := ret[0].(db.ThemeClue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClue indicates an expected call of GetClue.
func (mr *MockstoryInfoQueriesMockRecorder) GetClue(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClue", reflect.TypeOf((*MockstoryInfoQueries)(nil).GetClue), ctx, id)
}

// GetLocation mocks base method.
func (m *MockstoryInfoQueries) GetLocation(ctx context.Context, id uuid.UUID) (db.ThemeLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocation", ctx, id)
	ret0, _ := ret[0].(db.ThemeLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocation indicates an expected call of GetLocation.
func (mr *MockstoryInfoQueriesMockRecorder) GetLocation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocation", reflect.TypeOf((*MockstoryInfoQueries)(nil).GetLocation), ctx, id)
}

// GetMedia mocks base method.
func (m *MockstoryInfoQueries) GetMedia(ctx context.Context, id uuid.UUID) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedia", ctx, id)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedia indicates an expected call of GetMedia.
func (mr *MockstoryInfoQueriesMockRecorder) GetMedia(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedia", reflect.TypeOf((*MockstoryInfoQueries)(nil).GetMedia), ctx, id)
}

// GetStoryInfoWithOwner mocks base method.
func (m *MockstoryInfoQueries) GetStoryInfoWithOwner(ctx context.Context, arg db.GetStoryInfoWithOwnerParams) (db.StoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoryInfoWithOwner", ctx, arg)
	ret0, _ := ret[0].(db.StoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoryInfoWithOwner indicates an expected call of GetStoryInfoWithOwner.
func (mr *MockstoryInfoQueriesMockRecorder) GetStoryInfoWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoryInfoWithOwner", reflect.TypeOf((*MockstoryInfoQueries)(nil).GetStoryInfoWithOwner), ctx, arg)
}

// GetTheme mocks base method.
func (m *MockstoryInfoQueries) GetTheme(ctx context.Context, id uuid.UUID) (db.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", ctx, id)
	ret0, _ := ret[0].(db.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockstoryInfoQueriesMockRecorder) GetTheme(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockstoryInfoQueries)(nil).GetTheme), ctx, id)
}

// GetThemeCharacter mocks base method.
func (m *MockstoryInfoQueries) GetThemeCharacter(ctx context.Context, id uuid.UUID) (db.ThemeCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeCharacter", ctx, id)
	ret0, _ := ret[0].(db.ThemeCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeCharacter indicates an expected call of GetThemeCharacter.
func (mr *MockstoryInfoQueriesMockRecorder) GetThemeCharacter(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeCharacter", reflect.TypeOf((*MockstoryInfoQueries)(nil).GetThemeCharacter), ctx, id)
}

// ListStoryInfosByTheme mocks base method.
func (m *MockstoryInfoQueries) ListStoryInfosByTheme(ctx context.Context, arg db.ListStoryInfosByThemeParams) ([]db.StoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoryInfosByTheme", ctx, arg)
	ret0, _ := ret[0].([]db.StoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoryInfosByTheme indicates an expected call of ListStoryInfosByTheme.
func (mr *MockstoryInfoQueriesMockRecorder) ListStoryInfosByTheme(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoryInfosByTheme", reflect.TypeOf((*MockstoryInfoQueries)(nil).ListStoryInfosByTheme), ctx, arg)
}

// UpdateStoryInfo mocks base method.
func (m *MockstoryInfoQueries) UpdateStoryInfo(ctx context.Context, arg db.UpdateStoryInfoParams) (db.StoryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStoryInfo", ctx, arg)
	ret0, _ := ret[0].(db.StoryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStoryInfo indicates an expected call of UpdateStoryInfo.
func (mr *MockstoryInfoQueriesMockRecorder) UpdateStoryInfo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStoryInfo", reflect.TypeOf((*MockstoryInfoQueries)(nil).UpdateStoryInfo), ctx, arg)
}

// MockStoryInfoService is a mock of StoryInfoService interface.
type MockStoryInfoService struct {
	ctrl     *gomock.Controller
	recorder *MockStoryInfoServiceMockRecorder
	isgomock struct{}
}

// MockStoryInfoServiceMockRecorder is the mock recorder for MockStoryInfoService.
type MockStoryInfoServiceMockRecorder struct {
	mock *MockStoryInfoService
}

// NewMockStoryInfoService creates a new mock instance.
func NewMockStoryInfoService(ctrl *gomock.Controller) *MockStoryInfoService {
	mock := &MockStoryInfoService{ctrl: ctrl}
	mock.recorder = &MockStoryInfoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryInfoService) EXPECT() *MockStoryInfoServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStoryInfoService) Create(ctx context.Context, creatorID, themeID uuid.UUID, req CreateStoryInfoRequest) (*StoryInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*StoryInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStoryInfoServiceMockRecorder) Create(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStoryInfoService)(nil).Create), ctx, creatorID, themeID, req)
}

// Delete mocks base method.
func (m *MockStoryInfoService) Delete(ctx context.Context, creatorID, infoID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, creatorID, infoID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockStoryInfoServiceMockRecorder) Delete(ctx, creatorID, infoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStoryInfoService)(nil).Delete), ctx, creatorID, infoID)
}

// List mocks base method.
func (m *MockStoryInfoService) List(ctx context.Context, creatorID, themeID uuid.UUID) ([]StoryInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, creatorID, themeID)
	ret0, _ := ret[0].([]StoryInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoryInfoServiceMockRecorder) List(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStoryInfoService)(nil).List), ctx, creatorID, themeID)
}

// Update mocks base method.
func (m *MockStoryInfoService) Update(ctx context.Context, creatorID, infoID uuid.UUID, req UpdateStoryInfoRequest) (*StoryInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, creatorID, infoID, req)
	ret0, _ := ret[0].(*StoryInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStoryInfoServiceMockRecorder) Update(ctx, creatorID, infoID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStoryInfoService)(nil).Update), ctx, creatorID, infoID, req)
}
