// Code generated by MockGen. DO NOT EDIT.
// Source: media_service.go
//
// Generated by this command:
//
//	mockgen -destination=mock_media_service_test.go -package=editor -source=media_service.go MediaService
//

// Package editor is a generated GoMock package.
package editor

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	db "github.com/mmp-platform/server/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaService is a mock of MediaService interface.
type MockMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceMockRecorder
	isgomock struct{}
}

// MockMediaServiceMockRecorder is the mock recorder for MockMediaService.
type MockMediaServiceMockRecorder struct {
	mock *MockMediaService
}

// NewMockMediaService creates a new mock instance.
func NewMockMediaService(ctrl *gomock.Controller) *MockMediaService {
	mock := &MockMediaService{ctrl: ctrl}
	mock.recorder = &MockMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaService) EXPECT() *MockMediaServiceMockRecorder {
	return m.recorder
}

// ConfirmReplacementUpload mocks base method.
func (m *MockMediaService) ConfirmReplacementUpload(ctx context.Context, creatorID, mediaID uuid.UUID, req ConfirmUploadRequest) (*MediaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmReplacementUpload", ctx, creatorID, mediaID, req)
	ret0, _ := ret[0].(*MediaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmReplacementUpload indicates an expected call of ConfirmReplacementUpload.
func (mr *MockMediaServiceMockRecorder) ConfirmReplacementUpload(ctx, creatorID, mediaID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmReplacementUpload", reflect.TypeOf((*MockMediaService)(nil).ConfirmReplacementUpload), ctx, creatorID, mediaID, req)
}

// ConfirmUpload mocks base method.
func (m *MockMediaService) ConfirmUpload(ctx context.Context, creatorID, themeID uuid.UUID, req ConfirmUploadRequest) (*MediaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmUpload", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*MediaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmUpload indicates an expected call of ConfirmUpload.
func (mr *MockMediaServiceMockRecorder) ConfirmUpload(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmUpload", reflect.TypeOf((*MockMediaService)(nil).ConfirmUpload), ctx, creatorID, themeID, req)
}

// CreateCategory mocks base method.
func (m *MockMediaService) CreateCategory(ctx context.Context, creatorID, themeID uuid.UUID, req MediaCategoryRequest) (*MediaCategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*MediaCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockMediaServiceMockRecorder) CreateCategory(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockMediaService)(nil).CreateCategory), ctx, creatorID, themeID, req)
}

// CreateYouTube mocks base method.
func (m *MockMediaService) CreateYouTube(ctx context.Context, creatorID, themeID uuid.UUID, req CreateMediaYouTubeRequest) (*MediaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateYouTube", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*MediaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateYouTube indicates an expected call of CreateYouTube.
func (mr *MockMediaServiceMockRecorder) CreateYouTube(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateYouTube", reflect.TypeOf((*MockMediaService)(nil).CreateYouTube), ctx, creatorID, themeID, req)
}

// DeleteCategory mocks base method.
func (m *MockMediaService) DeleteCategory(ctx context.Context, creatorID, categoryID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, creatorID, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockMediaServiceMockRecorder) DeleteCategory(ctx, creatorID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockMediaService)(nil).DeleteCategory), ctx, creatorID, categoryID)
}

// DeleteMedia mocks base method.
func (m *MockMediaService) DeleteMedia(ctx context.Context, creatorID, mediaID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMedia", ctx, creatorID, mediaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMedia indicates an expected call of DeleteMedia.
func (mr *MockMediaServiceMockRecorder) DeleteMedia(ctx, creatorID, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMedia", reflect.TypeOf((*MockMediaService)(nil).DeleteMedia), ctx, creatorID, mediaID)
}

// GetEditorMediaDownloadURL mocks base method.
func (m *MockMediaService) GetEditorMediaDownloadURL(ctx context.Context, creatorID, mediaID uuid.UUID) (*MediaDownloadURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditorMediaDownloadURL", ctx, creatorID, mediaID)
	ret0, _ := ret[0].(*MediaDownloadURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditorMediaDownloadURL indicates an expected call of GetEditorMediaDownloadURL.
func (mr *MockMediaServiceMockRecorder) GetEditorMediaDownloadURL(ctx, creatorID, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditorMediaDownloadURL", reflect.TypeOf((*MockMediaService)(nil).GetEditorMediaDownloadURL), ctx, creatorID, mediaID)
}

// GetMediaPlayURL mocks base method.
func (m *MockMediaService) GetMediaPlayURL(ctx context.Context, sessionID, mediaID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaPlayURL", ctx, sessionID, mediaID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaPlayURL indicates an expected call of GetMediaPlayURL.
func (mr *MockMediaServiceMockRecorder) GetMediaPlayURL(ctx, sessionID, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaPlayURL", reflect.TypeOf((*MockMediaService)(nil).GetMediaPlayURL), ctx, sessionID, mediaID)
}

// ListCategories mocks base method.
func (m *MockMediaService) ListCategories(ctx context.Context, creatorID, themeID uuid.UUID) ([]MediaCategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, creatorID, themeID)
	ret0, _ := ret[0].([]MediaCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockMediaServiceMockRecorder) ListCategories(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockMediaService)(nil).ListCategories), ctx, creatorID, themeID)
}

// ListMedia mocks base method.
func (m *MockMediaService) ListMedia(ctx context.Context, creatorID, themeID uuid.UUID, mediaType string, categoryID *uuid.UUID) ([]MediaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMedia", ctx, creatorID, themeID, mediaType, categoryID)
	ret0, _ := ret[0].([]MediaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMedia indicates an expected call of ListMedia.
func (mr *MockMediaServiceMockRecorder) ListMedia(ctx, creatorID, themeID, mediaType, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMedia", reflect.TypeOf((*MockMediaService)(nil).ListMedia), ctx, creatorID, themeID, mediaType, categoryID)
}

// PreviewDeleteMedia mocks base method.
func (m *MockMediaService) PreviewDeleteMedia(ctx context.Context, creatorID, mediaID uuid.UUID) (*MediaDeletePreviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewDeleteMedia", ctx, creatorID, mediaID)
	ret0, _ := ret[0].(*MediaDeletePreviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewDeleteMedia indicates an expected call of PreviewDeleteMedia.
func (mr *MockMediaServiceMockRecorder) PreviewDeleteMedia(ctx, creatorID, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewDeleteMedia", reflect.TypeOf((*MockMediaService)(nil).PreviewDeleteMedia), ctx, creatorID, mediaID)
}

// RequestReplacementUpload mocks base method.
func (m *MockMediaService) RequestReplacementUpload(ctx context.Context, creatorID, mediaID uuid.UUID, req RequestMediaReplacementUploadRequest) (*UploadURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestReplacementUpload", ctx, creatorID, mediaID, req)
	ret0, _ := ret[0].(*UploadURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestReplacementUpload indicates an expected call of RequestReplacementUpload.
func (mr *MockMediaServiceMockRecorder) RequestReplacementUpload(ctx, creatorID, mediaID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestReplacementUpload", reflect.TypeOf((*MockMediaService)(nil).RequestReplacementUpload), ctx, creatorID, mediaID, req)
}

// RequestUpload mocks base method.
func (m *MockMediaService) RequestUpload(ctx context.Context, creatorID, themeID uuid.UUID, req RequestMediaUploadRequest) (*UploadURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestUpload", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*UploadURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestUpload indicates an expected call of RequestUpload.
func (mr *MockMediaServiceMockRecorder) RequestUpload(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestUpload", reflect.TypeOf((*MockMediaService)(nil).RequestUpload), ctx, creatorID, themeID, req)
}

// ResolveMediaURL mocks base method.
func (m *MockMediaService) ResolveMediaURL(ctx context.Context, sessionID, mediaID uuid.UUID, allowedTypes ...string) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sessionID, mediaID}
	for _, a := range allowedTypes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResolveMediaURL", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveMediaURL indicates an expected call of ResolveMediaURL.
func (mr *MockMediaServiceMockRecorder) ResolveMediaURL(ctx, sessionID, mediaID any, allowedTypes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sessionID, mediaID}, allowedTypes...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveMediaURL", reflect.TypeOf((*MockMediaService)(nil).ResolveMediaURL), varargs...)
}

// UpdateCategory mocks base method.
func (m *MockMediaService) UpdateCategory(ctx context.Context, creatorID, categoryID uuid.UUID, req MediaCategoryRequest) (*MediaCategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, creatorID, categoryID, req)
	ret0, _ := ret[0].(*MediaCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockMediaServiceMockRecorder) UpdateCategory(ctx, creatorID, categoryID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockMediaService)(nil).UpdateCategory), ctx, creatorID, categoryID, req)
}

// UpdateMedia mocks base method.
func (m *MockMediaService) UpdateMedia(ctx context.Context, creatorID, mediaID uuid.UUID, req UpdateMediaRequest) (*MediaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMedia", ctx, creatorID, mediaID, req)
	ret0, _ := ret[0].(*MediaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMedia indicates an expected call of UpdateMedia.
func (mr *MockMediaServiceMockRecorder) UpdateMedia(ctx, creatorID, mediaID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMedia", reflect.TypeOf((*MockMediaService)(nil).UpdateMedia), ctx, creatorID, mediaID, req)
}

// MockmediaQueries is a mock of mediaQueries interface.
type MockmediaQueries struct {
	ctrl     *gomock.Controller
	recorder *MockmediaQueriesMockRecorder
	isgomock struct{}
}

// MockmediaQueriesMockRecorder is the mock recorder for MockmediaQueries.
type MockmediaQueriesMockRecorder struct {
	mock *MockmediaQueries
}

// NewMockmediaQueries creates a new mock instance.
func NewMockmediaQueries(ctrl *gomock.Controller) *MockmediaQueries {
	mock := &MockmediaQueries{ctrl: ctrl}
	mock.recorder = &MockmediaQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmediaQueries) EXPECT() *MockmediaQueriesMockRecorder {
	return m.recorder
}

// ClearMapMediaReferencesWithOwner mocks base method.
func (m *MockmediaQueries) ClearMapMediaReferencesWithOwner(ctx context.Context, arg db.ClearMapMediaReferencesWithOwnerParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearMapMediaReferencesWithOwner", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearMapMediaReferencesWithOwner indicates an expected call of ClearMapMediaReferencesWithOwner.
func (mr *MockmediaQueriesMockRecorder) ClearMapMediaReferencesWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearMapMediaReferencesWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).ClearMapMediaReferencesWithOwner), ctx, arg)
}

// ClearReadingSectionMediaReferencesWithOwner mocks base method.
func (m *MockmediaQueries) ClearReadingSectionMediaReferencesWithOwner(ctx context.Context, arg db.ClearReadingSectionMediaReferencesWithOwnerParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearReadingSectionMediaReferencesWithOwner", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearReadingSectionMediaReferencesWithOwner indicates an expected call of ClearReadingSectionMediaReferencesWithOwner.
func (mr *MockmediaQueriesMockRecorder) ClearReadingSectionMediaReferencesWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearReadingSectionMediaReferencesWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).ClearReadingSectionMediaReferencesWithOwner), ctx, arg)
}

// ClearRoleSheetMediaReferencesWithOwner mocks base method.
func (m *MockmediaQueries) ClearRoleSheetMediaReferencesWithOwner(ctx context.Context, arg db.ClearRoleSheetMediaReferencesWithOwnerParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRoleSheetMediaReferencesWithOwner", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearRoleSheetMediaReferencesWithOwner indicates an expected call of ClearRoleSheetMediaReferencesWithOwner.
func (mr *MockmediaQueriesMockRecorder) ClearRoleSheetMediaReferencesWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRoleSheetMediaReferencesWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).ClearRoleSheetMediaReferencesWithOwner), ctx, arg)
}

// ClearThemeCoverMediaReferencesWithOwner mocks base method.
func (m *MockmediaQueries) ClearThemeCoverMediaReferencesWithOwner(ctx context.Context, arg db.ClearThemeCoverMediaReferencesWithOwnerParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearThemeCoverMediaReferencesWithOwner", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearThemeCoverMediaReferencesWithOwner indicates an expected call of ClearThemeCoverMediaReferencesWithOwner.
func (mr *MockmediaQueriesMockRecorder) ClearThemeCoverMediaReferencesWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearThemeCoverMediaReferencesWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).ClearThemeCoverMediaReferencesWithOwner), ctx, arg)
}

// CountMediaByTheme mocks base method.
func (m *MockmediaQueries) CountMediaByTheme(ctx context.Context, themeID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMediaByTheme", ctx, themeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMediaByTheme indicates an expected call of CountMediaByTheme.
func (mr *MockmediaQueriesMockRecorder) CountMediaByTheme(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMediaByTheme", reflect.TypeOf((*MockmediaQueries)(nil).CountMediaByTheme), ctx, themeID)
}

// CreateMedia mocks base method.
func (m *MockmediaQueries) CreateMedia(ctx context.Context, arg db.CreateMediaParams) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedia", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMedia indicates an expected call of CreateMedia.
func (mr *MockmediaQueriesMockRecorder) CreateMedia(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedia", reflect.TypeOf((*MockmediaQueries)(nil).CreateMedia), ctx, arg)
}

// CreateMediaCategory mocks base method.
func (m *MockmediaQueries) CreateMediaCategory(ctx context.Context, arg db.CreateMediaCategoryParams) (db.ThemeMediaCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMediaCategory", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMediaCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMediaCategory indicates an expected call of CreateMediaCategory.
func (mr *MockmediaQueriesMockRecorder) CreateMediaCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMediaCategory", reflect.TypeOf((*MockmediaQueries)(nil).CreateMediaCategory), ctx, arg)
}

// CreateMediaReplacementUpload mocks base method.
func (m *MockmediaQueries) CreateMediaReplacementUpload(ctx context.Context, arg db.CreateMediaReplacementUploadParams) (db.ThemeMediaReplacementUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMediaReplacementUpload", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMediaReplacementUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMediaReplacementUpload indicates an expected call of CreateMediaReplacementUpload.
func (mr *MockmediaQueriesMockRecorder) CreateMediaReplacementUpload(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMediaReplacementUpload", reflect.TypeOf((*MockmediaQueries)(nil).CreateMediaReplacementUpload), ctx, arg)
}

// DeleteMedia mocks base method.
func (m *MockmediaQueries) DeleteMedia(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMedia", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMedia indicates an expected call of DeleteMedia.
func (mr *MockmediaQueriesMockRecorder) DeleteMedia(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMedia", reflect.TypeOf((*MockmediaQueries)(nil).DeleteMedia), ctx, id)
}

// DeleteMediaCategoryWithOwner mocks base method.
func (m *MockmediaQueries) DeleteMediaCategoryWithOwner(ctx context.Context, arg db.DeleteMediaCategoryWithOwnerParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaCategoryWithOwner", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMediaCategoryWithOwner indicates an expected call of DeleteMediaCategoryWithOwner.
func (mr *MockmediaQueriesMockRecorder) DeleteMediaCategoryWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaCategoryWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).DeleteMediaCategoryWithOwner), ctx, arg)
}

// DeleteMediaReplacementUpload mocks base method.
func (m *MockmediaQueries) DeleteMediaReplacementUpload(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaReplacementUpload", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMediaReplacementUpload indicates an expected call of DeleteMediaReplacementUpload.
func (mr *MockmediaQueriesMockRecorder) DeleteMediaReplacementUpload(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaReplacementUpload", reflect.TypeOf((*MockmediaQueries)(nil).DeleteMediaReplacementUpload), ctx, id)
}

// DeleteMediaWithOwner mocks base method.
func (m *MockmediaQueries) DeleteMediaWithOwner(ctx context.Context, arg db.DeleteMediaWithOwnerParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaWithOwner", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMediaWithOwner indicates an expected call of DeleteMediaWithOwner.
func (mr *MockmediaQueriesMockRecorder) DeleteMediaWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).DeleteMediaWithOwner), ctx, arg)
}

// FindMapReferencesForMedia mocks base method.
func (m *MockmediaQueries) FindMapReferencesForMedia(ctx context.Context, arg db.FindMapReferencesForMediaParams) ([]db.FindMapReferencesForMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMapReferencesForMedia", ctx, arg)
	ret0, _ := ret[0].([]db.FindMapReferencesForMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMapReferencesForMedia indicates an expected call of FindMapReferencesForMedia.
func (mr *MockmediaQueriesMockRecorder) FindMapReferencesForMedia(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMapReferencesForMedia", reflect.TypeOf((*MockmediaQueries)(nil).FindMapReferencesForMedia), ctx, arg)
}

// FindMediaReferencesInReadingSections mocks base method.
func (m *MockmediaQueries) FindMediaReferencesInReadingSections(ctx context.Context, arg db.FindMediaReferencesInReadingSectionsParams) ([]db.FindMediaReferencesInReadingSectionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMediaReferencesInReadingSections", ctx, arg)
	ret0, _ := ret[0].([]db.FindMediaReferencesInReadingSectionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMediaReferencesInReadingSections indicates an expected call of FindMediaReferencesInReadingSections.
func (mr *MockmediaQueriesMockRecorder) FindMediaReferencesInReadingSections(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMediaReferencesInReadingSections", reflect.TypeOf((*MockmediaQueries)(nil).FindMediaReferencesInReadingSections), ctx, arg)
}

// FindRoleSheetReferencesForMedia mocks base method.
func (m *MockmediaQueries) FindRoleSheetReferencesForMedia(ctx context.Context, arg db.FindRoleSheetReferencesForMediaParams) ([]db.FindRoleSheetReferencesForMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoleSheetReferencesForMedia", ctx, arg)
	ret0, _ := ret[0].([]db.FindRoleSheetReferencesForMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoleSheetReferencesForMedia indicates an expected call of FindRoleSheetReferencesForMedia.
func (mr *MockmediaQueriesMockRecorder) FindRoleSheetReferencesForMedia(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoleSheetReferencesForMedia", reflect.TypeOf((*MockmediaQueries)(nil).FindRoleSheetReferencesForMedia), ctx, arg)
}

// FindThemeCoverReferencesForMedia mocks base method.
func (m *MockmediaQueries) FindThemeCoverReferencesForMedia(ctx context.Context, arg db.FindThemeCoverReferencesForMediaParams) ([]db.FindThemeCoverReferencesForMediaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindThemeCoverReferencesForMedia", ctx, arg)
	ret0, _ := ret[0].([]db.FindThemeCoverReferencesForMediaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindThemeCoverReferencesForMedia indicates an expected call of FindThemeCoverReferencesForMedia.
func (mr *MockmediaQueriesMockRecorder) FindThemeCoverReferencesForMedia(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindThemeCoverReferencesForMedia", reflect.TypeOf((*MockmediaQueries)(nil).FindThemeCoverReferencesForMedia), ctx, arg)
}

// GetMedia mocks base method.
func (m *MockmediaQueries) GetMedia(ctx context.Context, id uuid.UUID) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedia", ctx, id)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedia indicates an expected call of GetMedia.
func (mr *MockmediaQueriesMockRecorder) GetMedia(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedia", reflect.TypeOf((*MockmediaQueries)(nil).GetMedia), ctx, id)
}

// GetMediaCategoryWithOwner mocks base method.
func (m *MockmediaQueries) GetMediaCategoryWithOwner(ctx context.Context, arg db.GetMediaCategoryWithOwnerParams) (db.ThemeMediaCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaCategoryWithOwner", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMediaCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaCategoryWithOwner indicates an expected call of GetMediaCategoryWithOwner.
func (mr *MockmediaQueriesMockRecorder) GetMediaCategoryWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaCategoryWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).GetMediaCategoryWithOwner), ctx, arg)
}

// GetMediaForSession mocks base method.
func (m *MockmediaQueries) GetMediaForSession(ctx context.Context, arg db.GetMediaForSessionParams) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaForSession", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaForSession indicates an expected call of GetMediaForSession.
func (mr *MockmediaQueriesMockRecorder) GetMediaForSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaForSession", reflect.TypeOf((*MockmediaQueries)(nil).GetMediaForSession), ctx, arg)
}

// GetMediaReplacementUploadWithOwner mocks base method.
func (m *MockmediaQueries) GetMediaReplacementUploadWithOwner(ctx context.Context, arg db.GetMediaReplacementUploadWithOwnerParams) (db.ThemeMediaReplacementUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaReplacementUploadWithOwner", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMediaReplacementUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaReplacementUploadWithOwner indicates an expected call of GetMediaReplacementUploadWithOwner.
func (mr *MockmediaQueriesMockRecorder) GetMediaReplacementUploadWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaReplacementUploadWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).GetMediaReplacementUploadWithOwner), ctx, arg)
}

// GetMediaWithOwner mocks base method.
func (m *MockmediaQueries) GetMediaWithOwner(ctx context.Context, arg db.GetMediaWithOwnerParams) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaWithOwner", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaWithOwner indicates an expected call of GetMediaWithOwner.
func (mr *MockmediaQueriesMockRecorder) GetMediaWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).GetMediaWithOwner), ctx, arg)
}

// GetTheme mocks base method.
func (m *MockmediaQueries) GetTheme(ctx context.Context, id uuid.UUID) (db.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", ctx, id)
	ret0, _ := ret[0].(db.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockmediaQueriesMockRecorder) GetTheme(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockmediaQueries)(nil).GetTheme), ctx, id)
}

// ListMediaByTheme mocks base method.
func (m *MockmediaQueries) ListMediaByTheme(ctx context.Context, themeID uuid.UUID) ([]db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMediaByTheme", ctx, themeID)
	ret0, _ := ret[0].([]db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMediaByTheme indicates an expected call of ListMediaByTheme.
func (mr *MockmediaQueriesMockRecorder) ListMediaByTheme(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMediaByTheme", reflect.TypeOf((*MockmediaQueries)(nil).ListMediaByTheme), ctx, themeID)
}

// ListMediaByThemeAndCategory mocks base method.
func (m *MockmediaQueries) ListMediaByThemeAndCategory(ctx context.Context, arg db.ListMediaByThemeAndCategoryParams) ([]db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMediaByThemeAndCategory", ctx, arg)
	ret0, _ := ret[0].([]db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMediaByThemeAndCategory indicates an expected call of ListMediaByThemeAndCategory.
func (mr *MockmediaQueriesMockRecorder) ListMediaByThemeAndCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMediaByThemeAndCategory", reflect.TypeOf((*MockmediaQueries)(nil).ListMediaByThemeAndCategory), ctx, arg)
}

// ListMediaByThemeAndType mocks base method.
func (m *MockmediaQueries) ListMediaByThemeAndType(ctx context.Context, arg db.ListMediaByThemeAndTypeParams) ([]db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMediaByThemeAndType", ctx, arg)
	ret0, _ := ret[0].([]db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMediaByThemeAndType indicates an expected call of ListMediaByThemeAndType.
func (mr *MockmediaQueriesMockRecorder) ListMediaByThemeAndType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMediaByThemeAndType", reflect.TypeOf((*MockmediaQueries)(nil).ListMediaByThemeAndType), ctx, arg)
}

// ListMediaByThemeTypeAndCategory mocks base method.
func (m *MockmediaQueries) ListMediaByThemeTypeAndCategory(ctx context.Context, arg db.ListMediaByThemeTypeAndCategoryParams) ([]db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMediaByThemeTypeAndCategory", ctx, arg)
	ret0, _ := ret[0].([]db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMediaByThemeTypeAndCategory indicates an expected call of ListMediaByThemeTypeAndCategory.
func (mr *MockmediaQueriesMockRecorder) ListMediaByThemeTypeAndCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMediaByThemeTypeAndCategory", reflect.TypeOf((*MockmediaQueries)(nil).ListMediaByThemeTypeAndCategory), ctx, arg)
}

// ListMediaCategoriesByTheme mocks base method.
func (m *MockmediaQueries) ListMediaCategoriesByTheme(ctx context.Context, themeID uuid.UUID) ([]db.ThemeMediaCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMediaCategoriesByTheme", ctx, themeID)
	ret0, _ := ret[0].([]db.ThemeMediaCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMediaCategoriesByTheme indicates an expected call of ListMediaCategoriesByTheme.
func (mr *MockmediaQueriesMockRecorder) ListMediaCategoriesByTheme(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMediaCategoriesByTheme", reflect.TypeOf((*MockmediaQueries)(nil).ListMediaCategoriesByTheme), ctx, themeID)
}

// SumMediaSizeByCreator mocks base method.
func (m *MockmediaQueries) SumMediaSizeByCreator(ctx context.Context, creatorID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumMediaSizeByCreator", ctx, creatorID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumMediaSizeByCreator indicates an expected call of SumMediaSizeByCreator.
func (mr *MockmediaQueriesMockRecorder) SumMediaSizeByCreator(ctx, creatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumMediaSizeByCreator", reflect.TypeOf((*MockmediaQueries)(nil).SumMediaSizeByCreator), ctx, creatorID)
}

// SumMediaSizeByTheme mocks base method.
func (m *MockmediaQueries) SumMediaSizeByTheme(ctx context.Context, themeID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumMediaSizeByTheme", ctx, themeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumMediaSizeByTheme indicates an expected call of SumMediaSizeByTheme.
func (mr *MockmediaQueriesMockRecorder) SumMediaSizeByTheme(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumMediaSizeByTheme", reflect.TypeOf((*MockmediaQueries)(nil).SumMediaSizeByTheme), ctx, themeID)
}

// UpdateMedia mocks base method.
func (m *MockmediaQueries) UpdateMedia(ctx context.Context, arg db.UpdateMediaParams) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMedia", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMedia indicates an expected call of UpdateMedia.
func (mr *MockmediaQueriesMockRecorder) UpdateMedia(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMedia", reflect.TypeOf((*MockmediaQueries)(nil).UpdateMedia), ctx, arg)
}

// UpdateMediaCategory mocks base method.
func (m *MockmediaQueries) UpdateMediaCategory(ctx context.Context, arg db.UpdateMediaCategoryParams) (db.ThemeMediaCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMediaCategory", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMediaCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMediaCategory indicates an expected call of UpdateMediaCategory.
func (mr *MockmediaQueriesMockRecorder) UpdateMediaCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMediaCategory", reflect.TypeOf((*MockmediaQueries)(nil).UpdateMediaCategory), ctx, arg)
}

// UpdateMediaFileWithOwner mocks base method.
func (m *MockmediaQueries) UpdateMediaFileWithOwner(ctx context.Context, arg db.UpdateMediaFileWithOwnerParams) (db.ThemeMedium, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMediaFileWithOwner", ctx, arg)
	ret0, _ := ret[0].(db.ThemeMedium)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMediaFileWithOwner indicates an expected call of UpdateMediaFileWithOwner.
func (mr *MockmediaQueriesMockRecorder) UpdateMediaFileWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMediaFileWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).UpdateMediaFileWithOwner), ctx, arg)
}

// UpdateThemeConfigJsonWithOwner mocks base method.
func (m *MockmediaQueries) UpdateThemeConfigJsonWithOwner(ctx context.Context, arg db.UpdateThemeConfigJsonWithOwnerParams) (db.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThemeConfigJsonWithOwner", ctx, arg)
	ret0, _ := ret[0].(db.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateThemeConfigJsonWithOwner indicates an expected call of UpdateThemeConfigJsonWithOwner.
func (mr *MockmediaQueriesMockRecorder) UpdateThemeConfigJsonWithOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThemeConfigJsonWithOwner", reflect.TypeOf((*MockmediaQueries)(nil).UpdateThemeConfigJsonWithOwner), ctx, arg)
}
