// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	uuid "github.com/google/uuid"
	profile "github.com/mmp-platform/server/internal/domain/profile"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetNotificationPrefs mocks base method.
func (m *MockService) GetNotificationPrefs(ctx context.Context, userID uuid.UUID) (*profile.NotificationPrefsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationPrefs", ctx, userID)
	ret0, _ := ret[0].(*profile.NotificationPrefsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationPrefs indicates an expected call of GetNotificationPrefs.
func (mr *MockServiceMockRecorder) GetNotificationPrefs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationPrefs", reflect.TypeOf((*MockService)(nil).GetNotificationPrefs), ctx, userID)
}

// GetProfile mocks base method.
func (m *MockService) GetProfile(ctx context.Context, userID uuid.UUID) (*profile.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*profile.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockServiceMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockService)(nil).GetProfile), ctx, userID)
}

// GetPublicProfile mocks base method.
func (m *MockService) GetPublicProfile(ctx context.Context, userID uuid.UUID) (*profile.PublicProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicProfile", ctx, userID)
	ret0, _ := ret[0].(*profile.PublicProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicProfile indicates an expected call of GetPublicProfile.
func (mr *MockServiceMockRecorder) GetPublicProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProfile", reflect.TypeOf((*MockService)(nil).GetPublicProfile), ctx, userID)
}

// UpdateAvatar mocks base method.
func (m *MockService) UpdateAvatar(ctx context.Context, userID uuid.UUID, file multipart.File, header *multipart.FileHeader) (*profile.AvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, file, header)
	ret0, _ := ret[0].(*profile.AvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockServiceMockRecorder) UpdateAvatar(ctx, userID, file, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockService)(nil).UpdateAvatar), ctx, userID, file, header)
}

// UpdateNotificationPrefs mocks base method.
func (m *MockService) UpdateNotificationPrefs(ctx context.Context, userID uuid.UUID, req profile.UpdateNotificationPrefsRequest) (*profile.NotificationPrefsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationPrefs", ctx, userID, req)
	ret0, _ := ret[0].(*profile.NotificationPrefsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNotificationPrefs indicates an expected call of UpdateNotificationPrefs.
func (mr *MockServiceMockRecorder) UpdateNotificationPrefs(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationPrefs", reflect.TypeOf((*MockService)(nil).UpdateNotificationPrefs), ctx, userID, req)
}

// UpdateProfile mocks base method.
func (m *MockService) UpdateProfile(ctx context.Context, userID uuid.UUID, req profile.UpdateProfileRequest) (*profile.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, req)
	ret0, _ := ret[0].(*profile.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockServiceMockRecorder) UpdateProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockService)(nil).UpdateProfile), ctx, userID, req)
}
