// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	room "github.com/mmp-platform/server/internal/domain/room"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockService) CreateRoom(ctx context.Context, hostID uuid.UUID, req room.CreateRoomRequest) (*room.RoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, hostID, req)
	ret0, _ := ret[0].(*room.RoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockServiceMockRecorder) CreateRoom(ctx, hostID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockService)(nil).CreateRoom), ctx, hostID, req)
}

// GetRoom mocks base method.
func (m *MockService) GetRoom(ctx context.Context, roomID uuid.UUID) (*room.RoomDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*room.RoomDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockServiceMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockService)(nil).GetRoom), ctx, roomID)
}

// GetRoomByCode mocks base method.
func (m *MockService) GetRoomByCode(ctx context.Context, code string) (*room.RoomDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByCode", ctx, code)
	ret0, _ := ret[0].(*room.RoomDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByCode indicates an expected call of GetRoomByCode.
func (mr *MockServiceMockRecorder) GetRoomByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByCode", reflect.TypeOf((*MockService)(nil).GetRoomByCode), ctx, code)
}

// JoinRoom mocks base method.
func (m *MockService) JoinRoom(ctx context.Context, roomID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", ctx, roomID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockServiceMockRecorder) JoinRoom(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockService)(nil).JoinRoom), ctx, roomID, userID)
}

// LeaveRoom mocks base method.
func (m *MockService) LeaveRoom(ctx context.Context, roomID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveRoom", ctx, roomID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveRoom indicates an expected call of LeaveRoom.
func (mr *MockServiceMockRecorder) LeaveRoom(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveRoom", reflect.TypeOf((*MockService)(nil).LeaveRoom), ctx, roomID, userID)
}

// ListWaitingRooms mocks base method.
func (m *MockService) ListWaitingRooms(ctx context.Context, limit, offset int32) ([]room.RoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWaitingRooms", ctx, limit, offset)
	ret0, _ := ret[0].([]room.RoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWaitingRooms indicates an expected call of ListWaitingRooms.
func (mr *MockServiceMockRecorder) ListWaitingRooms(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWaitingRooms", reflect.TypeOf((*MockService)(nil).ListWaitingRooms), ctx, limit, offset)
}

// StartRoom mocks base method.
func (m *MockService) StartRoom(ctx context.Context, roomID, hostID uuid.UUID, req room.StartRoomRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRoom", ctx, roomID, hostID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartRoom indicates an expected call of StartRoom.
func (mr *MockServiceMockRecorder) StartRoom(ctx, roomID, hostID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRoom", reflect.TypeOf((*MockService)(nil).StartRoom), ctx, roomID, hostID, req)
}

// MockGameStarter is a mock of GameStarter interface.
type MockGameStarter struct {
	ctrl     *gomock.Controller
	recorder *MockGameStarterMockRecorder
	isgomock struct{}
}

// MockGameStarterMockRecorder is the mock recorder for MockGameStarter.
type MockGameStarterMockRecorder struct {
	mock *MockGameStarter
}

// NewMockGameStarter creates a new mock instance.
func NewMockGameStarter(ctrl *gomock.Controller) *MockGameStarter {
	mock := &MockGameStarter{ctrl: ctrl}
	mock.recorder = &MockGameStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameStarter) EXPECT() *MockGameStarterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockGameStarter) Start(ctx context.Context, roomID uuid.UUID, configJSON []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, roomID, configJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockGameStarterMockRecorder) Start(ctx, roomID, configJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockGameStarter)(nil).Start), ctx, roomID, configJSON)
}
