// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	flow "github.com/mmp-platform/server/internal/domain/flow"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateEdge mocks base method.
func (m *MockService) CreateEdge(ctx context.Context, creatorID, themeID uuid.UUID, req flow.CreateEdgeRequest) (*flow.FlowEdge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEdge", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*flow.FlowEdge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEdge indicates an expected call of CreateEdge.
func (mr *MockServiceMockRecorder) CreateEdge(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEdge", reflect.TypeOf((*MockService)(nil).CreateEdge), ctx, creatorID, themeID, req)
}

// CreateNode mocks base method.
func (m *MockService) CreateNode(ctx context.Context, creatorID, themeID uuid.UUID, req flow.CreateNodeRequest) (*flow.FlowNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNode", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*flow.FlowNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNode indicates an expected call of CreateNode.
func (mr *MockServiceMockRecorder) CreateNode(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNode", reflect.TypeOf((*MockService)(nil).CreateNode), ctx, creatorID, themeID, req)
}

// DeleteEdge mocks base method.
func (m *MockService) DeleteEdge(ctx context.Context, creatorID, themeID, edgeID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdge", ctx, creatorID, themeID, edgeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdge indicates an expected call of DeleteEdge.
func (mr *MockServiceMockRecorder) DeleteEdge(ctx, creatorID, themeID, edgeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdge", reflect.TypeOf((*MockService)(nil).DeleteEdge), ctx, creatorID, themeID, edgeID)
}

// DeleteNode mocks base method.
func (m *MockService) DeleteNode(ctx context.Context, creatorID, themeID, nodeID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, creatorID, themeID, nodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockServiceMockRecorder) DeleteNode(ctx, creatorID, themeID, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockService)(nil).DeleteNode), ctx, creatorID, themeID, nodeID)
}

// GetFlow mocks base method.
func (m *MockService) GetFlow(ctx context.Context, creatorID, themeID uuid.UUID) (*flow.FlowGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlow", ctx, creatorID, themeID)
	ret0, _ := ret[0].(*flow.FlowGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlow indicates an expected call of GetFlow.
func (mr *MockServiceMockRecorder) GetFlow(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlow", reflect.TypeOf((*MockService)(nil).GetFlow), ctx, creatorID, themeID)
}

// MigratePhases mocks base method.
func (m *MockService) MigratePhases(ctx context.Context, themeID uuid.UUID, phases []map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigratePhases", ctx, themeID, phases)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigratePhases indicates an expected call of MigratePhases.
func (mr *MockServiceMockRecorder) MigratePhases(ctx, themeID, phases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigratePhases", reflect.TypeOf((*MockService)(nil).MigratePhases), ctx, themeID, phases)
}

// SaveFlow mocks base method.
func (m *MockService) SaveFlow(ctx context.Context, creatorID, themeID uuid.UUID, req flow.SaveFlowRequest) (*flow.FlowGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFlow", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*flow.FlowGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFlow indicates an expected call of SaveFlow.
func (mr *MockServiceMockRecorder) SaveFlow(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFlow", reflect.TypeOf((*MockService)(nil).SaveFlow), ctx, creatorID, themeID, req)
}

// UpdateEdge mocks base method.
func (m *MockService) UpdateEdge(ctx context.Context, creatorID, themeID, edgeID uuid.UUID, req flow.UpdateEdgeRequest) (*flow.FlowEdge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEdge", ctx, creatorID, themeID, edgeID, req)
	ret0, _ := ret[0].(*flow.FlowEdge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEdge indicates an expected call of UpdateEdge.
func (mr *MockServiceMockRecorder) UpdateEdge(ctx, creatorID, themeID, edgeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEdge", reflect.TypeOf((*MockService)(nil).UpdateEdge), ctx, creatorID, themeID, edgeID, req)
}

// UpdateNode mocks base method.
func (m *MockService) UpdateNode(ctx context.Context, creatorID, themeID, nodeID uuid.UUID, req flow.UpdateNodeRequest) (*flow.FlowNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNode", ctx, creatorID, themeID, nodeID, req)
	ret0, _ := ret[0].(*flow.FlowNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNode indicates an expected call of UpdateNode.
func (mr *MockServiceMockRecorder) UpdateNode(ctx, creatorID, themeID, nodeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNode", reflect.TypeOf((*MockService)(nil).UpdateNode), ctx, creatorID, themeID, nodeID, req)
}
