// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	uuid "github.com/google/uuid"
	editor "github.com/mmp-platform/server/internal/domain/editor"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateCharacter mocks base method.
func (m *MockService) CreateCharacter(ctx context.Context, creatorID, themeID uuid.UUID, req editor.CreateCharacterRequest) (*editor.CharacterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCharacter", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*editor.CharacterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCharacter indicates an expected call of CreateCharacter.
func (mr *MockServiceMockRecorder) CreateCharacter(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCharacter", reflect.TypeOf((*MockService)(nil).CreateCharacter), ctx, creatorID, themeID, req)
}

// CreateClue mocks base method.
func (m *MockService) CreateClue(ctx context.Context, creatorID, themeID uuid.UUID, req editor.CreateClueRequest) (*editor.ClueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClue", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*editor.ClueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClue indicates an expected call of CreateClue.
func (mr *MockServiceMockRecorder) CreateClue(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClue", reflect.TypeOf((*MockService)(nil).CreateClue), ctx, creatorID, themeID, req)
}

// CreateLocation mocks base method.
func (m *MockService) CreateLocation(ctx context.Context, creatorID, themeID, mapID uuid.UUID, req editor.CreateLocationRequest) (*editor.LocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", ctx, creatorID, themeID, mapID, req)
	ret0, _ := ret[0].(*editor.LocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MockServiceMockRecorder) CreateLocation(ctx, creatorID, themeID, mapID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MockService)(nil).CreateLocation), ctx, creatorID, themeID, mapID, req)
}

// CreateMap mocks base method.
func (m *MockService) CreateMap(ctx context.Context, creatorID, themeID uuid.UUID, req editor.CreateMapRequest) (*editor.MapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMap", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*editor.MapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMap indicates an expected call of CreateMap.
func (mr *MockServiceMockRecorder) CreateMap(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMap", reflect.TypeOf((*MockService)(nil).CreateMap), ctx, creatorID, themeID, req)
}

// CreateTheme mocks base method.
func (m *MockService) CreateTheme(ctx context.Context, creatorID uuid.UUID, req editor.CreateThemeRequest) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTheme", ctx, creatorID, req)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTheme indicates an expected call of CreateTheme.
func (mr *MockServiceMockRecorder) CreateTheme(ctx, creatorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTheme", reflect.TypeOf((*MockService)(nil).CreateTheme), ctx, creatorID, req)
}

// DeleteCharacter mocks base method.
func (m *MockService) DeleteCharacter(ctx context.Context, creatorID, charID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCharacter", ctx, creatorID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCharacter indicates an expected call of DeleteCharacter.
func (mr *MockServiceMockRecorder) DeleteCharacter(ctx, creatorID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCharacter", reflect.TypeOf((*MockService)(nil).DeleteCharacter), ctx, creatorID, charID)
}

// DeleteClue mocks base method.
func (m *MockService) DeleteClue(ctx context.Context, creatorID, clueID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClue", ctx, creatorID, clueID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClue indicates an expected call of DeleteClue.
func (mr *MockServiceMockRecorder) DeleteClue(ctx, creatorID, clueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClue", reflect.TypeOf((*MockService)(nil).DeleteClue), ctx, creatorID, clueID)
}

// DeleteLocation mocks base method.
func (m *MockService) DeleteLocation(ctx context.Context, creatorID, locID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLocation", ctx, creatorID, locID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLocation indicates an expected call of DeleteLocation.
func (mr *MockServiceMockRecorder) DeleteLocation(ctx, creatorID, locID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLocation", reflect.TypeOf((*MockService)(nil).DeleteLocation), ctx, creatorID, locID)
}

// DeleteMap mocks base method.
func (m *MockService) DeleteMap(ctx context.Context, creatorID, mapID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMap", ctx, creatorID, mapID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMap indicates an expected call of DeleteMap.
func (mr *MockServiceMockRecorder) DeleteMap(ctx, creatorID, mapID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMap", reflect.TypeOf((*MockService)(nil).DeleteMap), ctx, creatorID, mapID)
}

// DeleteTheme mocks base method.
func (m *MockService) DeleteTheme(ctx context.Context, creatorID, themeID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTheme", ctx, creatorID, themeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTheme indicates an expected call of DeleteTheme.
func (mr *MockServiceMockRecorder) DeleteTheme(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTheme", reflect.TypeOf((*MockService)(nil).DeleteTheme), ctx, creatorID, themeID)
}

// GetCharacterRoleSheet mocks base method.
func (m *MockService) GetCharacterRoleSheet(ctx context.Context, creatorID, charID uuid.UUID) (*editor.RoleSheetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterRoleSheet", ctx, creatorID, charID)
	ret0, _ := ret[0].(*editor.RoleSheetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterRoleSheet indicates an expected call of GetCharacterRoleSheet.
func (mr *MockServiceMockRecorder) GetCharacterRoleSheet(ctx, creatorID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterRoleSheet", reflect.TypeOf((*MockService)(nil).GetCharacterRoleSheet), ctx, creatorID, charID)
}

// GetClueEdges mocks base method.
func (m *MockService) GetClueEdges(ctx context.Context, creatorID, themeID uuid.UUID) ([]editor.ClueEdgeGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClueEdges", ctx, creatorID, themeID)
	ret0, _ := ret[0].([]editor.ClueEdgeGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClueEdges indicates an expected call of GetClueEdges.
func (mr *MockServiceMockRecorder) GetClueEdges(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClueEdges", reflect.TypeOf((*MockService)(nil).GetClueEdges), ctx, creatorID, themeID)
}

// GetContent mocks base method.
func (m *MockService) GetContent(ctx context.Context, creatorID, themeID uuid.UUID, key string) (*editor.ContentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", ctx, creatorID, themeID, key)
	ret0, _ := ret[0].(*editor.ContentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockServiceMockRecorder) GetContent(ctx, creatorID, themeID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockService)(nil).GetContent), ctx, creatorID, themeID, key)
}

// GetModuleSchemas mocks base method.
func (m *MockService) GetModuleSchemas(ctx context.Context) (map[string]json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleSchemas", ctx)
	ret0, _ := ret[0].(map[string]json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleSchemas indicates an expected call of GetModuleSchemas.
func (mr *MockServiceMockRecorder) GetModuleSchemas(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleSchemas", reflect.TypeOf((*MockService)(nil).GetModuleSchemas), ctx)
}

// GetTheme mocks base method.
func (m *MockService) GetTheme(ctx context.Context, creatorID, themeID uuid.UUID) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", ctx, creatorID, themeID)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockServiceMockRecorder) GetTheme(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockService)(nil).GetTheme), ctx, creatorID, themeID)
}

// GetThemeBySlug mocks base method.
func (m *MockService) GetThemeBySlug(ctx context.Context, creatorID uuid.UUID, slug string) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeBySlug", ctx, creatorID, slug)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeBySlug indicates an expected call of GetThemeBySlug.
func (mr *MockServiceMockRecorder) GetThemeBySlug(ctx, creatorID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeBySlug", reflect.TypeOf((*MockService)(nil).GetThemeBySlug), ctx, creatorID, slug)
}

// ListCharacters mocks base method.
func (m *MockService) ListCharacters(ctx context.Context, creatorID, themeID uuid.UUID) ([]editor.CharacterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCharacters", ctx, creatorID, themeID)
	ret0, _ := ret[0].([]editor.CharacterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCharacters indicates an expected call of ListCharacters.
func (mr *MockServiceMockRecorder) ListCharacters(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCharacters", reflect.TypeOf((*MockService)(nil).ListCharacters), ctx, creatorID, themeID)
}

// ListClues mocks base method.
func (m *MockService) ListClues(ctx context.Context, creatorID, themeID uuid.UUID) ([]editor.ClueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClues", ctx, creatorID, themeID)
	ret0, _ := ret[0].([]editor.ClueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClues indicates an expected call of ListClues.
func (mr *MockServiceMockRecorder) ListClues(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClues", reflect.TypeOf((*MockService)(nil).ListClues), ctx, creatorID, themeID)
}

// ListLocations mocks base method.
func (m *MockService) ListLocations(ctx context.Context, creatorID, themeID uuid.UUID) ([]editor.LocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLocations", ctx, creatorID, themeID)
	ret0, _ := ret[0].([]editor.LocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLocations indicates an expected call of ListLocations.
func (mr *MockServiceMockRecorder) ListLocations(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLocations", reflect.TypeOf((*MockService)(nil).ListLocations), ctx, creatorID, themeID)
}

// ListMaps mocks base method.
func (m *MockService) ListMaps(ctx context.Context, creatorID, themeID uuid.UUID) ([]editor.MapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMaps", ctx, creatorID, themeID)
	ret0, _ := ret[0].([]editor.MapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMaps indicates an expected call of ListMaps.
func (mr *MockServiceMockRecorder) ListMaps(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMaps", reflect.TypeOf((*MockService)(nil).ListMaps), ctx, creatorID, themeID)
}

// ListMyThemes mocks base method.
func (m *MockService) ListMyThemes(ctx context.Context, creatorID uuid.UUID) ([]editor.ThemeSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyThemes", ctx, creatorID)
	ret0, _ := ret[0].([]editor.ThemeSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyThemes indicates an expected call of ListMyThemes.
func (mr *MockServiceMockRecorder) ListMyThemes(ctx, creatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyThemes", reflect.TypeOf((*MockService)(nil).ListMyThemes), ctx, creatorID)
}

// PublishTheme mocks base method.
func (m *MockService) PublishTheme(ctx context.Context, creatorID, themeID uuid.UUID) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTheme", ctx, creatorID, themeID)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishTheme indicates an expected call of PublishTheme.
func (mr *MockServiceMockRecorder) PublishTheme(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTheme", reflect.TypeOf((*MockService)(nil).PublishTheme), ctx, creatorID, themeID)
}

// ReplaceClueEdges mocks base method.
func (m *MockService) ReplaceClueEdges(ctx context.Context, creatorID, themeID uuid.UUID, reqs []editor.ClueEdgeGroupRequest) ([]editor.ClueEdgeGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceClueEdges", ctx, creatorID, themeID, reqs)
	ret0, _ := ret[0].([]editor.ClueEdgeGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceClueEdges indicates an expected call of ReplaceClueEdges.
func (mr *MockServiceMockRecorder) ReplaceClueEdges(ctx, creatorID, themeID, reqs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceClueEdges", reflect.TypeOf((*MockService)(nil).ReplaceClueEdges), ctx, creatorID, themeID, reqs)
}

// SubmitForReview mocks base method.
func (m *MockService) SubmitForReview(ctx context.Context, userID, themeID uuid.UUID) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitForReview", ctx, userID, themeID)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitForReview indicates an expected call of SubmitForReview.
func (mr *MockServiceMockRecorder) SubmitForReview(ctx, userID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitForReview", reflect.TypeOf((*MockService)(nil).SubmitForReview), ctx, userID, themeID)
}

// UnpublishTheme mocks base method.
func (m *MockService) UnpublishTheme(ctx context.Context, creatorID, themeID uuid.UUID) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishTheme", ctx, creatorID, themeID)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnpublishTheme indicates an expected call of UnpublishTheme.
func (mr *MockServiceMockRecorder) UnpublishTheme(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishTheme", reflect.TypeOf((*MockService)(nil).UnpublishTheme), ctx, creatorID, themeID)
}

// UpdateCharacter mocks base method.
func (m *MockService) UpdateCharacter(ctx context.Context, creatorID, charID uuid.UUID, req editor.UpdateCharacterRequest) (*editor.CharacterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCharacter", ctx, creatorID, charID, req)
	ret0, _ := ret[0].(*editor.CharacterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCharacter indicates an expected call of UpdateCharacter.
func (mr *MockServiceMockRecorder) UpdateCharacter(ctx, creatorID, charID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCharacter", reflect.TypeOf((*MockService)(nil).UpdateCharacter), ctx, creatorID, charID, req)
}

// UpdateClue mocks base method.
func (m *MockService) UpdateClue(ctx context.Context, creatorID, clueID uuid.UUID, req editor.UpdateClueRequest) (*editor.ClueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClue", ctx, creatorID, clueID, req)
	ret0, _ := ret[0].(*editor.ClueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClue indicates an expected call of UpdateClue.
func (mr *MockServiceMockRecorder) UpdateClue(ctx, creatorID, clueID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClue", reflect.TypeOf((*MockService)(nil).UpdateClue), ctx, creatorID, clueID, req)
}

// UpdateConfigJson mocks base method.
func (m *MockService) UpdateConfigJson(ctx context.Context, creatorID, themeID uuid.UUID, config json.RawMessage) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigJson", ctx, creatorID, themeID, config)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConfigJson indicates an expected call of UpdateConfigJson.
func (mr *MockServiceMockRecorder) UpdateConfigJson(ctx, creatorID, themeID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigJson", reflect.TypeOf((*MockService)(nil).UpdateConfigJson), ctx, creatorID, themeID, config)
}

// UpdateLocation mocks base method.
func (m *MockService) UpdateLocation(ctx context.Context, creatorID, locID uuid.UUID, req editor.UpdateLocationRequest) (*editor.LocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, creatorID, locID, req)
	ret0, _ := ret[0].(*editor.LocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockServiceMockRecorder) UpdateLocation(ctx, creatorID, locID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockService)(nil).UpdateLocation), ctx, creatorID, locID, req)
}

// UpdateMap mocks base method.
func (m *MockService) UpdateMap(ctx context.Context, creatorID, mapID uuid.UUID, req editor.UpdateMapRequest) (*editor.MapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMap", ctx, creatorID, mapID, req)
	ret0, _ := ret[0].(*editor.MapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMap indicates an expected call of UpdateMap.
func (mr *MockServiceMockRecorder) UpdateMap(ctx, creatorID, mapID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMap", reflect.TypeOf((*MockService)(nil).UpdateMap), ctx, creatorID, mapID, req)
}

// UpdateTheme mocks base method.
func (m *MockService) UpdateTheme(ctx context.Context, creatorID, themeID uuid.UUID, req editor.UpdateThemeRequest) (*editor.ThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTheme", ctx, creatorID, themeID, req)
	ret0, _ := ret[0].(*editor.ThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTheme indicates an expected call of UpdateTheme.
func (mr *MockServiceMockRecorder) UpdateTheme(ctx, creatorID, themeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTheme", reflect.TypeOf((*MockService)(nil).UpdateTheme), ctx, creatorID, themeID, req)
}

// UpsertCharacterRoleSheet mocks base method.
func (m *MockService) UpsertCharacterRoleSheet(ctx context.Context, creatorID, charID uuid.UUID, req editor.UpsertRoleSheetRequest) (*editor.RoleSheetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCharacterRoleSheet", ctx, creatorID, charID, req)
	ret0, _ := ret[0].(*editor.RoleSheetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCharacterRoleSheet indicates an expected call of UpsertCharacterRoleSheet.
func (mr *MockServiceMockRecorder) UpsertCharacterRoleSheet(ctx, creatorID, charID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCharacterRoleSheet", reflect.TypeOf((*MockService)(nil).UpsertCharacterRoleSheet), ctx, creatorID, charID, req)
}

// UpsertContent mocks base method.
func (m *MockService) UpsertContent(ctx context.Context, creatorID, themeID uuid.UUID, key, body string) (*editor.ContentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertContent", ctx, creatorID, themeID, key, body)
	ret0, _ := ret[0].(*editor.ContentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertContent indicates an expected call of UpsertContent.
func (mr *MockServiceMockRecorder) UpsertContent(ctx, creatorID, themeID, key, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertContent", reflect.TypeOf((*MockService)(nil).UpsertContent), ctx, creatorID, themeID, key, body)
}

// ValidateTheme mocks base method.
func (m *MockService) ValidateTheme(ctx context.Context, creatorID, themeID uuid.UUID) (*editor.ValidationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTheme", ctx, creatorID, themeID)
	ret0, _ := ret[0].(*editor.ValidationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateTheme indicates an expected call of ValidateTheme.
func (mr *MockServiceMockRecorder) ValidateTheme(ctx, creatorID, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTheme", reflect.TypeOf((*MockService)(nil).ValidateTheme), ctx, creatorID, themeID)
}
