// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mmp-platform/server/internal/engine (interfaces: PlayerStatusController)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_player_status_controller.go -package=mocks github.com/mmp-platform/server/internal/engine PlayerStatusController
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	engine "github.com/mmp-platform/server/internal/engine"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerStatusController is a mock of PlayerStatusController interface.
type MockPlayerStatusController struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerStatusControllerMockRecorder
	isgomock struct{}
}

// MockPlayerStatusControllerMockRecorder is the mock recorder for MockPlayerStatusController.
type MockPlayerStatusControllerMockRecorder struct {
	mock *MockPlayerStatusController
}

// NewMockPlayerStatusController creates a new mock instance.
func NewMockPlayerStatusController(ctrl *gomock.Controller) *MockPlayerStatusController {
	mock := &MockPlayerStatusController{ctrl: ctrl}
	mock.recorder = &MockPlayerStatusControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerStatusController) EXPECT() *MockPlayerStatusControllerMockRecorder {
	return m.recorder
}

// ApplyPlayerStatus mocks base method.
func (m *MockPlayerStatusController) ApplyPlayerStatus(ctx context.Context, action engine.PlayerStatusAction) (engine.PlayerRuntimeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPlayerStatus", ctx, action)
	ret0, _ := ret[0].(engine.PlayerRuntimeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyPlayerStatus indicates an expected call of ApplyPlayerStatus.
func (mr *MockPlayerStatusControllerMockRecorder) ApplyPlayerStatus(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPlayerStatus", reflect.TypeOf((*MockPlayerStatusController)(nil).ApplyPlayerStatus), ctx, action)
}
