package main

import (
	"fmt"
	"sort"
	"strings"
)

// render produces the TypeScript output for catalog + payloads.
//
// Layout (Phase 19 PR-1):
//
//  1. File header (do-not-edit, source, regenerate command).
//  2. WsEventType — const object + derived type alias.
//  3. WsEventDirection — Record<WsEventType, "c2s" | "s2c" | "bidi">.
//  4. WsEventCategory — Record<WsEventType, string>.
//  5. WsEventStatus   — Record<WsEventType, "active" | "stub" | "deprec">.
//  6. Payload interfaces (v1.5; placeholder block for v1).
//
// Entries are emitted in lexical Type order so diffs stay stable across
// source-file reordering.
func render(catalog []EventEntry, payloads []PayloadStruct) (string, error) {
	ordered := make([]EventEntry, len(catalog))
	copy(ordered, catalog)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Type < ordered[j].Type })

	var b strings.Builder
	b.WriteString(headerBlock)
	b.WriteString(renderEnum(ordered))
	b.WriteString(renderDirectionMap(ordered))
	b.WriteString(renderCategoryMap(ordered))
	b.WriteString(renderStatusMap(ordered))
	b.WriteString(renderPayloads(payloads))
	return b.String(), nil
}

const headerBlock = `// DO NOT EDIT — generated by apps/server/cmd/wsgen.
//
// Regenerate with:
//   cd apps/server && go run ./cmd/wsgen
//
// Source of truth: apps/server/internal/ws/envelope_catalog_*.go
// Any hand edit will be overwritten by the next go generate run.
// Phase 19 PR-1 (2026-04-18).

/* eslint-disable */
/* prettier-ignore */

`

func renderEnum(catalog []EventEntry) string {
	keys := assignEnumKeys(catalog)
	var b strings.Builder
	b.WriteString("/** All WebSocket event wire types. Single source of truth: Go Catalog. */\n")
	b.WriteString("export const WsEventType = {\n")
	for i, e := range catalog {
		if jsdoc := eventJSDoc(e); jsdoc != "" {
			b.WriteString(jsdoc)
		}
		fmt.Fprintf(&b, "  %s: %q,\n", keys[i], e.Type)
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export type WsEventType = (typeof WsEventType)[keyof typeof WsEventType];\n\n")
	return b.String()
}

// assignEnumKeys returns a per-index TS enum key for each catalog entry,
// collision-free even when the catalog holds both dot and colon variants
// of the same action (e.g. "reading.completed" and "reading:completed" —
// Phase 19 PR-1 carries both while awaiting Phase 20 normalisation).
//
// Policy: dot form is canonical and keeps the plain base key; colliding
// colon variants are suffixed "_LEGACY" so the generated object literal
// compiles and the legacy nature of the duplicate is visible at call-site
// (e.g. `WsEventType.PHASE_ENTERED_LEGACY`).
func assignEnumKeys(catalog []EventEntry) []string {
	// Pass 1: detect base-key collisions.
	baseFirstWire := make(map[string]string)
	collides := make(map[string]bool)
	for _, e := range catalog {
		base := enumKey(e.Type)
		if prev, seen := baseFirstWire[base]; seen && prev != e.Type {
			collides[base] = true
		} else {
			baseFirstWire[base] = e.Type
		}
	}
	// Pass 2: assign final keys.
	out := make([]string, len(catalog))
	for i, e := range catalog {
		base := enumKey(e.Type)
		key := base
		if collides[base] && strings.Contains(e.Type, ":") {
			key = base + "_LEGACY"
		}
		out[i] = key
	}
	return out
}

func renderDirectionMap(catalog []EventEntry) string {
	var b strings.Builder
	b.WriteString("/** Direction each event may travel. */\n")
	b.WriteString("export const WsEventDirection: Readonly<Record<WsEventType, \"c2s\" | \"s2c\" | \"bidi\">> = {\n")
	for _, e := range catalog {
		fmt.Fprintf(&b, "  %q: %q,\n", e.Type, e.Direction)
	}
	b.WriteString("} as const;\n\n")
	return b.String()
}

func renderCategoryMap(catalog []EventEntry) string {
	var b strings.Builder
	b.WriteString("/** Coarse grouping for docs / UI rendering. */\n")
	b.WriteString("export const WsEventCategory: Readonly<Record<WsEventType, string>> = {\n")
	for _, e := range catalog {
		fmt.Fprintf(&b, "  %q: %q,\n", e.Type, e.Category)
	}
	b.WriteString("} as const;\n\n")
	return b.String()
}

func renderStatusMap(catalog []EventEntry) string {
	var b strings.Builder
	b.WriteString("/** Lifecycle status. \"stub\" = reserved catalog entry, no server handler yet. */\n")
	b.WriteString("export const WsEventStatus: Readonly<Record<WsEventType, \"active\" | \"stub\" | \"deprec\">> = {\n")
	for _, e := range catalog {
		fmt.Fprintf(&b, "  %q: %q,\n", e.Type, e.Status)
	}
	b.WriteString("} as const;\n\n")
	return b.String()
}

// renderPayloads emits TS interface declarations for each Go struct the
// payload extractor returned (v1.5 α). If none are marked, a placeholder
// comment is emitted so the generated file layout stays stable.
func renderPayloads(payloads []PayloadStruct) string {
	if len(payloads) == 0 {
		return "// --- payload interfaces (v1.5; no //wsgen:payload structs found) ---\n"
	}
	var b strings.Builder
	b.WriteString("// --- payload interfaces (generated from Go structs marked //wsgen:payload) ---\n\n")
	for _, p := range payloads {
		if p.Comment != "" {
			b.WriteString("/**\n")
			for _, line := range strings.Split(p.Comment, "\n") {
				fmt.Fprintf(&b, " * %s\n", line)
			}
			b.WriteString(" */\n")
		}
		fmt.Fprintf(&b, "export interface %s {\n", p.Name)
		for _, f := range p.Fields {
			name := f.JSONName
			if f.Optional {
				name += "?"
			}
			fmt.Fprintf(&b, "  %s: %s;\n", name, f.TSType)
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// enumKey normalises a wire type string into a TS enum key:
//
//	"phase.advanced"      → "PHASE_ADVANCED"
//	"clue:trade_propose"  → "CLUE_TRADE_PROPOSE"
//	"auth.identify"       → "AUTH_IDENTIFY"
//	"ready.all_ready"     → "READY_ALL_READY"
func enumKey(wireType string) string {
	s := wireType
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, ":", "_")
	return strings.ToUpper(s)
}

func eventJSDoc(e EventEntry) string {
	lines := []string{fmt.Sprintf("%s · %s", strings.ToUpper(e.Direction), e.Category)}
	if e.Status != "active" {
		lines = append(lines, fmt.Sprintf("status=%s", e.Status))
	}
	if e.Note != "" {
		lines = append(lines, e.Note)
	}
	if len(lines) == 1 && e.Status == "active" && e.Note == "" {
		return fmt.Sprintf("  /** %s */\n", lines[0])
	}
	var b strings.Builder
	b.WriteString("  /**\n")
	for _, l := range lines {
		fmt.Fprintf(&b, "   * %s\n", l)
	}
	b.WriteString("   */\n")
	return b.String()
}
